[colors]
ansi = [
    '#090300',
    '#db2d20',
    '#01a252',
    '#fded02',
    '#01a0e4',
    '#a16a94',
    '#b5e4f4',
    '#a5a2a2',
]
background = '#f7f7f7'
brights = [
    '#5c5855',
    '#e8bbd0',
    '#3a3432',
    '#4a4543',
    '#807d7c',
    '#d6d5d4',
    '#cdab53',
    '#f7f7f7',
]
cursor_bg = '#4a4543'
cursor_border = '#4a4543'
cursor_fg = '#4a4543'
foreground = '#4a4543'

[colors.indexed]

[metadata]
name = '3024Day (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
