[colors]
ansi = [
    '#000000',
    '#fd5ff1',
    '#87c38a',
    '#ffd7b1',
    '#85befd',
    '#b9b6fc',
    '#85befd',
    '#e0e0e0',
]
background = '#161719'
brights = [
    '#000000',
    '#fd5ff1',
    '#94fa36',
    '#f5ffa8',
    '#96cbfe',
    '#b9b6fc',
    '#85befd',
    '#e0e0e0',
]
cursor_bg = '#c5c8c6'
cursor_border = '#c5c8c6'
cursor_fg = '#c5c8c6'
foreground = '#c5c8c6'

[colors.indexed]

[metadata]
name = 'Atom (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
