[colors]
ansi = [
    '#110f18',
    '#ff6767',
    '#61ffca',
    '#ffca85',
    '#a277ff',
    '#a277ff',
    '#61ffca',
    '#edecee',
]
background = '#15141b'
brights = [
    '#6d6d6d',
    '#ffca85',
    '#a277ff',
    '#ffca85',
    '#a277ff',
    '#a277ff',
    '#61ffca',
    '#edecee',
]
cursor_bg = '#edecee'
cursor_border = '#edecee'
cursor_fg = '#edecee'
foreground = '#edecee'

[colors.indexed]

[metadata]
name = 'Aura (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
