[colors]
ansi = [
    '#1f2430',
    '#ff3333',
    '#bae67e',
    '#ffa759',
    '#73d0ff',
    '#d4bfff',
    '#95e6cb',
    '#cbccc6',
]
background = '#1f2430'
brights = [
    '#707a8c',
    '#ff3333',
    '#bae67e',
    '#ffa759',
    '#73d0ff',
    '#d4bfff',
    '#95e6cb',
    '#cbccc6',
]
cursor_bg = '#ffcc66'
cursor_border = '#ffcc66'
cursor_fg = '#ffcc66'
foreground = '#cbccc6'

[colors.indexed]

[metadata]
name = 'AyuMirage (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
