[colors]
ansi = [
    '#e4e5f1',
    '#d52753',
    '#23974a',
    '#df631c',
    '#275fe4',
    '#823ff1',
    '#27618d',
    '#000000',
]
background = '#f9f9f9'
brights = [
    '#5794de',
    '#ff6480',
    '#3cbc66',
    '#c5a332',
    '#0099e1',
    '#ce33c0',
    '#6d93bb',
    '#26272d',
]
cursor_bg = '#383a42'
cursor_border = '#383a42'
cursor_fg = '#383a42'
foreground = '#383a42'

[colors.indexed]

[metadata]
name = 'BlulocoZshLight (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
