[colors]
ansi = [
    '#4f4f4f',
    '#ff6c60',
    '#a8ff60',
    '#ffffb6',
    '#96cbfe',
    '#ff73fd',
    '#c6c5fe',
    '#eeeeee',
]
background = '#0000a4'
brights = [
    '#7c7c7c',
    '#ffb6b0',
    '#ceffac',
    '#ffffcc',
    '#b5dcff',
    '#ff9cfe',
    '#dfdffe',
    '#ffffff',
]
cursor_bg = '#ffff4e'
cursor_border = '#ffff4e'
cursor_fg = '#ffff4e'
foreground = '#ffff4e'

[colors.indexed]

[metadata]
name = 'Borland (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
