[colors]
ansi = [
    '#090300',
    '#883932',
    '#55a049',
    '#bfce72',
    '#40318d',
    '#8b3f96',
    '#67b6bd',
    '#ffffff',
]
background = '#40318d'
brights = [
    '#000000',
    '#883932',
    '#55a049',
    '#bfce72',
    '#40318d',
    '#8b3f96',
    '#67b6bd',
    '#f7f7f7',
]
cursor_bg = '#7869c4'
cursor_border = '#7869c4'
cursor_fg = '#7869c4'
foreground = '#7869c4'

[colors.indexed]

[metadata]
name = 'C64 (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
