[colors]
ansi = [
    '#000000',
    '#ca274d',
    '#4dca27',
    '#caa427',
    '#274dca',
    '#a427ca',
    '#27caa4',
    '#808080',
]
background = '#09111a'
brights = [
    '#808080',
    '#e98da3',
    '#a3e98d',
    '#e9d48d',
    '#8da3e9',
    '#d48de9',
    '#8de9d4',
    '#ffffff',
]
cursor_bg = '#d9e6f2'
cursor_border = '#d9e6f2'
cursor_fg = '#d9e6f2'
foreground = '#d9e6f2'

[colors.indexed]

[metadata]
name = 'Cai (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
