[colors]
ansi = [
    '#000000',
    '#c37372',
    '#72c373',
    '#c2c372',
    '#7372c3',
    '#c372c2',
    '#72c2c3',
    '#d9d9d9',
]
background = '#29262f'
brights = [
    '#323232',
    '#dbaaaa',
    '#aadbaa',
    '#dadbaa',
    '#aaaadb',
    '#dbaada',
    '#aadadb',
    '#ffffff',
]
cursor_bg = '#d9e6f2'
cursor_border = '#d9e6f2'
cursor_fg = '#d9e6f2'
foreground = '#d9e6f2'

[colors.indexed]

[metadata]
name = 'Chalkboard (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
