[colors]
ansi = [
    '#2c2c2c',
    '#cc231c',
    '#689d69',
    '#d79922',
    '#366b71',
    '#4e5165',
    '#458587',
    '#c8bb97',
]
background = '#2c2c2c'
brights = [
    '#777777',
    '#cc231c',
    '#689d69',
    '#d79922',
    '#366b71',
    '#4e5165',
    '#458587',
    '#c8bb97',
]
cursor_bg = '#dedede'
cursor_border = '#dedede'
cursor_fg = '#dedede'
foreground = '#dedede'

[colors.indexed]

[metadata]
name = 'Chameleon (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
