[colors]
ansi = [
    '#333333',
    '#ff5555',
    '#5fd38d',
    '#ff9955',
    '#3771c8',
    '#bc5fd3',
    '#5fd3bc',
    '#999999',
]
background = '#333333'
brights = [
    '#666666',
    '#ff8080',
    '#87deaa',
    '#ffb380',
    '#5f8dd3',
    '#cd87de',
    '#87decd',
    '#cccccc',
]
cursor_bg = '#cccccc'
cursor_border = '#cccccc'
cursor_fg = '#cccccc'
foreground = '#cccccc'

[colors.indexed]

[metadata]
name = 'DeHydration (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
