[colors]
ansi = [
    '#4d4d4d',
    '#ff2b2b',
    '#98fb98',
    '#f0e68c',
    '#cd853f',
    '#ffdead',
    '#ffa0a0',
    '#f5deb3',
]
background = '#333333'
brights = [
    '#555555',
    '#ff5555',
    '#55ff55',
    '#ffff55',
    '#87ceff',
    '#ff55ff',
    '#ffd700',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#ffffff'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'Desert (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
