[colors]
ansi = [
    '#000000',
    '#dc322f',
    '#56db3a',
    '#ff8400',
    '#0084d4',
    '#b729d9',
    '#ccccff',
    '#ffffff',
]
background = '#000000'
brights = [
    '#d6dbe5',
    '#dc322f',
    '#56db3a',
    '#ff8400',
    '#0084d4',
    '#b729d9',
    '#ccccff',
    '#ffffff',
]
cursor_bg = '#dc322f'
cursor_border = '#dc322f'
cursor_fg = '#dc322f'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'Dissonance (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
