[colors]
ansi = [
    '#44475a',
    '#ff5555',
    '#50fa7b',
    '#ffb86c',
    '#8be9fd',
    '#bd93f9',
    '#ff79c6',
    '#94a3a5',
]
background = '#282a36'
brights = [
    '#000000',
    '#ff5555',
    '#50fa7b',
    '#ffb86c',
    '#8be9fd',
    '#bd93f9',
    '#ff79c6',
    '#ffffff',
]
cursor_bg = '#94a3a5'
cursor_border = '#94a3a5'
cursor_fg = '#94a3a5'
foreground = '#94a3a5'

[colors.indexed]

[metadata]
name = 'Dracula (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
