[colors]
ansi = [
    '#121418',
    '#c94234',
    '#85c54c',
    '#f5ae2e',
    '#1398b9',
    '#d0633d',
    '#509552',
    '#e5c6aa',
]
background = '#292520'
brights = [
    '#675f54',
    '#ff645a',
    '#98e036',
    '#e0d561',
    '#5fdaff',
    '#ff9269',
    '#84f088',
    '#f6f7ec',
]
cursor_bg = '#e5c7a9'
cursor_border = '#e5c7a9'
cursor_fg = '#e5c7a9'
foreground = '#e5c7a9'

[colors.indexed]

[metadata]
name = 'Earthsong (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
