[colors]
ansi = [
    '#000000',
    '#cc0000',
    '#1a921c',
    '#f0e53a',
    '#0066ff',
    '#c5656b',
    '#06989a',
    '#d3d7cf',
]
background = '#2a211c'
brights = [
    '#555753',
    '#ef2929',
    '#9aff87',
    '#fffb5c',
    '#43a8ed',
    '#ff818a',
    '#34e2e2',
    '#eeeeec',
]
cursor_bg = '#b8a898'
cursor_border = '#b8a898'
cursor_fg = '#b8a898'
foreground = '#b8a898'

[colors.indexed]

[metadata]
name = 'EspressoLibre (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
