[colors]
ansi = [
    '#353535',
    '#d25252',
    '#a5c261',
    '#ffc66d',
    '#6c99bb',
    '#d197d9',
    '#bed6ff',
    '#eeeeec',
]
background = '#323232'
brights = [
    '#535353',
    '#f00c0c',
    '#c2e075',
    '#e1e48b',
    '#8ab7d9',
    '#efb5f7',
    '#dcf4ff',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#ffffff'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'Espresso (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
