[colors]
ansi = [
    '#03073c',
    '#c6004a',
    '#acf157',
    '#fecd5e',
    '#525fb8',
    '#986f82',
    '#968763',
    '#ecf0fc',
]
background = '#232537'
brights = [
    '#6c5b30',
    '#da4b8a',
    '#dbffa9',
    '#fee6a9',
    '#b2befa',
    '#fda5cd',
    '#a5bd86',
    '#f6ffec',
]
cursor_bg = '#ecf0fe'
cursor_border = '#ecf0fe'
cursor_fg = '#ecf0fe'
foreground = '#ecf0fe'

[colors.indexed]

[metadata]
name = 'Fishtank (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
