[colors]
ansi = [
    '#1f2229',
    '#d41919',
    '#5ebdab',
    '#fea44c',
    '#367bf0',
    '#bf2e5d',
    '#49aee6',
    '#e6e6e6',
]
background = '#272a34'
brights = [
    '#8c42ab',
    '#ec0101',
    '#47d4b9',
    '#ff8a18',
    '#277fff',
    '#d71655',
    '#05a1f7',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#ffffff'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'FlatRemix (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
