[colors]
ansi = [
    '#202124',
    '#ea4335',
    '#34a853',
    '#fbbc04',
    '#4285f4',
    '#a142f4',
    '#24c1e0',
    '#e8eaed',
]
background = '#202124'
brights = [
    '#5f6368',
    '#ea4335',
    '#34a853',
    '#fbbc05',
    '#4285f4',
    '#a142f4',
    '#24c1e0',
    '#ffffff',
]
cursor_bg = '#e8eaed'
cursor_border = '#e8eaed'
cursor_fg = '#e8eaed'
foreground = '#e8eaed'

[colors.indexed]

[metadata]
name = 'GoogleDark (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
