[colors]
ansi = [
    '#777777',
    '#ff0055',
    '#739100',
    '#503d15',
    '#538091',
    '#5b345e',
    '#538091',
    '#999999',
]
background = '#efefef'
brights = [
    '#999999',
    '#d65e76',
    '#9cc700',
    '#947555',
    '#9db3cd',
    '#a184a4',
    '#85b2aa',
    '#bababa',
]
cursor_bg = '#ff0054'
cursor_border = '#ff0054'
cursor_fg = '#ff0054'
foreground = '#444444'

[colors.indexed]

[metadata]
name = 'HemisuLight (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
