[colors]
ansi = [
    '#16161c',
    '#e95678',
    '#29d398',
    '#fab795',
    '#26bbd9',
    '#ee64ae',
    '#59e3e3',
    '#fadad1',
]
background = '#1c1e26'
brights = [
    '#232530',
    '#ec6a88',
    '#3fdaa4',
    '#fbc3a7',
    '#3fc6de',
    '#f075b7',
    '#6be6e6',
    '#fdf0ed',
]
cursor_bg = '#fdf0ed'
cursor_border = '#fdf0ed'
cursor_fg = '#fdf0ed'
foreground = '#fdf0ed'

[colors.indexed]

[metadata]
name = 'HorizonDark (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
