[colors]
ansi = [
    '#282a2e',
    '#a54242',
    '#8c9440',
    '#de935f',
    '#5f819d',
    '#85678f',
    '#5e8d87',
    '#969896',
]
background = '#141414'
brights = [
    '#373b41',
    '#cc6666',
    '#b5bd68',
    '#f0c674',
    '#81a2be',
    '#b294bb',
    '#8abeb7',
    '#c5c8c6',
]
cursor_bg = '#94a3a5'
cursor_border = '#94a3a5'
cursor_fg = '#94a3a5'
foreground = '#94a3a5'

[colors.indexed]

[metadata]
name = 'Hybrid (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
