[colors]
ansi = [
    '#1f1f1f',
    '#fb002a',
    '#339c24',
    '#659b25',
    '#149b45',
    '#53b82c',
    '#2cb868',
    '#e0ffef',
]
background = '#3a3d3f'
brights = [
    '#032710',
    '#a7ff3f',
    '#9fff6d',
    '#d2ff6d',
    '#72ffb5',
    '#50ff3e',
    '#22ff71',
    '#daefd0',
]
cursor_bg = '#d9efd3'
cursor_border = '#d9efd3'
cursor_fg = '#d9efd3'
foreground = '#d9efd3'

[colors.indexed]

[metadata]
name = 'ICGreenPPL (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
