[colors]
ansi = [
    '#4e4e4e',
    '#ff6c60',
    '#a8ff60',
    '#ffffb6',
    '#69cbfe',
    '#ff73fd',
    '#c6c5fe',
    '#eeeeee',
]
background = '#000000'
brights = [
    '#7c7c7c',
    '#ffb6b0',
    '#ceffac',
    '#ffffcb',
    '#b5dcfe',
    '#ff9cfe',
    '#dfdffe',
    '#ffffff',
]
cursor_bg = '#ffa560'
cursor_border = '#ffa560'
cursor_fg = '#ffa560'
foreground = '#eeeeee'

[colors.indexed]

[metadata]
name = 'IrBlack (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
