[colors]
ansi = [
    '#323f46',
    '#83615b',
    '#7f9781',
    '#a69875',
    '#53516f',
    '#856880',
    '#7d96b2',
    '#c9cdd7',
]
background = '#323f46'
brights = [
    '#3d4950',
    '#ba9088',
    '#bedbc1',
    '#f1dfb4',
    '#767495',
    '#be9cb8',
    '#bcdbff',
    '#dfe2ed',
]
cursor_bg = '#c9cdd7'
cursor_border = '#c9cdd7'
cursor_fg = '#c9cdd7'
foreground = '#c9cdd7'

[colors.indexed]

[metadata]
name = 'LunariaEclipse (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
