[colors]
ansi = [
    '#000000',
    '#cc0000',
    '#00a600',
    '#999900',
    '#0000b2',
    '#b200b2',
    '#00a6b2',
    '#cccccc',
]
background = '#fef49c'
brights = [
    '#666666',
    '#e50000',
    '#00d900',
    '#e5e500',
    '#0000ff',
    '#e500e5',
    '#00e5e5',
    '#e5e5e5',
]
cursor_bg = '#000000'
cursor_border = '#000000'
cursor_fg = '#000000'
foreground = '#000000'

[colors.indexed]

[metadata]
name = 'ManPage (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
