[colors]
ansi = [
    '#3e3838',
    '#df7484',
    '#bbd87e',
    '#edce73',
    '#dc9373',
    '#a9aae9',
    '#a4d7cc',
    '#fbf2f3',
]
background = '#3e3838'
brights = [
    '#70696a',
    '#df7484',
    '#bbd87e',
    '#edce73',
    '#dc9373',
    '#a9aae9',
    '#a4d7cc',
    '#fbf2f3',
]
cursor_bg = '#fbf2f3'
cursor_border = '#fbf2f3'
cursor_fg = '#fbf2f3'
foreground = '#fbf2f3'

[colors.indexed]

[metadata]
name = 'MonokaiProRistretto (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
