[colors]
ansi = [
    '#403500',
    '#ffd300',
    '#ffd300',
    '#ffd300',
    '#ffd300',
    '#ffd300',
    '#ffd300',
    '#ffd300',
]
background = '#2b2400'
brights = [
    '#ffd300',
    '#ffd300',
    '#ffd300',
    '#ffd300',
    '#ffd300',
    '#ffd300',
    '#ffd300',
    '#ffd300',
]
cursor_bg = '#ffd300'
cursor_border = '#ffd300'
cursor_fg = '#ffd300'
foreground = '#ffd300'

[colors.indexed]

[metadata]
name = 'mono-yellow (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
