[colors]
ansi = [
    '#034000',
    '#0bff00',
    '#0bff00',
    '#0bff00',
    '#0bff00',
    '#0bff00',
    '#0bff00',
    '#0bff00',
]
background = '#022b00'
brights = [
    '#0bff00',
    '#0bff00',
    '#0bff00',
    '#0bff00',
    '#0bff00',
    '#0bff00',
    '#0bff00',
    '#0bff00',
]
cursor_bg = '#0bff00'
cursor_border = '#0bff00'
cursor_fg = '#0bff00'
foreground = '#0bff00'

[colors.indexed]

[metadata]
name = 'mono-green (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
