[colors]
ansi = [
    '#75715e',
    '#f92672',
    '#a6e22e',
    '#f4bf75',
    '#66d9ef',
    '#ae81ff',
    '#2aa198',
    '#f9f8f5',
]
background = '#272822'
brights = [
    '#272822',
    '#f92672',
    '#a6e22e',
    '#f4bf75',
    '#66d9ef',
    '#ae81ff',
    '#2aa198',
    '#f8f8f2',
]
cursor_bg = '#f8f8f2'
cursor_border = '#f8f8f2'
cursor_fg = '#f8f8f2'
foreground = '#f8f8f2'

[colors.indexed]

[metadata]
name = 'MonokaiDark (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
