[colors]
ansi = [
    '#402500',
    '#ff9400',
    '#ff9400',
    '#ff9400',
    '#ff9400',
    '#ff9400',
    '#ff9400',
    '#ff9400',
]
background = '#2b1900'
brights = [
    '#ff9400',
    '#ff9400',
    '#ff9400',
    '#ff9400',
    '#ff9400',
    '#ff9400',
    '#ff9400',
    '#ff9400',
]
cursor_bg = '#ff9400'
cursor_border = '#ff9400'
cursor_fg = '#ff9400'
foreground = '#ff9400'

[colors.indexed]

[metadata]
name = 'mono-amber (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
