[colors]
ansi = [
    '#000000',
    '#800000',
    '#61ce3c',
    '#fbde2d',
    '#253b76',
    '#ff0080',
    '#8da6ce',
    '#f8f8f8',
]
background = '#271f19'
brights = [
    '#000000',
    '#800000',
    '#61ce3c',
    '#fbde2d',
    '#253b76',
    '#ff0080',
    '#8da6ce',
    '#f8f8f8',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#ffffff'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'Neopolitan (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
