[colors]
ansi = [
    '#23252b',
    '#b54036',
    '#5ab977',
    '#deb566',
    '#6a7c93',
    '#a4799d',
    '#3f94a8',
    '#e6e8ef',
]
background = '#1c1e22'
brights = [
    '#23252b',
    '#b54036',
    '#5ab977',
    '#deb566',
    '#6a7c93',
    '#a4799d',
    '#3f94a8',
    '#ebedf2',
]
cursor_bg = '#e6e8ef'
cursor_border = '#e6e8ef'
cursor_fg = '#e6e8ef'
foreground = '#e6e8ef'

[colors.indexed]

[metadata]
name = 'Neutron (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
