[colors]
ansi = [
    '#3b4252',
    '#bf616a',
    '#a3be8c',
    '#ebcb8b',
    '#81a1c1',
    '#b48ead',
    '#88c0d0',
    '#e5e9f0',
]
background = '#2e3440'
brights = [
    '#4c566a',
    '#bf616a',
    '#a3be8c',
    '#ebcb8b',
    '#81a1c1',
    '#b48ead',
    '#8fbcbb',
    '#eceff4',
]
cursor_bg = '#d8dee9'
cursor_border = '#d8dee9'
cursor_fg = '#d8dee9'
foreground = '#d8dee9'

[colors.indexed]

[metadata]
name = 'Nord (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
