[colors]
ansi = [
    '#003b4e',
    '#e64569',
    '#069f5f',
    '#dab752',
    '#439ecf',
    '#d961dc',
    '#00b1be',
    '#b3b3b3',
]
background = '#ebeaf2'
brights = [
    '#3e89a1',
    '#e4859a',
    '#a2cca1',
    '#e1e387',
    '#6fbbe2',
    '#e586e7',
    '#96dcda',
    '#dedede',
]
cursor_bg = '#439ecf'
cursor_border = '#439ecf'
cursor_fg = '#439ecf'
foreground = '#004f7c'

[colors.indexed]

[metadata]
name = 'NordLight (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
