[colors]
ansi = [
    '#000000',
    '#cc0000',
    '#009600',
    '#d06b00',
    '#0000cc',
    '#cc00cc',
    '#0087cc',
    '#cccccc',
]
background = '#dfdbc3'
brights = [
    '#808080',
    '#cc0000',
    '#009600',
    '#d06b00',
    '#0000cc',
    '#cc00cc',
    '#0087cc',
    '#ffffff',
]
cursor_bg = '#3b2322'
cursor_border = '#3b2322'
cursor_fg = '#3b2322'
foreground = '#3b2322'

[colors.indexed]

[metadata]
name = 'Novel (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
