[colors]
ansi = [
    '#191622',
    '#e96379',
    '#67e480',
    '#e89e64',
    '#78d1e1',
    '#988bc7',
    '#ff79c6',
    '#abb2bf',
]
background = '#191622'
brights = [
    '#000000',
    '#e96379',
    '#67e480',
    '#e89e64',
    '#78d1e1',
    '#988bc7',
    '#ff79c6',
    '#ffffff',
]
cursor_bg = '#abb2bf'
cursor_border = '#abb2bf'
cursor_fg = '#abb2bf'
foreground = '#abb2bf'

[colors.indexed]

[metadata]
name = 'Omni (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
