[colors]
ansi = [
    '#000000',
    '#da3e39',
    '#41933e',
    '#855504',
    '#315eee',
    '#930092',
    '#0e6fad',
    '#8e8f96',
]
background = '#f8f8f8'
brights = [
    '#2a2b32',
    '#da3e39',
    '#41933e',
    '#855504',
    '#315eee',
    '#930092',
    '#0e6fad',
    '#fffefe',
]
cursor_bg = '#2a2b32'
cursor_border = '#2a2b32'
cursor_fg = '#2a2b32'
foreground = '#2a2b32'

[colors.indexed]

[metadata]
name = 'OneLight (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
