[colors]
ansi = [
    '#292d3e',
    '#f07178',
    '#c3e88d',
    '#ffcb6b',
    '#82aaff',
    '#c792ea',
    '#60adec',
    '#abb2bf',
]
background = '#292d3e'
brights = [
    '#959dcb',
    '#f07178',
    '#c3e88d',
    '#ff5572',
    '#82aaff',
    '#ffcb6b',
    '#676e95',
    '#fffefe',
]
cursor_bg = '#bfc7d5'
cursor_border = '#bfc7d5'
cursor_fg = '#bfc7d5'
foreground = '#bfc7d5'

[colors.indexed]

[metadata]
name = 'palenight (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
