[colors]
ansi = [
    '#212121',
    '#c30771',
    '#10a778',
    '#a89c14',
    '#008ec4',
    '#523c79',
    '#20a5ba',
    '#d9d9d9',
]
background = '#212121'
brights = [
    '#424242',
    '#fb007a',
    '#5fd7af',
    '#f3e430',
    '#20bbfc',
    '#6855de',
    '#4fb8cc',
    '#f1f1f1',
]
cursor_bg = '#f1f1f1'
cursor_border = '#f1f1f1'
cursor_fg = '#f1f1f1'
foreground = '#f1f1f1'

[colors.indexed]

[metadata]
name = 'PencilDark (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
