[colors]
ansi = [
    '#2f2942',
    '#ff857f',
    '#48b685',
    '#e6c000',
    '#ae81ff',
    '#ef6155',
    '#c2ffdf',
    '#f8f8f2',
]
background = '#241f33'
brights = [
    '#75507b',
    '#f1568e',
    '#5adba2',
    '#d5a425',
    '#c5a3ff',
    '#ef6155',
    '#c2ffff',
    '#f8f8f0',
]
cursor_bg = '#d1cae8'
cursor_border = '#d1cae8'
cursor_fg = '#d1cae8'
foreground = '#d1cae8'

[colors.indexed]

[metadata]
name = 'Pixiefloss (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
