[colors]
ansi = [
    '#012026',
    '#b2302d',
    '#00a941',
    '#5e8baa',
    '#449a86',
    '#00599d',
    '#5d7e19',
    '#405555',
]
background = '#001015'
brights = [
    '#384451',
    '#ff4242',
    '#2aea5e',
    '#8ed4fd',
    '#61d5ba',
    '#1298ff',
    '#98d028',
    '#58fbd6',
]
cursor_bg = '#405555'
cursor_border = '#405555'
cursor_fg = '#405555'
foreground = '#405555'

[colors.indexed]

[metadata]
name = 'Shaman (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
