[colors]
ansi = [
    '#2c2423',
    '#ab2463',
    '#6ca323',
    '#ab6423',
    '#2c64a2',
    '#6c24a2',
    '#2ca363',
    '#918988',
]
background = '#2a201f'
brights = [
    '#918988',
    '#f588b9',
    '#c2ee86',
    '#f5ba86',
    '#8fbaec',
    '#c288ec',
    '#8feeb9',
    '#f5eeec',
]
cursor_bg = '#4882cd'
cursor_border = '#4882cd'
cursor_fg = '#4882cd'
foreground = '#4882cd'

[colors.indexed]

[metadata]
name = 'Shel (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
