[colors]
ansi = [
    '#000000',
    '#c75646',
    '#8eb33b',
    '#d0b03c',
    '#72b3cc',
    '#c8a0d1',
    '#218693',
    '#b0b0b0',
]
background = '#242424'
brights = [
    '#5d5d5d',
    '#e09690',
    '#cdee69',
    '#ffe377',
    '#9cd9f0',
    '#fbb1f9',
    '#77dfd8',
    '#f7f7f7',
]
cursor_bg = '#f7f7f7'
cursor_border = '#f7f7f7'
cursor_fg = '#f7f7f7'
foreground = '#f7f7f7'

[colors.indexed]

[metadata]
name = 'Smyck (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
