[colors]
ansi = [
    '#282a36',
    '#ff5c57',
    '#5af78e',
    '#f3f99d',
    '#57c7ff',
    '#ff6ac1',
    '#9aedfe',
    '#f1f1f0',
]
background = '#282a36'
brights = [
    '#686868',
    '#ff5c57',
    '#5af78e',
    '#f3f99d',
    '#57c7ff',
    '#ff6ac1',
    '#9aedfe',
    '#eff0eb',
]
cursor_bg = '#97979b'
cursor_border = '#97979b'
cursor_fg = '#97979b'
foreground = '#eff0eb'

[colors.indexed]

[metadata]
name = 'Snazzy (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
