[colors]
ansi = [
    '#000000',
    '#a2686a',
    '#9aa56a',
    '#a3906a',
    '#6b8fa3',
    '#6a71a3',
    '#6ba58f',
    '#99a3a2',
]
background = '#242626'
brights = [
    '#666c6c',
    '#dd5c60',
    '#bfdf55',
    '#deb360',
    '#62b1df',
    '#606edf',
    '#64e39c',
    '#d2e0de',
]
cursor_bg = '#99a3a2'
cursor_border = '#99a3a2'
cursor_fg = '#99a3a2'
foreground = '#99a3a2'

[colors.indexed]

[metadata]
name = 'SoftServer (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
