[colors]
ansi = [
    '#073642',
    '#dc322f',
    '#859900',
    '#cf9a6b',
    '#268bd2',
    '#d33682',
    '#2aa198',
    '#eee8d5',
]
background = '#002b36'
brights = [
    '#657b83',
    '#d87979',
    '#88cf76',
    '#657b83',
    '#2699ff',
    '#d33682',
    '#43b8c3',
    '#fdf6e3',
]
cursor_bg = '#839496'
cursor_border = '#839496'
cursor_fg = '#839496'
foreground = '#839496'

[colors.indexed]

[metadata]
name = 'SolarizedDark (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
