[colors]
ansi = [
    '#000000',
    '#ff4d83',
    '#1f8c3b',
    '#1fc95b',
    '#1dd3ee',
    '#8959a8',
    '#3e999f',
    '#ffffff',
]
background = '#0a1e24'
brights = [
    '#000000',
    '#ff0021',
    '#1fc231',
    '#d5b807',
    '#15a9fd',
    '#8959a8',
    '#3e999f',
    '#ffffff',
]
cursor_bg = '#ecf0c1'
cursor_border = '#ecf0c1'
cursor_fg = '#ecf0c1'
foreground = '#ecf0c1'

[colors.indexed]

[metadata]
name = 'Spring (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
