[colors]
ansi = [
    '#050505',
    '#e9897c',
    '#b6377d',
    '#ecebbe',
    '#a9cdeb',
    '#75507b',
    '#c9caec',
    '#f2f2f2',
]
background = '#0a1e24'
brights = [
    '#141414',
    '#f99286',
    '#c3f786',
    '#fcfbcc',
    '#b6defb',
    '#ad7fa8',
    '#d7d9fc',
    '#e2e2e2',
]
cursor_bg = '#a1a1a1'
cursor_border = '#a1a1a1'
cursor_fg = '#a1a1a1'
foreground = '#a1a1a1'

[colors.indexed]

[metadata]
name = 'Square (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
