[colors]
ansi = [
    '#666666',
    '#ff1e8e',
    '#8eff1e',
    '#fffb00',
    '#1e8eff',
    '#e500e5',
    '#00e5e5',
    '#e5e5e5',
]
background = '#272822'
brights = [
    '#666666',
    '#ff1e8e',
    '#8eff1e',
    '#fffb00',
    '#1e8eff',
    '#e500e5',
    '#00e5e5',
    '#e5e5e5',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#ffffff'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'summer-pop (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
