[colors]
ansi = [
    '#3f3f54',
    '#f60055',
    '#06c993',
    '#9700be',
    '#f69154',
    '#ec89cb',
    '#60adec',
    '#abb2bf',
]
background = '#222235'
brights = [
    '#959dcb',
    '#f60055',
    '#06c993',
    '#9700be',
    '#f69154',
    '#ec89cb',
    '#00dded',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#ffffff'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'SweetTerminal (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
