[colors]
ansi = [
    '#1d1d1d',
    '#c5152f',
    '#c9d05c',
    '#ffc24b',
    '#b3deef',
    '#d3b987',
    '#73cef4',
    '#eeeeee',
]
background = '#282828'
brights = [
    '#323232',
    '#f43753',
    '#d9e066',
    '#facc72',
    '#c0eafb',
    '#efd093',
    '#a1d6ec',
    '#ffffff',
]
cursor_bg = '#eeeeee'
cursor_border = '#eeeeee'
cursor_fg = '#eeeeee'
foreground = '#eeeeee'

[colors.indexed]

[metadata]
name = 'Tender (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
