[colors]
ansi = [
    '#0f0f14',
    '#8c4351',
    '#485e30',
    '#8f5e15',
    '#34548a',
    '#5a4a78',
    '#0f4b6e',
    '#343b58',
]
background = '#d5d6db'
brights = [
    '#9699a3',
    '#8c4351',
    '#485e30',
    '#8f5e15',
    '#34548a',
    '#5a4a78',
    '#0f4b6e',
    '#343b58',
]
cursor_bg = '#565a6e'
cursor_border = '#565a6e'
cursor_fg = '#565a6e'
foreground = '#565a6e'

[colors.indexed]

[metadata]
name = 'TokyoNightLight (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
