[colors]
ansi = [
    '#000000',
    '#cc6666',
    '#b5bd68',
    '#f0c674',
    '#81a2be',
    '#b293bb',
    '#8abeb7',
    '#fffefe',
]
background = '#1d1f21'
brights = [
    '#000000',
    '#cc6666',
    '#b5bd68',
    '#f0c574',
    '#80a1bd',
    '#b294ba',
    '#8abdb6',
    '#fffefe',
]
cursor_bg = '#c4c8c5'
cursor_border = '#c4c8c5'
cursor_fg = '#c4c8c5'
foreground = '#c5c8c6'

[colors.indexed]

[metadata]
name = 'TomorrowNight (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
