[colors]
ansi = [
    '#303030',
    '#a87139',
    '#39a871',
    '#71a839',
    '#7139a8',
    '#a83971',
    '#3971a8',
    '#8a8a8a',
]
background = '#191f1d'
brights = [
    '#494949',
    '#b0763b',
    '#3bb076',
    '#76b03b',
    '#763bb0',
    '#b03b76',
    '#3b76b0',
    '#cfcfcf',
]
cursor_bg = '#d9e6f2'
cursor_border = '#d9e6f2'
cursor_fg = '#d9e6f2'
foreground = '#d9e6f2'

[colors.indexed]

[metadata]
name = 'Vag (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
