[colors]
ansi = [
    '#6a787a',
    '#e9653b',
    '#39e9a8',
    '#e5b684',
    '#44aae6',
    '#e17599',
    '#3dd5e7',
    '#c3dde1',
]
background = '#1e1e1e'
brights = [
    '#598489',
    '#e65029',
    '#00ff9a',
    '#e89440',
    '#009afb',
    '#ff578f',
    '#5fffff',
    '#d9fbff',
]
cursor_bg = '#cccccc'
cursor_border = '#cccccc'
cursor_fg = '#cccccc'
foreground = '#cccccc'

[colors.indexed]

[metadata]
name = 'VSCodeDark+ (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
