[colors]
ansi = [
    '#393b44',
    '#c94f6d',
    '#81b29a',
    '#dbc074',
    '#719cd6',
    '#9d79d6',
    '#63cdcf',
    '#dfdfe0',
]
background = '#192330'
brights = [
    '#575860',
    '#d16983',
    '#8ebaa4',
    '#e0c989',
    '#86abdc',
    '#baa1e2',
    '#7ad4d6',
    '#e4e4e5',
]
cursor_bg = '#cdcecf'
cursor_border = '#cdcecf'
cursor_fg = '#cdcecf'
foreground = '#cdcecf'

[colors.indexed]

[metadata]
name = '_bash (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
