[colors]
ansi = [
    '#3f3f3f',
    '#ff0883',
    '#83ff08',
    '#ff8308',
    '#0883ff',
    '#8308ff',
    '#08ff83',
    '#bebebe',
]
background = '#1f1305'
brights = [
    '#474747',
    '#ff1e8e',
    '#8eff1e',
    '#ff8e1e',
    '#1e8eff',
    '#8e1eff',
    '#1eff8e',
    '#c4c4c4',
]
cursor_bg = '#b4e1fd'
cursor_border = '#b4e1fd'
cursor_fg = '#b4e1fd'
foreground = '#b4e1fd'

[colors.indexed]

[metadata]
name = 'Aco (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
