[colors]
ansi = [
    '#151515',
    '#a53c23',
    '#7b9246',
    '#d3a04d',
    '#6c99bb',
    '#9f4e85',
    '#7dd6cf',
    '#d0d0d0',
]
background = '#222222'
brights = [
    '#505050',
    '#a53c23',
    '#7b9246',
    '#d3a04d',
    '#547c99',
    '#9f4e85',
    '#7dd6cf',
    '#f5f5f5',
]
cursor_bg = '#d0d0d0'
cursor_border = '#d0d0d0'
cursor_fg = '#d0d0d0'
foreground = '#d0d0d0'

[colors.indexed]

[metadata]
name = 'Afterglow (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
