[colors]
ansi = [
    '#112616',
    '#7f2b27',
    '#2f7e25',
    '#717f24',
    '#2f6a7f',
    '#47587f',
    '#327f77',
    '#647d75',
]
background = '#0f1610'
brights = [
    '#3c4812',
    '#e08009',
    '#18e000',
    '#bde000',
    '#00aae0',
    '#0058e0',
    '#00e0c4',
    '#73fa91',
]
cursor_bg = '#637d75'
cursor_border = '#637d75'
cursor_fg = '#637d75'
foreground = '#637d75'

[colors.indexed]

[metadata]
name = 'AlienBlood (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
