[colors]
ansi = [
    '#232323',
    '#ff000f',
    '#8ce10b',
    '#ffb900',
    '#008df8',
    '#6d43a6',
    '#00d8eb',
    '#ffffff',
]
background = '#0e1019'
brights = [
    '#444444',
    '#ff2740',
    '#abe15b',
    '#ffd242',
    '#0092ff',
    '#9a5feb',
    '#67fff0',
    '#ffffff',
]
cursor_bg = '#fffaf4'
cursor_border = '#fffaf4'
cursor_fg = '#fffaf4'
foreground = '#fffaf4'

[colors.indexed]

[metadata]
name = 'Argonaut (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
