[colors]
ansi = [
    '#3d352a',
    '#cd5c5c',
    '#86af80',
    '#e8ae5b',
    '#6495ed',
    '#deb887',
    '#b0c4de',
    '#bbaa99',
]
background = '#1c1c1c'
brights = [
    '#554444',
    '#cc5533',
    '#88aa22',
    '#ffa75d',
    '#87ceeb',
    '#996600',
    '#b0c4de',
    '#ddccbb',
]
cursor_bg = '#ddeedd'
cursor_border = '#ddeedd'
cursor_fg = '#ddeedd'
foreground = '#ddeedd'

[colors.indexed]

[metadata]
name = 'Arthur (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
