[colors]
ansi = [
    '#0a0e14',
    '#ff3333',
    '#c2d94c',
    '#ff8f40',
    '#59c2ff',
    '#ffee99',
    '#95e6cb',
    '#b3b1ad',
]
background = '#0a0e14'
brights = [
    '#4d5566',
    '#ff3333',
    '#c2d94c',
    '#ff8f40',
    '#59c2ff',
    '#ffee99',
    '#95e6cb',
    '#b3b1ad',
]
cursor_bg = '#e6b450'
cursor_border = '#e6b450'
cursor_fg = '#e6b450'
foreground = '#b3b1ad'

[colors.indexed]

[metadata]
name = 'AyuDark (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
