[colors]
ansi = [
    '#575f66',
    '#f51818',
    '#86b300',
    '#f2ae49',
    '#399ee6',
    '#a37acc',
    '#4cbf99',
    '#fafafa',
]
background = '#fafafa'
brights = [
    '#8a9199',
    '#f51818',
    '#86b300',
    '#f2ae49',
    '#399ee6',
    '#a37acc',
    '#4cbf99',
    '#fafafa',
]
cursor_bg = '#ff9940'
cursor_border = '#ff9940'
cursor_fg = '#ff9940'
foreground = '#575f66'

[colors.indexed]

[metadata]
name = 'AyuLight (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
