[colors]
ansi = [
    '#000000',
    '#ac6d74',
    '#74ac6d',
    '#aca46d',
    '#6d74ac',
    '#a46dac',
    '#6daca4',
    '#e6e6e6',
]
background = '#09111a'
brights = [
    '#262626',
    '#d6b8bc',
    '#bcd6b8',
    '#d6d3b8',
    '#b8bcd6',
    '#d3b8d6',
    '#b8d6d3',
    '#ffffff',
]
cursor_bg = '#d9e6f2'
cursor_border = '#d9e6f2'
cursor_fg = '#d9e6f2'
foreground = '#d9e6f2'

[colors.indexed]

[metadata]
name = 'Azu (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
