[colors]
ansi = [
    '#2c2423',
    '#f557a0',
    '#a9ee55',
    '#f5a255',
    '#5ea2ec',
    '#a957ec',
    '#5eeea0',
    '#918988',
]
background = '#012849'
brights = [
    '#918988',
    '#f579b2',
    '#bbee78',
    '#f5b378',
    '#81b3ec',
    '#bb79ec',
    '#81eeb2',
    '#f5eeec',
]
cursor_bg = '#a9bed8'
cursor_border = '#a9bed8'
cursor_fg = '#a9bed8'
foreground = '#a9bed8'

[colors.indexed]

[metadata]
name = 'Bim (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
