[colors]
ansi = [
    '#573d26',
    '#be2d26',
    '#6ba18a',
    '#e99d2a',
    '#5a86ad',
    '#ac80a6',
    '#74a6ad',
    '#e0dbb7',
]
background = '#2a1f1d'
brights = [
    '#9b6c4a',
    '#e84627',
    '#95d8ba',
    '#d0d150',
    '#b8d3ed',
    '#d19ecb',
    '#93cfd7',
    '#fff9d5',
]
cursor_bg = '#e0dbb7'
cursor_border = '#e0dbb7'
cursor_fg = '#e0dbb7'
foreground = '#e0dbb7'

[colors.indexed]

[metadata]
name = 'BirdsOfParadise (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
