[colors]
ansi = [
    '#000000',
    '#da4939',
    '#519f50',
    '#ffd24a',
    '#6d9cbe',
    '#d0d0ff',
    '#6e9cbe',
    '#ffffff',
]
background = '#2b2b2b'
brights = [
    '#323232',
    '#ff7b6b',
    '#83d182',
    '#ffff7c',
    '#9fcef0',
    '#ffffff',
    '#a0cef0',
    '#ffffff',
]
cursor_bg = '#e6e1dc'
cursor_border = '#e6e1dc'
cursor_fg = '#e6e1dc'
foreground = '#e6e1dc'

[colors.indexed]

[metadata]
name = 'Broadcast (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
