[colors]
ansi = [
    '#646464',
    '#f58e8e',
    '#a9d3ab',
    '#fed37e',
    '#7aabd4',
    '#d6add5',
    '#79d4d5',
    '#d4d4d4',
]
background = '#2d2d2d'
brights = [
    '#646464',
    '#f58e8e',
    '#a9d3ab',
    '#fed37e',
    '#7aabd4',
    '#d6add5',
    '#79d4d5',
    '#d4d4d4',
]
cursor_bg = '#d4d4d4'
cursor_border = '#d4d4d4'
cursor_fg = '#d4d4d4'
foreground = '#d4d4d4'

[colors.indexed]

[metadata]
name = 'Chalk (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
