[colors]
ansi = [
    '#181818',
    '#810009',
    '#48513b',
    '#cc8b3f',
    '#576d8c',
    '#724d7c',
    '#5c4f4b',
    '#aea47f',
]
background = '#191c27'
brights = [
    '#555555',
    '#ac3835',
    '#a6a75d',
    '#dcdf7c',
    '#3097c6',
    '#d33061',
    '#f3dbb2',
    '#f4f4f4',
]
cursor_bg = '#aea47a'
cursor_border = '#aea47a'
cursor_fg = '#aea47a'
foreground = '#aea47a'

[colors.indexed]

[metadata]
name = 'Ciapre (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
