[colors]
ansi = [
    '#000000',
    '#f8282a',
    '#328a5d',
    '#fa701d',
    '#135cd0',
    '#9f00bd',
    '#33c3c1',
    '#b3b3b3',
]
background = '#ffffff'
brights = [
    '#555753',
    '#fb0416',
    '#2cc631',
    '#fdd727',
    '#1670ff',
    '#e900b0',
    '#3ad5ce',
    '#eeeeec',
]
cursor_bg = '#262626'
cursor_border = '#262626'
cursor_fg = '#262626'
foreground = '#262626'

[colors.indexed]

[metadata]
name = 'CLRS (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
