[colors]
ansi = [
    '#000000',
    '#d70000',
    '#5faf00',
    '#5faf00',
    '#005f87',
    '#d70000',
    '#5f5f5f',
    '#e4e4e4',
]
background = '#ffffff'
brights = [
    '#5f5f5f',
    '#d70000',
    '#5f5f5f',
    '#ffff00',
    '#0087af',
    '#0087af',
    '#0087af',
    '#ffffff',
]
cursor_bg = '#005f87'
cursor_border = '#005f87'
cursor_fg = '#005f87'
foreground = '#005f87'

[colors.indexed]

[metadata]
name = 'Colorcli (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
