[colors]
ansi = [
    '#2b1b1d',
    '#91002b',
    '#579524',
    '#ab311b',
    '#8c87b0',
    '#692f50',
    '#e8a866',
    '#68525a',
]
background = '#150707'
brights = [
    '#3d2b2e',
    '#c5255d',
    '#8dff57',
    '#c8381d',
    '#cfc9ff',
    '#fc6cba',
    '#ffceaf',
    '#b0949d',
]
cursor_bg = '#68525a'
cursor_border = '#68525a'
cursor_fg = '#68525a'
foreground = '#68525a'

[colors.indexed]

[metadata]
name = 'CrayonPonyFish (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
