[colors]
ansi = [
    '#000000',
    '#e8341c',
    '#68c256',
    '#f2d42c',
    '#1c98e8',
    '#8e69c9',
    '#1c98e8',
    '#bababa',
]
background = '#222324'
brights = [
    '#000000',
    '#e05a4f',
    '#77b869',
    '#efd64b',
    '#387cd3',
    '#957bbe',
    '#3d97e2',
    '#bababa',
]
cursor_bg = '#bababa'
cursor_border = '#bababa'
cursor_fg = '#bababa'
foreground = '#bababa'

[colors.indexed]

[metadata]
name = 'Darkside (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
