[colors]
ansi = [
    '#000000',
    '#ff5555',
    '#55ff55',
    '#ffff55',
    '#5555ff',
    '#ff55ff',
    '#55ffff',
    '#bbbbbb',
]
background = '#000000'
brights = [
    '#555555',
    '#ff5555',
    '#55ff55',
    '#ffff55',
    '#5555ff',
    '#ff55ff',
    '#55ffff',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#ffffff'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'DarkPastel (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
