[colors]
ansi = [
    '#3a3d43',
    '#be3f48',
    '#879a3b',
    '#c5a635',
    '#4f76a1',
    '#855c8d',
    '#578fa4',
    '#b9bcba',
]
background = '#1f1f1f'
brights = [
    '#888987',
    '#fb001f',
    '#0f722f',
    '#c47033',
    '#186de3',
    '#fb0067',
    '#2e706d',
    '#fdffb9',
]
cursor_bg = '#b9bcba'
cursor_border = '#b9bcba'
cursor_fg = '#b9bcba'
foreground = '#b9bcba'

[colors.indexed]

[metadata]
name = 'DimmedMonokai (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
