[colors]
ansi = [
    '#42395d',
    '#a8757b',
    '#ff857f',
    '#e6c000',
    '#ae81ff',
    '#716799',
    '#c2ffdf',
    '#f8f8f2',
]
background = '#5a5475'
brights = [
    '#75507b',
    '#ffb8d1',
    '#f1568e',
    '#d5a425',
    '#c5a3ff',
    '#8077a8',
    '#c2ffff',
    '#f8f8f0',
]
cursor_bg = '#ffb8d1'
cursor_border = '#ffb8d1'
cursor_fg = '#ffb8d1'
foreground = '#c2ffdf'

[colors.indexed]

[metadata]
name = 'FairyFloss (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
