[colors]
ansi = [
    '#1d1d19',
    '#f18339',
    '#9fd364',
    '#f4ef6d',
    '#5096be',
    '#695abc',
    '#d63865',
    '#ffffff',
]
background = '#1d1f21'
brights = [
    '#1d1d19',
    '#d22a24',
    '#a7d42c',
    '#ff8949',
    '#61b9d0',
    '#695abc',
    '#d63865',
    '#ffffff',
]
cursor_bg = '#b8dbef'
cursor_border = '#b8dbef'
cursor_fg = '#b8dbef'
foreground = '#b8dbef'

[colors.indexed]

[metadata]
name = 'Flatland (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
