[colors]
ansi = [
    '#2c3e50',
    '#c0392b',
    '#27ae60',
    '#f39c12',
    '#2980b9',
    '#8e44ad',
    '#16a085',
    '#bdc3c7',
]
background = '#1f2d3a'
brights = [
    '#34495e',
    '#e74c3c',
    '#2ecc71',
    '#f1c40f',
    '#3498db',
    '#9b59b6',
    '#2aa198',
    '#ecf0f1',
]
cursor_bg = '#1abc9c'
cursor_border = '#1abc9c'
cursor_fg = '#1abc9c'
foreground = '#1abc9c'

[colors.indexed]

[metadata]
name = 'Flat (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
