[colors]
ansi = [
    '#000000',
    '#f9555f',
    '#21b089',
    '#fef02a',
    '#589df6',
    '#944d95',
    '#1f9ee7',
    '#bbbbbb',
]
background = '#1d2837'
brights = [
    '#555555',
    '#fa8c8f',
    '#35bb9a',
    '#ffff55',
    '#589df6',
    '#e75699',
    '#3979bc',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#ffffff'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'FrontendGalaxy (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
