[colors]
ansi = [
    '#242526',
    '#f8511b',
    '#565747',
    '#fa771d',
    '#2c70b7',
    '#f02e4f',
    '#3ca1a6',
    '#adadad',
]
background = '#1b1c1d'
brights = [
    '#5fac6d',
    '#f74319',
    '#74ec4c',
    '#fdc325',
    '#3393ca',
    '#e75e4f',
    '#4fbce6',
    '#8c735b',
]
cursor_bg = '#adadad'
cursor_border = '#adadad'
cursor_fg = '#adadad'
foreground = '#adadad'

[colors.indexed]

[metadata]
name = 'FrontendDelight (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
