[colors]
ansi = [
    '#000009',
    '#bb4f6c',
    '#72ccae',
    '#c65e3d',
    '#58b6ca',
    '#6488c4',
    '#8d84c6',
    '#858893',
]
background = '#0d101b'
brights = [
    '#1f222d',
    '#ee829f',
    '#a5ffe1',
    '#f99170',
    '#8be9fd',
    '#97bbf7',
    '#c0b7f9',
    '#ffffff',
]
cursor_bg = '#ebeef9'
cursor_border = '#ebeef9'
cursor_fg = '#ebeef9'
foreground = '#ebeef9'

[colors.indexed]

[metadata]
name = 'gooey (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
