[colors]
ansi = [
    '#0a0f14',
    '#c33027',
    '#26a98b',
    '#edb54b',
    '#195465',
    '#4e5165',
    '#33859d',
    '#98d1ce',
]
background = '#0a0f14'
brights = [
    '#10151b',
    '#d26939',
    '#081f2d',
    '#245361',
    '#093748',
    '#888ba5',
    '#599caa',
    '#d3ebe9',
]
cursor_bg = '#98d1ce'
cursor_border = '#98d1ce'
cursor_fg = '#98d1ce'
foreground = '#98d1ce'

[colors.indexed]

[metadata]
name = 'gotham (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
