[colors]
ansi = [
    '#000000',
    '#bb0000',
    '#00bb00',
    '#e7b000',
    '#0000a3',
    '#950062',
    '#00bbbb',
    '#bbbbbb',
]
background = '#13773d'
brights = [
    '#555555',
    '#bb0000',
    '#00bb00',
    '#e7b000',
    '#0000bb',
    '#ff55ff',
    '#55ffff',
    '#ffffff',
]
cursor_bg = '#fff0a5'
cursor_border = '#fff0a5'
cursor_fg = '#fff0a5'
foreground = '#fff0a5'

[colors.indexed]

[metadata]
name = 'Grass (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
