[colors]
ansi = [
    '#1b1d1e',
    '#f92672',
    '#a6e22e',
    '#fd971f',
    '#66d9ef',
    '#9e6ffe',
    '#5e7175',
    '#ccccc6',
]
background = '#121212'
brights = [
    '#505354',
    '#ff669d',
    '#beed5f',
    '#e6db74',
    '#66d9ef',
    '#9e6ffe',
    '#a3babf',
    '#f8f8f2',
]
cursor_bg = '#a0a0a0'
cursor_border = '#a0a0a0'
cursor_fg = '#a0a0a0'
foreground = '#a0a0a0'

[colors.indexed]

[metadata]
name = 'Hardcore (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
