[colors]
ansi = [
    '#010101',
    '#f8b63f',
    '#7fb5e1',
    '#d6da25',
    '#489e48',
    '#b296c6',
    '#f5bfd7',
    '#a8a49d',
]
background = '#010101'
brights = [
    '#726e6a',
    '#f8b63f',
    '#7fb5e1',
    '#d6da25',
    '#489e48',
    '#b296c6',
    '#f5bfd7',
    '#fefbea',
]
cursor_bg = '#a8a49d'
cursor_border = '#a8a49d'
cursor_fg = '#a8a49d'
foreground = '#a8a49d'

[colors.indexed]

[metadata]
name = 'Harper (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
