[colors]
ansi = [
    '#444444',
    '#ff0054',
    '#b1d630',
    '#9d895e',
    '#67bee3',
    '#b576bc',
    '#569a9f',
    '#ededed',
]
background = '#000000'
brights = [
    '#777777',
    '#d65e75',
    '#baffaa',
    '#ece1c8',
    '#9fd3e5',
    '#deb3df',
    '#b6e0e5',
    '#ffffff',
]
cursor_bg = '#baffaa'
cursor_border = '#baffaa'
cursor_fg = '#baffaa'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'HemisuDark (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
