[colors]
ansi = [
    '#000000',
    '#d00e18',
    '#138034',
    '#ffcb3e',
    '#006bb3',
    '#6b2775',
    '#384564',
    '#ededed',
]
background = '#222225'
brights = [
    '#5d504a',
    '#f07e18',
    '#b1d130',
    '#fff120',
    '#4fc2fd',
    '#de0071',
    '#5d504a',
    '#ffffff',
]
cursor_bg = '#ededed'
cursor_border = '#ededed'
cursor_fg = '#ededed'
foreground = '#ededed'

[colors.indexed]

[metadata]
name = 'Highway (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
