[colors]
ansi = [
    '#000000',
    '#b6214a',
    '#00a600',
    '#bfbf00',
    '#246eb2',
    '#b200b2',
    '#00a6b2',
    '#bfbfbf',
]
background = '#100b05'
brights = [
    '#666666',
    '#e50000',
    '#86a93e',
    '#e5e500',
    '#0000ff',
    '#e500e5',
    '#00e5e5',
    '#e5e5e5',
]
cursor_bg = '#84c138'
cursor_border = '#84c138'
cursor_fg = '#84c138'
foreground = '#84c138'

[colors.indexed]

[metadata]
name = 'HipsterGreen (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
