[colors]
ansi = [
    '#16161c',
    '#da103f',
    '#1eb980',
    '#f6661e',
    '#26bbd9',
    '#ee64ae',
    '#1d8991',
    '#fadad1',
]
background = '#fdf0ed'
brights = [
    '#1a1c23',
    '#f43e5c',
    '#07da8c',
    '#f77d26',
    '#3fc6de',
    '#f075b7',
    '#1eaeae',
    '#fdf0ed',
]
cursor_bg = '#1c1e26'
cursor_border = '#1c1e26'
cursor_fg = '#1c1e26'
foreground = '#1c1e26'

[colors.indexed]

[metadata]
name = 'HorizonBright (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
