[colors]
ansi = [
    '#575757',
    '#ff1b00',
    '#a5e055',
    '#fbe74a',
    '#496487',
    '#fd5ff1',
    '#86e9fe',
    '#cbcccb',
]
background = '#000000'
brights = [
    '#262626',
    '#d51d00',
    '#a5df55',
    '#fbe84a',
    '#89beff',
    '#c001c1',
    '#86eafe',
    '#dbdbdb',
]
cursor_bg = '#dbdbdb'
cursor_border = '#dbdbdb'
cursor_fg = '#dbdbdb'
foreground = '#dbdbdb'

[colors.indexed]

[metadata]
name = 'Hurtado (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
