[colors]
ansi = [
    '#000000',
    '#ff0000',
    '#00ff00',
    '#ffff00',
    '#00bfff',
    '#ffc0cb',
    '#40e0d0',
    '#bebebe',
]
background = '#000000'
brights = [
    '#414141',
    '#ffa500',
    '#98fb98',
    '#ffff00',
    '#0000cd',
    '#a020f0',
    '#aeeeee',
    '#ffffff',
]
cursor_bg = '#fdfdfd'
cursor_border = '#fdfdfd'
cursor_fg = '#fdfdfd'
foreground = '#fdfdfd'

[colors.indexed]

[metadata]
name = 'IBM3270(HighContrast) (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
