[colors]
ansi = [
    '#222222',
    '#f01818',
    '#24d830',
    '#f0d824',
    '#7890f0',
    '#f078d8',
    '#54e4e4',
    '#a5a5a5',
]
background = '#000000'
brights = [
    '#888888',
    '#ef8383',
    '#7ed684',
    '#efe28b',
    '#b3bfef',
    '#efb3e3',
    '#9ce2e2',
    '#ffffff',
]
cursor_bg = '#fdfdfd'
cursor_border = '#fdfdfd'
cursor_fg = '#fdfdfd'
foreground = '#fdfdfd'

[colors.indexed]

[metadata]
name = 'ibm3270 (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
