[colors]
ansi = [
    '#000000',
    '#c13900',
    '#a4a900',
    '#caaf00',
    '#bd6d00',
    '#fc5e00',
    '#f79500',
    '#ffc88a',
]
background = '#262626'
brights = [
    '#6a4f2a',
    '#ff8c68',
    '#f6ff40',
    '#ffe36e',
    '#ffbe55',
    '#fc874f',
    '#c69752',
    '#fafaff',
]
cursor_bg = '#ffcb83'
cursor_border = '#ffcb83'
cursor_fg = '#ffcb83'
foreground = '#ffcb83'

[colors.indexed]

[metadata]
name = 'ICOrangePPL (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
