[colors]
ansi = [
    '#000000',
    '#dd006f',
    '#6fdd00',
    '#dd6f00',
    '#006fdd',
    '#6f00dd',
    '#00dd6f',
    '#f2f2f2',
]
background = '#758480'
brights = [
    '#7d7d7d',
    '#ff74b9',
    '#b9ff74',
    '#ffb974',
    '#74b9ff',
    '#b974ff',
    '#74ffb9',
    '#ffffff',
]
cursor_bg = '#23476a'
cursor_border = '#23476a'
cursor_fg = '#23476a'
foreground = '#23476a'

[colors.indexed]

[metadata]
name = 'Jup (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
