[colors]
ansi = [
    '#4d4d4d',
    '#c70031',
    '#29cf13',
    '#d8e30e',
    '#3449d1',
    '#8400ff',
    '#0798ab',
    '#e2d1e3',
]
background = '#0e100a'
brights = [
    '#5a5a5a',
    '#f01578',
    '#6ce05c',
    '#f3f79e',
    '#97a4f7',
    '#c495f0',
    '#68f2e0',
    '#ffffff',
]
cursor_bg = '#f7f7f7'
cursor_border = '#f7f7f7'
cursor_fg = '#f7f7f7'
foreground = '#f7f7f7'

[colors.indexed]

[metadata]
name = 'Kibble (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
