[colors]
ansi = [
    '#2e8744',
    '#d84e4c',
    '#95da5a',
    '#d6e264',
    '#4b9ed7',
    '#945fc5',
    '#d89b25',
    '#d8e2d7',
]
background = '#0d4a08'
brights = [
    '#34934f',
    '#ff4f59',
    '#aff56a',
    '#fcff75',
    '#57aeff',
    '#ae63e9',
    '#ffaa2b',
    '#fffefe',
]
cursor_bg = '#d8e2d7'
cursor_border = '#d8e2d7'
cursor_fg = '#d8e2d7'
foreground = '#d8e2d7'

[colors.indexed]

[metadata]
name = 'kokuban (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
