[colors]
ansi = [
    '#39243a',
    '#eb64b9',
    '#afd686',
    '#feae87',
    '#40b4c4',
    '#b381c5',
    '#215969',
    '#91889b',
]
background = '#1f1926'
brights = [
    '#716485',
    '#fc2377',
    '#50fa7b',
    '#ffe261',
    '#74dfc4',
    '#6d75e0',
    '#b4dce7',
    '#ffffff',
]
cursor_bg = '#c7c7c7'
cursor_border = '#c7c7c7'
cursor_fg = '#c7c7c7'
foreground = '#e0e0e0'

[colors.indexed]

[metadata]
name = 'laserwave (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
