[colors]
ansi = [
    '#2b2b2b',
    '#d45a60',
    '#afba67',
    '#e5d289',
    '#a0bad6',
    '#c092d6',
    '#91bfb7',
    '#3c3d3d',
]
background = '#222222'
brights = [
    '#454747',
    '#d3232f',
    '#aabb39',
    '#e5be39',
    '#6699d6',
    '#ab53d6',
    '#5fc0ae',
    '#c1c2c2',
]
cursor_bg = '#959595'
cursor_border = '#959595'
cursor_fg = '#959595'
foreground = '#959595'

[colors.indexed]

[metadata]
name = 'LaterThisEvening (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
