[colors]
ansi = [
    '#230046',
    '#7d1625',
    '#337e6f',
    '#7f6f49',
    '#4f4a7f',
    '#5a3f7f',
    '#58777f',
    '#736e7d',
]
background = '#050014'
brights = [
    '#372d46',
    '#e05167',
    '#52e0c4',
    '#e0c386',
    '#8e87e0',
    '#a776e0',
    '#9ad4e0',
    '#8c91fa',
]
cursor_bg = '#736e7d'
cursor_border = '#736e7d'
cursor_fg = '#736e7d'
foreground = '#736e7d'

[colors.indexed]

[metadata]
name = 'Lavandula (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
