[colors]
ansi = [
    '#000000',
    '#ff3030',
    '#559a70',
    '#ccac00',
    '#0099cc',
    '#cc69c8',
    '#7ac4cc',
    '#bccccc',
]
background = '#303030'
brights = [
    '#000000',
    '#ff3030',
    '#559a70',
    '#ccac00',
    '#0099cc',
    '#cc69c8',
    '#7ac4cc',
    '#bccccc',
]
cursor_bg = '#afc2c2'
cursor_border = '#afc2c2'
cursor_fg = '#afc2c2'
foreground = '#afc2c2'

[colors.indexed]

[metadata]
name = 'LiquidCarbon (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
