[colors]
ansi = [
    '#36464e',
    '#846560',
    '#809984',
    '#a79a79',
    '#555673',
    '#866c83',
    '#7e98b4',
    '#caced8',
]
background = '#36464e'
brights = [
    '#404f56',
    '#bb928b',
    '#bfdcc2',
    '#f1dfb6',
    '#777798',
    '#bf9db9',
    '#bddcff',
    '#dfe2ed',
]
cursor_bg = '#caced8'
cursor_border = '#caced8'
cursor_fg = '#caced8'
foreground = '#caced8'

[colors.indexed]

[metadata]
name = 'LunariaDark (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
