[colors]
ansi = [
    '#3e3c3d',
    '#783c1f',
    '#497d46',
    '#8f750b',
    '#3f3566',
    '#793f62',
    '#3778a9',
    '#d5cfcc',
]
background = '#ebe4e1'
brights = [
    '#484646',
    '#b06240',
    '#7bc175',
    '#dcb735',
    '#5c4f89',
    '#b56895',
    '#64baff',
    '#ebe4e1',
]
cursor_bg = '#484646'
cursor_border = '#484646'
cursor_fg = '#484646'
foreground = '#484646'

[colors.indexed]

[metadata]
name = 'LunariaLight (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
