[colors]
ansi = [
    '#232423',
    '#ba2922',
    '#7e807e',
    '#4c4f4d',
    '#16a085',
    '#43746a',
    '#00cccc',
    '#e0e0e0',
]
background = '#31363b'
brights = [
    '#282928',
    '#cc372c',
    '#8d8f8d',
    '#4e524f',
    '#13bf9d',
    '#487d72',
    '#00d1d1',
    '#e8e8e8',
]
cursor_bg = '#bdc3c7'
cursor_border = '#bdc3c7'
cursor_fg = '#bdc3c7'
foreground = '#bdc3c7'

[colors.indexed]

[metadata]
name = 'Maia (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
