[colors]
ansi = [
    '#073641',
    '#eb606b',
    '#c3e88d',
    '#f7eb95',
    '#80cbc3',
    '#ff2490',
    '#aeddff',
    '#ffffff',
]
background = '#1e282c'
brights = [
    '#002b36',
    '#eb606b',
    '#c3e88d',
    '#f7eb95',
    '#7dc6bf',
    '#6c71c3',
    '#34434d',
    '#ffffff',
]
cursor_bg = '#657b83'
cursor_border = '#657b83'
cursor_fg = '#657b83'
foreground = '#c3c7d1'

[colors.indexed]

[metadata]
name = 'Material (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
