[colors]
ansi = [
    '#000000',
    '#b64c00',
    '#7c8b16',
    '#d3bd26',
    '#616bb0',
    '#8c5a90',
    '#916c25',
    '#cac29a',
]
background = '#1d1908'
brights = [
    '#5e5219',
    '#ff9149',
    '#b2ca3b',
    '#ffe54a',
    '#acb8ff',
    '#ffa0ff',
    '#ffbc51',
    '#fed698',
]
cursor_bg = '#cac296'
cursor_border = '#cac296'
cursor_fg = '#cac296'
foreground = '#cac296'

[colors.indexed]

[metadata]
name = 'Medallion (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
