[colors]
ansi = [
    '#351b0e',
    '#9b291c',
    '#636232',
    '#c36e28',
    '#515c5d',
    '#9b1d29',
    '#588056',
    '#f7d75c',
]
background = '#120b0d'
brights = [
    '#874228',
    '#ff4331',
    '#b4b264',
    '#ff9566',
    '#9eb2b4',
    '#ff5b6a',
    '#8acd8f',
    '#ffe598',
]
cursor_bg = '#f7d66a'
cursor_border = '#f7d66a'
cursor_fg = '#f7d66a'
foreground = '#f7d66a'

[colors.indexed]

[metadata]
name = 'MonaLisa (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
