[colors]
ansi = [
    '#363537',
    '#ff6188',
    '#a9dc76',
    '#ffd866',
    '#fc9867',
    '#ab9df2',
    '#78dce8',
    '#fdf9f3',
]
background = '#363537'
brights = [
    '#908e8f',
    '#ff6188',
    '#a9dc76',
    '#ffd866',
    '#fc9867',
    '#ab9df2',
    '#78dce8',
    '#fdf9f3',
]
cursor_bg = '#fdf9f3'
cursor_border = '#fdf9f3'
cursor_fg = '#fdf9f3'
foreground = '#fdf9f3'

[colors.indexed]

[metadata]
name = 'MonokaiPro (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
