[colors]
ansi = [
    '#401200',
    '#ff3600',
    '#ff3600',
    '#ff3600',
    '#ff3600',
    '#ff3600',
    '#ff3600',
    '#ff3600',
]
background = '#2b0c00'
brights = [
    '#ff3600',
    '#ff3600',
    '#ff3600',
    '#ff3600',
    '#ff3600',
    '#ff3600',
    '#ff3600',
    '#ff3600',
]
cursor_bg = '#ff3600'
cursor_border = '#ff3600'
cursor_fg = '#ff3600'
foreground = '#ff3600'

[colors.indexed]

[metadata]
name = 'mono-red (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
