[colors]
ansi = [
    '#003340',
    '#00ccff',
    '#00ccff',
    '#00ccff',
    '#00ccff',
    '#00ccff',
    '#00ccff',
    '#00ccff',
]
background = '#00222b'
brights = [
    '#00ccff',
    '#00ccff',
    '#00ccff',
    '#00ccff',
    '#00ccff',
    '#00ccff',
    '#00ccff',
    '#00ccff',
]
cursor_bg = '#00ccff'
cursor_border = '#00ccff'
cursor_fg = '#00ccff'
foreground = '#00ccff'

[colors.indexed]

[metadata]
name = 'mono-cyan (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
