[colors]
ansi = [
    '#3b3b3b',
    '#fafafa',
    '#fafafa',
    '#fafafa',
    '#fafafa',
    '#fafafa',
    '#fafafa',
    '#fafafa',
]
background = '#262626'
brights = [
    '#fafafa',
    '#fafafa',
    '#fafafa',
    '#fafafa',
    '#fafafa',
    '#fafafa',
    '#fafafa',
    '#fafafa',
]
cursor_bg = '#fafafa'
cursor_border = '#fafafa'
cursor_fg = '#fafafa'
foreground = '#fafafa'

[colors.indexed]

[metadata]
name = 'mono-white (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
