[colors]
ansi = [
    '#1a1a1a',
    '#f4005f',
    '#98e024',
    '#fa8419',
    '#9d65ff',
    '#f4005f',
    '#58d1eb',
    '#c4c5b5',
]
background = '#1a1a1a'
brights = [
    '#625e4c',
    '#f4005f',
    '#98e024',
    '#e0d561',
    '#9d65ff',
    '#f4005f',
    '#58d1eb',
    '#f6f6ef',
]
cursor_bg = '#c4c5b5'
cursor_border = '#c4c5b5'
cursor_fg = '#c4c5b5'
foreground = '#c4c5b5'

[colors.indexed]

[metadata]
name = 'MonokaiSoda (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
