[colors]
ansi = [
    '#383838',
    '#a95551',
    '#666666',
    '#a98051',
    '#657d3e',
    '#767676',
    '#c9c9c9',
    '#d0b8a3',
]
background = '#222222'
brights = [
    '#474747',
    '#a97775',
    '#8c8c8c',
    '#a99175',
    '#98bd5e',
    '#a3a3a3',
    '#dcdcdc',
    '#d8c8bb',
]
cursor_bg = '#a0a0a0'
cursor_border = '#a0a0a0'
cursor_fg = '#a0a0a0'
foreground = '#a0a0a0'

[colors.indexed]

[metadata]
name = 'N0tch2k (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
