[colors]
ansi = [
    '#20242d',
    '#ff8e8e',
    '#7efdd0',
    '#fcad3f',
    '#69b4f9',
    '#dd92f6',
    '#8ce8ff',
    '#c9cccd',
]
background = '#20242d'
brights = [
    '#20242d',
    '#ff8e8e',
    '#7efdd0',
    '#fcad3f',
    '#69b4f9',
    '#dd92f6',
    '#8ce8ff',
    '#c9cccd',
]
cursor_bg = '#c7c8ff'
cursor_border = '#c7c8ff'
cursor_fg = '#c7c8ff'
foreground = '#c7c8ff'

[colors.indexed]

[metadata]
name = 'neon-night (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
