[colors]
ansi = [
    '#373d48',
    '#9b3e46',
    '#095b32',
    '#808020',
    '#1d3e6f',
    '#823065',
    '#3a7458',
    '#828282',
]
background = '#2f2f2f'
brights = [
    '#5c6370',
    '#d0555f',
    '#119955',
    '#dfe048',
    '#4674b8',
    '#ed86c9',
    '#70d2a4',
    '#dfdfdf',
]
cursor_bg = '#dfdfdf'
cursor_border = '#dfdfdf'
cursor_fg = '#dfdfdf'
foreground = '#dfdfdf'

[colors.indexed]

[metadata]
name = 'nighty (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
