[colors]
ansi = [
    '#011627',
    '#ef5350',
    '#22da6e',
    '#addb67',
    '#82aaff',
    '#c792ea',
    '#21c7a8',
    '#ffffff',
]
background = '#011627'
brights = [
    '#575656',
    '#ef5350',
    '#22da6e',
    '#ffeb95',
    '#82aaff',
    '#c792ea',
    '#7fdbca',
    '#ffffff',
]
cursor_bg = '#d6deeb'
cursor_border = '#d6deeb'
cursor_fg = '#d6deeb'
foreground = '#d6deeb'

[colors.indexed]

[metadata]
name = 'NightOwl (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
