[colors]
ansi = [
    '#000000',
    '#a60001',
    '#00bb00',
    '#fecd22',
    '#3a9bdb',
    '#bb00bb',
    '#00bbbb',
    '#bbbbbb',
]
background = '#283033'
brights = [
    '#555555',
    '#ff0003',
    '#93c863',
    '#fef874',
    '#a1d7ff',
    '#ff55ff',
    '#55ffff',
    '#ffffff',
]
cursor_bg = '#cdcdcd'
cursor_border = '#cdcdcd'
cursor_fg = '#cdcdcd'
foreground = '#cdcdcd'

[colors.indexed]

[metadata]
name = 'Obsidian (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
