[colors]
ansi = [
    '#000000',
    '#ac2e31',
    '#31ac61',
    '#ac4300',
    '#2d57ac',
    '#b08528',
    '#1fa6ac',
    '#8a8eac',
]
background = '#222125'
brights = [
    '#5b3725',
    '#ff3d48',
    '#3bff99',
    '#ff5e1e',
    '#4488ff',
    '#ffc21d',
    '#1ffaff',
    '#5b6ea7',
]
cursor_bg = '#8a8dae'
cursor_border = '#8a8dae'
cursor_fg = '#8a8dae'
foreground = '#8a8dae'

[colors.indexed]

[metadata]
name = 'Ollie (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
