[colors]
ansi = [
    '#000000',
    '#e06c75',
    '#98c379',
    '#d19a66',
    '#61afef',
    '#c678dd',
    '#56b6c2',
    '#abb2bf',
]
background = '#1e2127'
brights = [
    '#5c6370',
    '#e06c75',
    '#98c379',
    '#d19a66',
    '#61afef',
    '#c678dd',
    '#56b6c2',
    '#fffefe',
]
cursor_bg = '#5c6370'
cursor_border = '#5c6370'
cursor_fg = '#5c6370'
foreground = '#5c6370'

[colors.indexed]

[metadata]
name = 'OneDark (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
