[colors]
ansi = [
    '#282c34',
    '#e06c75',
    '#98c379',
    '#e5c07b',
    '#61afef',
    '#c678dd',
    '#56b6c2',
    '#dcdfe4',
]
background = '#000000'
brights = [
    '#282c34',
    '#e06c75',
    '#98c379',
    '#e5c07b',
    '#61afef',
    '#c678dd',
    '#56b6c2',
    '#dcdfe4',
]
cursor_bg = '#dcdfe4'
cursor_border = '#dcdfe4'
cursor_fg = '#dcdfe4'
foreground = '#dcdfe4'

[colors.indexed]

[metadata]
name = 'OneHalfBlack (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
