[colors]
ansi = [
    '#0a0a0a',
    '#ab8f74',
    '#74ab8f',
    '#8fab74',
    '#8f74ab',
    '#ab748f',
    '#748fab',
    '#f2f2f2',
]
background = '#232e37'
brights = [
    '#5d5d5d',
    '#ff1d62',
    '#9cc3af',
    '#ffd00a',
    '#af9cc3',
    '#ff1d62',
    '#4bb8fd',
    '#a020f0',
]
cursor_bg = '#d9e6f2'
cursor_border = '#d9e6f2'
cursor_fg = '#d9e6f2'
foreground = '#d9e6f2'

[colors.indexed]

[metadata]
name = 'Pali (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
