[colors]
ansi = [
    '#1f1f20',
    '#fb055a',
    '#26ffd4',
    '#fdaa5a',
    '#5c9fff',
    '#fc59a6',
    '#26ffd4',
    '#f0f0f0',
]
background = '#1d1e20'
brights = [
    '#5c6370',
    '#fb055a',
    '#26ffd4',
    '#febe7e',
    '#55adff',
    '#fd95d0',
    '#26ffd4',
    '#f0f0f0',
]
cursor_bg = '#f0f0f0'
cursor_border = '#f0f0f0'
cursor_fg = '#f0f0f0'
foreground = '#f0f0f0'

[colors.indexed]

[metadata]
name = 'Panda (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
