[colors]
ansi = [
    '#1c1c1c',
    '#af005f',
    '#5faf00',
    '#d7af5f',
    '#5fafd7',
    '#808080',
    '#d7875f',
    '#d0d0d0',
]
background = '#1c1c1c'
brights = [
    '#585858',
    '#5faf5f',
    '#afd700',
    '#af87d7',
    '#ffaf00',
    '#ff5faf',
    '#00afaf',
    '#5f8787',
]
cursor_bg = '#d0d0d0'
cursor_border = '#d0d0d0'
cursor_fg = '#d0d0d0'
foreground = '#d0d0d0'

[colors.indexed]

[metadata]
name = 'PaperColorDark (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
