[colors]
ansi = [
    '#2a2a2a',
    '#ff0000',
    '#79ff0f',
    '#d3bf00',
    '#396bd7',
    '#b449be',
    '#66ccff',
    '#bbbbbb',
]
background = '#000000'
brights = [
    '#666666',
    '#ff0080',
    '#66ff66',
    '#f3d64e',
    '#709aed',
    '#db67e6',
    '#7adff2',
    '#ffffff',
]
cursor_bg = '#f2f2f2'
cursor_border = '#f2f2f2'
cursor_fg = '#f2f2f2'
foreground = '#f2f2f2'

[colors.indexed]

[metadata]
name = 'PaulMillr (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
