[colors]
ansi = [
    '#353535',
    '#e64569',
    '#89d287',
    '#dab752',
    '#439ecf',
    '#d961dc',
    '#64aaaf',
    '#b3b3b3',
]
background = '#000000'
brights = [
    '#535353',
    '#e4859a',
    '#a2cca1',
    '#e1e387',
    '#6fbbe2',
    '#e586e7',
    '#96dcda',
    '#dedede',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#bbbbbb'
foreground = '#c7c7c7'

[colors.indexed]

[metadata]
name = 'Peppermint (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
