[colors]
ansi = [
    '#2f2e2d',
    '#a36666',
    '#90a57d',
    '#d7af87',
    '#7fa5bd',
    '#c79ec4',
    '#8adbb4',
    '#d0d0d0',
]
background = '#1c1c1c'
brights = [
    '#4a4845',
    '#d78787',
    '#afbea2',
    '#e4c9af',
    '#a1bdce',
    '#d7beda',
    '#b1e7dd',
    '#efefef',
]
cursor_bg = '#d0d0d0'
cursor_border = '#d0d0d0'
cursor_fg = '#d0d0d0'
foreground = '#d0d0d0'

[colors.indexed]

[metadata]
name = 'Pnevma (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
