[colors]
ansi = [
    '#000000',
    '#7e0008',
    '#098003',
    '#c4a000',
    '#010083',
    '#d33682',
    '#0e807f',
    '#7f7c7f',
]
background = '#052454'
brights = [
    '#808080',
    '#ef2929',
    '#1cfe3c',
    '#fefe45',
    '#268ad2',
    '#fe13fa',
    '#29fffe',
    '#c2c1c3',
]
cursor_bg = '#f6f6f7'
cursor_border = '#f6f6f7'
cursor_fg = '#f6f6f7'
foreground = '#f6f6f7'

[colors.indexed]

[metadata]
name = 'PowerShell (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
