[colors]
ansi = [
    '#0d1117',
    '#e34c26',
    '#238636',
    '#ed9a51',
    '#a5d6ff',
    '#6eb0e8',
    '#c09aeb',
    '#c9d1d9',
]
background = '#161b22'
brights = [
    '#0d1117',
    '#ff7b72',
    '#3bab4a',
    '#ffa657',
    '#a5d6ff',
    '#79c0ff',
    '#b694df',
    '#c9d1d9',
]
cursor_bg = '#c9d1d9'
cursor_border = '#c9d1d9'
cursor_fg = '#c9d1d9'
foreground = '#c9d1d9'

[colors.indexed]

[metadata]
name = 'PurplePeopleEater (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
