[colors]
ansi = [
    '#000000',
    '#d62e4e',
    '#71be6b',
    '#beb86b',
    '#489bee',
    '#e979d7',
    '#6bbeb8',
    '#d6d6d6',
]
background = '#762423'
brights = [
    '#262626',
    '#e02553',
    '#aff08c',
    '#dfddb7',
    '#65aaf1',
    '#ddb7df',
    '#b7dfdd',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#ffffff'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'RedAlert (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
