[colors]
ansi = [
    '#000000',
    '#ff3f00',
    '#00bb00',
    '#e7b000',
    '#0072ff',
    '#bb00bb',
    '#00bbbb',
    '#bbbbbb',
]
background = '#7a251e'
brights = [
    '#555555',
    '#bb0000',
    '#00bb00',
    '#e7b000',
    '#0072ae',
    '#ff55ff',
    '#55ffff',
    '#ffffff',
]
cursor_bg = '#d7c9a7'
cursor_border = '#d7c9a7'
cursor_fg = '#d7c9a7'
foreground = '#d7c9a7'

[colors.indexed]

[metadata]
name = 'RedSands (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
