[colors]
ansi = [
    '#241f2b',
    '#91284c',
    '#23801c',
    '#b49d27',
    '#6580b0',
    '#674d96',
    '#8aaabe',
    '#524966',
]
background = '#100815'
brights = [
    '#312d3d',
    '#d5356c',
    '#2cd946',
    '#fde83b',
    '#90baf9',
    '#a479e3',
    '#acd4eb',
    '#9e8cbd',
]
cursor_bg = '#514968'
cursor_border = '#514968'
cursor_fg = '#514968'
foreground = '#514968'

[colors.indexed]

[metadata]
name = 'Royal (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
