[colors]
ansi = [
    '#000000',
    '#dd0007',
    '#07dd00',
    '#ddd600',
    '#0007dd',
    '#d600dd',
    '#00ddd6',
    '#f2f2f2',
]
background = '#758480'
brights = [
    '#7d7d7d',
    '#ff7478',
    '#78ff74',
    '#fffa74',
    '#7478ff',
    '#fa74ff',
    '#74fffa',
    '#ffffff',
]
cursor_bg = '#23476a'
cursor_border = '#23476a'
cursor_fg = '#23476a'
foreground = '#23476a'

[colors.indexed]

[metadata]
name = 'Sat (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
