[colors]
ansi = [
    '#757575',
    '#825d4d',
    '#728c62',
    '#ada16d',
    '#4d7b82',
    '#8a7267',
    '#729494',
    '#e0e0e0',
]
background = '#243435'
brights = [
    '#8a8a8a',
    '#cf937a',
    '#98d9aa',
    '#fae79d',
    '#7ac3cf',
    '#d6b2a1',
    '#ade0e0',
    '#e0e0e0',
]
cursor_bg = '#d4e7d4'
cursor_border = '#d4e7d4'
cursor_fg = '#d4e7d4'
foreground = '#d4e7d4'

[colors.indexed]

[metadata]
name = 'SeafoamPastel (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
