[colors]
ansi = [
    '#17384c',
    '#d15123',
    '#027c9b',
    '#fca02f',
    '#1e4950',
    '#68d4f1',
    '#50a3b5',
    '#deb88d',
]
background = '#09141b'
brights = [
    '#434b53',
    '#d48678',
    '#628d98',
    '#fdd39f',
    '#1bbcdd',
    '#bbe3ee',
    '#87acb4',
    '#fee4ce',
]
cursor_bg = '#deb88d'
cursor_border = '#deb88d'
cursor_fg = '#deb88d'
foreground = '#deb88d'

[colors.indexed]

[metadata]
name = 'SeaShells (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
