[colors]
ansi = [
    '#323232',
    '#c22832',
    '#8ec43d',
    '#e0c64f',
    '#43a5d5',
    '#8b57b5',
    '#8ec43d',
    '#eeeeee',
]
background = '#111213'
brights = [
    '#323232',
    '#c22832',
    '#8ec43d',
    '#e0c64f',
    '#43a5d5',
    '#8b57b5',
    '#8ec43d',
    '#ffffff',
]
cursor_bg = '#cacecd'
cursor_border = '#cacecd'
cursor_fg = '#cacecd'
foreground = '#cacecd'

[colors.indexed]

[metadata]
name = 'Seti (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
