[colors]
ansi = [
    '#222222',
    '#e2a8bf',
    '#81d778',
    '#c4c9c0',
    '#264b49',
    '#a481d3',
    '#15ab9c',
    '#02c5e0',
]
background = '#222222'
brights = [
    '#ffffff',
    '#ffcdd9',
    '#beffa8',
    '#d0ccca',
    '#7ab0d2',
    '#c5a7d9',
    '#8cdfe0',
    '#e0e0e0',
]
cursor_bg = '#35b1d2'
cursor_border = '#35b1d2'
cursor_fg = '#35b1d2'
foreground = '#35b1d2'

[colors.indexed]

[metadata]
name = 'Slate (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
