[colors]
ansi = [
    '#25292a',
    '#f24840',
    '#629655',
    '#b68800',
    '#2075c7',
    '#797fd4',
    '#15968d',
    '#d2d8d9',
]
background = '#3d3f41'
brights = [
    '#25292a',
    '#f24840',
    '#629655',
    '#b68800',
    '#2075c7',
    '#797fd4',
    '#15968d',
    '#d2d8d9',
]
cursor_bg = '#d2d8d9'
cursor_border = '#d2d8d9'
cursor_fg = '#d2d8d9'
foreground = '#d2d8d9'

[colors.indexed]

[metadata]
name = 'SolarizedDarcula (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
