[colors]
ansi = [
    '#15171c',
    '#b24a56',
    '#92b477',
    '#c6735a',
    '#7c8fa5',
    '#a5789e',
    '#80cdcb',
    '#b3b8c3',
]
background = '#222222'
brights = [
    '#555555',
    '#ec5f67',
    '#89e986',
    '#fec254',
    '#5486c0',
    '#bf83c1',
    '#58c2c1',
    '#ffffff',
]
cursor_bg = '#c9c6bc'
cursor_border = '#c9c6bc'
cursor_fg = '#c9c6bc'
foreground = '#c9c6bc'

[colors.indexed]

[metadata]
name = 'SpaceGrayEightiesDull (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
