[colors]
ansi = [
    '#6e5346',
    '#e35b00',
    '#5cab96',
    '#e3cd7b',
    '#0f548b',
    '#e35b00',
    '#06afc7',
    '#f0f1ce',
]
background = '#0a1e24'
brights = [
    '#684c31',
    '#ff8a3a',
    '#aecab8',
    '#ffc878',
    '#67a0ce',
    '#ff8a3a',
    '#83a7b4',
    '#fefff1',
]
cursor_bg = '#ecf0c1'
cursor_border = '#ecf0c1'
cursor_fg = '#ecf0c1'
foreground = '#ecf0c1'

[colors.indexed]

[metadata]
name = 'Spacedust (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
