[colors]
ansi = [
    '#1c1b19',
    '#ff3128',
    '#519f50',
    '#fbb829',
    '#5573a3',
    '#e02c6d',
    '#0aaeb3',
    '#918175',
]
background = '#282828'
brights = [
    '#2d2b28',
    '#f75341',
    '#98bc37',
    '#fed06e',
    '#8eb2f7',
    '#e35682',
    '#53fde9',
    '#fce8c3',
]
cursor_bg = '#ebdbb2'
cursor_border = '#ebdbb2'
cursor_fg = '#ebdbb2'
foreground = '#ebdbb2'

[colors.indexed]

[metadata]
name = 'Srcery (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
