[colors]
ansi = [
    '#282c34',
    '#ed254e',
    '#71f79f',
    '#f9dc5c',
    '#7cb7ff',
    '#c74ded',
    '#00c1e4',
    '#dcdfe4',
]
background = '#282c34'
brights = [
    '#282c34',
    '#ed254e',
    '#71f79f',
    '#f9dc5c',
    '#7cb7ff',
    '#c74ded',
    '#00c1e4',
    '#dcdfe4',
]
cursor_bg = '#c3c7d1'
cursor_border = '#c3c7d1'
cursor_fg = '#c3c7d1'
foreground = '#c3c7d1'

[colors.indexed]

[metadata]
name = 'sweet-eliverlara (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
