[colors]
ansi = [
    '#000000',
    '#dc322f',
    '#56db3a',
    '#ff8400',
    '#0084d4',
    '#b729d9',
    '#ccccff',
    '#ffffff',
]
background = '#000000'
brights = [
    '#1b1d21',
    '#dc322f',
    '#56db3a',
    '#ff8400',
    '#0084d4',
    '#b729d9',
    '#ccccff',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#ffffff'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'Symphonic (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
