[colors]
ansi = [
    '#1b1d1e',
    '#f92672',
    '#4df840',
    '#f4fd22',
    '#2757d6',
    '#8c54fe',
    '#38c8b5',
    '#ccccc6',
]
background = '#1b1d1e'
brights = [
    '#505354',
    '#ff5995',
    '#b6e354',
    '#feed6c',
    '#3f78ff',
    '#9e6ffe',
    '#23cfd5',
    '#f8f8f2',
]
cursor_bg = '#f8f8f8'
cursor_border = '#f8f8f8'
cursor_fg = '#f8f8f8'
foreground = '#f8f8f8'

[colors.indexed]

[metadata]
name = 'ThayerBright (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
