[colors]
ansi = [
    '#000000',
    '#8d534e',
    '#4e8d53',
    '#888d4e',
    '#534e8d',
    '#8d4e88',
    '#4e888d',
    '#ffffff',
]
background = '#2e2e35'
brights = [
    '#000000',
    '#b57d78',
    '#78b57d',
    '#b0b578',
    '#7d78b5',
    '#b578b0',
    '#78b0b5',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#ffffff'
foreground = '#ffffff'

[colors.indexed]

[metadata]
name = 'Tin (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
