[colors]
ansi = [
    '#000000',
    '#d54e53',
    '#b9ca49',
    '#e7c547',
    '#79a6da',
    '#c397d8',
    '#70c0b1',
    '#fffefe',
]
background = '#000000'
brights = [
    '#000000',
    '#d44d53',
    '#b9c949',
    '#e6c446',
    '#79a6da',
    '#c396d7',
    '#70c0b1',
    '#fffefe',
]
cursor_bg = '#e9e9e9'
cursor_border = '#e9e9e9'
cursor_fg = '#e9e9e9'
foreground = '#e9e9e9'

[colors.indexed]

[metadata]
name = 'TomorrowNightBright (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
