[colors]
ansi = [
    '#000000',
    '#c82828',
    '#718c00',
    '#eab700',
    '#4171ae',
    '#8959a8',
    '#3e999f',
    '#fffefe',
]
background = '#ffffff'
brights = [
    '#000000',
    '#c82828',
    '#708b00',
    '#e9b600',
    '#4170ae',
    '#8958a7',
    '#3d999f',
    '#fffefe',
]
cursor_bg = '#4c4c4c'
cursor_border = '#4c4c4c'
cursor_fg = '#4c4c4c'
foreground = '#4d4d4c'

[colors.indexed]

[metadata]
name = 'Tomorrow (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
