[colors]
ansi = [
    '#000000',
    '#f27779',
    '#99cc99',
    '#ffcc66',
    '#6699cc',
    '#cc99cc',
    '#66cccc',
    '#fffefe',
]
background = '#2c2c2c'
brights = [
    '#000000',
    '#f17779',
    '#99cc99',
    '#ffcc66',
    '#6699cc',
    '#cc99cc',
    '#66cccc',
    '#fffefe',
]
cursor_bg = '#cccccc'
cursor_border = '#cccccc'
cursor_fg = '#cccccc'
foreground = '#cccccc'

[colors.indexed]

[metadata]
name = 'TomorrowNightEighties (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
