[colors]
ansi = [
    '#2c3f58',
    '#be2d26',
    '#1a9172',
    '#db8e27',
    '#325d96',
    '#8a5edc',
    '#35a08f',
    '#23d183',
]
background = '#24364b'
brights = [
    '#336889',
    '#dd5944',
    '#31d07b',
    '#e7d84b',
    '#34a6da',
    '#ae6bdc',
    '#42c3ae',
    '#d5d5d5',
]
cursor_bg = '#31d07b'
cursor_border = '#31d07b'
cursor_fg = '#31d07b'
foreground = '#31d07b'

[colors.indexed]

[metadata]
name = 'ToyChest (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
