[colors]
ansi = [
    '#141414',
    '#c06d44',
    '#afb97a',
    '#c2a86c',
    '#44474a',
    '#b4be7c',
    '#778385',
    '#ffffd4',
]
background = '#141414'
brights = [
    '#262626',
    '#de7c4c',
    '#ccd88c',
    '#e2c47e',
    '#5a5e62',
    '#d0dc8e',
    '#8a989b',
    '#ffffd4',
]
cursor_bg = '#ffffd4'
cursor_border = '#ffffd4'
cursor_fg = '#ffffd4'
foreground = '#ffffd4'

[colors.indexed]

[metadata]
name = 'Twilight (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
