[colors]
ansi = [
    '#000000',
    '#c21b6f',
    '#6fc21b',
    '#c26f1b',
    '#1b6fc2',
    '#6f1bc2',
    '#1bc26f',
    '#808080',
]
background = '#feffee'
brights = [
    '#808080',
    '#ee84b9',
    '#b9ee84',
    '#eeb984',
    '#84b9ee',
    '#b984ee',
    '#84eeb9',
    '#e5e5e5',
]
cursor_bg = '#23476a'
cursor_border = '#23476a'
cursor_fg = '#23476a'
foreground = '#23476a'

[colors.indexed]

[metadata]
name = 'Ura (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
