[colors]
ansi = [
    '#000000',
    '#b0425b',
    '#37a415',
    '#ad5c42',
    '#564d9b',
    '#6c3ca1',
    '#808080',
    '#87799c',
]
background = '#1b1b23'
brights = [
    '#5d3225',
    '#ff6388',
    '#29e620',
    '#f08161',
    '#867aed',
    '#a05eee',
    '#eaeaea',
    '#bfa3ff',
]
cursor_bg = '#877a9b'
cursor_border = '#877a9b'
cursor_fg = '#877a9b'
foreground = '#877a9b'

[colors.indexed]

[metadata]
name = 'Urple (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
