[colors]
ansi = [
    '#020202',
    '#cd3232',
    '#00bc00',
    '#a5a900',
    '#0752a8',
    '#bc05bc',
    '#0598bc',
    '#343434',
]
background = '#f9f9f9'
brights = [
    '#5e5e5e',
    '#cd3333',
    '#1bce1a',
    '#adbb5b',
    '#0752a8',
    '#c451ce',
    '#52a8c7',
    '#a6a3a6',
]
cursor_bg = '#020202'
cursor_border = '#020202'
cursor_fg = '#020202'
foreground = '#020202'

[colors.indexed]

[metadata]
name = 'VSCodeLight+ (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
