[colors]
ansi = [
    '#000000',
    '#e24346',
    '#39b13a',
    '#dae145',
    '#4261c5',
    '#f920fb',
    '#2abbd4',
    '#d0b8a3',
]
background = '#404040'
brights = [
    '#fefcfc',
    '#e97071',
    '#9cc090',
    '#ddda7a',
    '#7b91d6',
    '#f674ba',
    '#5ed1e5',
    '#d8c8bb',
]
cursor_bg = '#afdab6'
cursor_border = '#afdab6'
cursor_fg = '#afdab6'
foreground = '#afdab6'

[colors.indexed]

[metadata]
name = 'WarmNeon (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
