[colors]
ansi = [
    '#000000',
    '#cc5555',
    '#55cc55',
    '#cdcd55',
    '#5555cc',
    '#cc55cc',
    '#7acaca',
    '#cccccc',
]
background = '#000000'
brights = [
    '#555555',
    '#ff5555',
    '#55ff55',
    '#ffff55',
    '#5555ff',
    '#ff55ff',
    '#55ffff',
    '#ffffff',
]
cursor_bg = '#b3b3b3'
cursor_border = '#b3b3b3'
cursor_fg = '#b3b3b3'
foreground = '#b3b3b3'

[colors.indexed]

[metadata]
name = 'Wez (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
