[colors]
ansi = [
    '#000000',
    '#ff615a',
    '#b1e969',
    '#ebd99c',
    '#5da9f6',
    '#e86aff',
    '#82fff7',
    '#dedacf',
]
background = '#171717'
brights = [
    '#313131',
    '#f58c80',
    '#ddf88f',
    '#eee5b2',
    '#a5c7ff',
    '#ddaaff',
    '#b7fff9',
    '#ffffff',
]
cursor_bg = '#dedacf'
cursor_border = '#dedacf'
cursor_fg = '#dedacf'
foreground = '#dedacf'

[colors.indexed]

[metadata]
name = 'Wombat (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
