[colors]
ansi = [
    '#333333',
    '#8c4665',
    '#287373',
    '#7c7c99',
    '#395573',
    '#5e468c',
    '#31658c',
    '#899ca1',
]
background = '#101010'
brights = [
    '#3d3d3d',
    '#bf4d80',
    '#53a6a6',
    '#9e9ecb',
    '#477ab3',
    '#7e62b3',
    '#6096bf',
    '#c0c0c0',
]
cursor_bg = '#999993'
cursor_border = '#999993'
cursor_fg = '#999993'
foreground = '#999993'

[colors.indexed]

[metadata]
name = 'Wryan (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
