[colors]
ansi = [
    '#2e3436',
    '#fc6386',
    '#424043',
    '#fce94f',
    '#fb976b',
    '#75507b',
    '#34e2e2',
    '#ffffff',
]
background = '#424043'
brights = [
    '#989595',
    '#fc6386',
    '#a9dc76',
    '#fce94f',
    '#fb976b',
    '#ab9df2',
    '#34e2e2',
    '#d1d1c0',
]
cursor_bg = '#fcfcfa'
cursor_border = '#fcfcfa'
cursor_fg = '#fcfcfa'
foreground = '#fcfcfa'

[colors.indexed]

[metadata]
name = 'Wzoreck (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
