[colors]
ansi = [
    '#4d4d4d',
    '#705050',
    '#60b48a',
    '#f0dfaf',
    '#506070',
    '#dc8cc3',
    '#8cd0d3',
    '#dcdccc',
]
background = '#3f3f3f'
brights = [
    '#709080',
    '#dca3a3',
    '#c3bf9f',
    '#e0cf9f',
    '#94bff3',
    '#ec93d3',
    '#93e0e3',
    '#ffffff',
]
cursor_bg = '#dcdccc'
cursor_border = '#dcdccc'
cursor_fg = '#dcdccc'
foreground = '#dcdccc'

[colors.indexed]

[metadata]
name = 'Zenburn (Gogh)'
origin_url = 'https://github.com/Gogh-Co/Gogh'
