[colors]
ansi = [
    '#000000',
    '#cd0000',
    '#00cd00',
    '#cdcd00',
    '#1093f5',
    '#cd00cd',
    '#00cdcd',
    '#faebd7',
]
background = '#111416'
brights = [
    '#404040',
    '#ff0000',
    '#00ff00',
    '#ffff00',
    '#11b5f6',
    '#ff00ff',
    '#00ffff',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#eeeeec'
selection_bg = '#eeeeec'
selection_fg = '#333333'

[colors.indexed]

[metadata]
name = 'Abernathy'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
