[colors]
ansi = [
    '#000000',
    '#cd3131',
    '#05bc79',
    '#e5e512',
    '#2472c8',
    '#bc3fbc',
    '#0fa8cd',
    '#e5e5e5',
]
background = '#262a33'
brights = [
    '#666666',
    '#cd3131',
    '#05bc79',
    '#e5e512',
    '#2472c8',
    '#bc3fbc',
    '#0fa8cd',
    '#e5e5e5',
]
cursor_bg = '#f8f8f0'
cursor_border = '#f8f8f0'
cursor_fg = '#cfcfc2'
foreground = '#e5e5e5'
selection_bg = '#5a5c62'
selection_fg = '#ece7e7'

[colors.indexed]

[metadata]
name = 'Andromeda'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
