[colors]
ansi = [
    '#202746',
    '#c94922',
    '#ac9739',
    '#c08b30',
    '#3d8fd1',
    '#6679cc',
    '#22a2c9',
    '#979db4',
]
background = '#202746'
brights = [
    '#6b7394',
    '#c76b29',
    '#293256',
    '#5e6687',
    '#898ea4',
    '#dfe2f1',
    '#9c637a',
    '#f5f7ff',
]
cursor_bg = '#979db4'
cursor_border = '#979db4'
cursor_fg = '#202746'
foreground = '#979db4'
selection_bg = '#5e6687'
selection_fg = '#979db4'

[colors.indexed]

[metadata]
name = 'AtelierSulphurpool'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
