[colors]
ansi = [
    '#23262e',
    '#f0266f',
    '#8fd46d',
    '#ffe66d',
    '#0321d7',
    '#ee5d43',
    '#03d6b8',
    '#c74ded',
]
background = '#23262e'
brights = [
    '#292e38',
    '#f92672',
    '#8fd46d',
    '#ffe66d',
    '#03d6b8',
    '#ee5d43',
    '#03d6b8',
    '#c74ded',
]
cursor_bg = '#ee5d43'
cursor_border = '#ee5d43'
cursor_fg = '#ffd29c'
foreground = '#ffca28'
selection_bg = '#292e38'
selection_fg = '#00e8c6'

[colors.indexed]

[metadata]
name = 'Aurora'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
