[colors]
ansi = [
    '#191e2a',
    '#ed8274',
    '#a6cc70',
    '#fad07b',
    '#6dcbfa',
    '#cfbafa',
    '#90e1c6',
    '#c7c7c7',
]
background = '#1f2430'
brights = [
    '#686868',
    '#f28779',
    '#bae67e',
    '#ffd580',
    '#73d0ff',
    '#d4bfff',
    '#95e6cb',
    '#ffffff',
]
cursor_bg = '#ffcc66'
cursor_border = '#ffcc66'
cursor_fg = '#1f2430'
foreground = '#cbccc6'
selection_bg = '#33415e'
selection_fg = '#cbccc6'

[colors.indexed]

[metadata]
name = 'Ayu Mirage'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
