[colors]
ansi = [
    '#20111b',
    '#be100e',
    '#858162',
    '#eaa549',
    '#426a79',
    '#97522c',
    '#989a9c',
    '#968c83',
]
background = '#20111b'
brights = [
    '#5e5252',
    '#be100e',
    '#858162',
    '#eaa549',
    '#426a79',
    '#97522c',
    '#989a9c',
    '#d5ccba',
]
cursor_bg = '#968c83'
cursor_border = '#968c83'
cursor_fg = '#20111b'
foreground = '#968c83'
selection_bg = '#45373c'
selection_fg = '#968c83'

[colors.indexed]

[metadata]
name = 'Belafonte Night'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
