[colors]
ansi = [
    '#4f4f4f',
    '#ff6c60',
    '#a8ff60',
    '#ffffb6',
    '#96cbfe',
    '#ff73fd',
    '#c6c5fe',
    '#eeeeee',
]
background = '#0000a4'
brights = [
    '#7c7c7c',
    '#ffb6b0',
    '#ceffac',
    '#ffffcc',
    '#b5dcff',
    '#ff9cfe',
    '#dfdffe',
    '#ffffff',
]
cursor_bg = '#ffa560'
cursor_border = '#ffa560'
cursor_fg = '#ffffff'
foreground = '#ffff4e'
selection_bg = '#a4a4a4'
selection_fg = '#0000a4'

[colors.indexed]

[metadata]
name = 'Borland'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
