[colors]
ansi = [
    '#073642',
    '#dc322f',
    '#859900',
    '#b58900',
    '#268bd2',
    '#d33682',
    '#2aa198',
    '#eee8d5',
]
background = '#fdf6e3'
brights = [
    '#002b36',
    '#cb4b16',
    '#586e75',
    '#657b83',
    '#839496',
    '#6c71c4',
    '#93a1a1',
    '#fdf6e3',
]
cursor_bg = '#657b83'
cursor_border = '#657b83'
cursor_fg = '#eee8d5'
foreground = '#657b83'
selection_bg = '#eee8d5'
selection_fg = '#586e75'

[colors.indexed]

[metadata]
name = 'Builtin Solarized Light'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
