[colors]
ansi = [
    '#7d8b8f',
    '#b23a52',
    '#789b6a',
    '#b9ac4a',
    '#2a7fac',
    '#bd4f5a',
    '#44a799',
    '#d2d8d9',
]
background = '#2b2d2e'
brights = [
    '#888888',
    '#f24840',
    '#80c470',
    '#ffeb62',
    '#4196ff',
    '#fc5275',
    '#53cdbd',
    '#d2d8d9',
]
cursor_bg = '#708284'
cursor_border = '#708284'
cursor_fg = '#002831'
foreground = '#d2d8d9'
selection_bg = '#e4e8ed'
selection_fg = '#3f4041'

[colors.indexed]

[metadata]
name = 'Chalk'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
