[colors]
ansi = [
    '#141228',
    '#ff5458',
    '#62d196',
    '#ffb378',
    '#65b2ff',
    '#906cff',
    '#63f2f1',
    '#a6b3cc',
]
background = '#1e1c31'
brights = [
    '#565575',
    '#ff8080',
    '#95ffa4',
    '#ffe9aa',
    '#91ddff',
    '#c991e1',
    '#aaffe4',
    '#cbe3e7',
]
cursor_bg = '#fbfcfc'
cursor_border = '#fbfcfc'
cursor_fg = '#ff271d'
foreground = '#cbe1e7'
selection_bg = '#cbe1e7'
selection_fg = '#1e1c31'

[colors.indexed]

[metadata]
name = 'ChallengerDeep'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
