[colors]
ansi = [
    '#000000',
    '#ff0000',
    '#38de21',
    '#ffe50a',
    '#1460d2',
    '#ff005d',
    '#00bbbb',
    '#bbbbbb',
]
background = '#132738'
brights = [
    '#555555',
    '#f40e17',
    '#3bd01d',
    '#edc809',
    '#5555ff',
    '#ff55ff',
    '#6ae3fa',
    '#ffffff',
]
cursor_bg = '#f0cc09'
cursor_border = '#f0cc09'
cursor_fg = '#fefff2'
foreground = '#ffffff'
selection_bg = '#18354f'
selection_fg = '#b5b5b5'

[colors.indexed]

[metadata]
name = 'Cobalt2'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
