[colors]
ansi = [
    '#080808',
    '#ff8373',
    '#00c172',
    '#d2a700',
    '#0071cf',
    '#ff90fe',
    '#6bffdd',
    '#f1f1f1',
]
background = '#151144'
brights = [
    '#2e2e2e',
    '#ffc4be',
    '#d6fcba',
    '#fffed5',
    '#c2e3ff',
    '#ffb2fe',
    '#e6e7fe',
    '#ffffff',
]
cursor_bg = '#00ff9c'
cursor_border = '#00ff9c'
cursor_fg = '#ffffff'
foreground = '#00ff92'
selection_bg = '#454d96'
selection_fg = '#f4f4f4'

[colors.indexed]

[metadata]
name = 'Cyberdyne'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
