[colors]
ansi = [
    '#000000',
    '#fd6209',
    '#41a83e',
    '#ffe862',
    '#245032',
    '#f8f8f8',
    '#9df39f',
    '#ffffff',
]
background = '#051f14'
brights = [
    '#323232',
    '#ff943b',
    '#73da70',
    '#ffff94',
    '#568264',
    '#ffffff',
    '#cfffd1',
    '#ffffff',
]
cursor_bg = '#ffcc00'
cursor_border = '#ffcc00'
cursor_fg = '#dadedc'
foreground = '#dadedc'
selection_bg = '#203727'
selection_fg = '#dadedc'

[colors.indexed]

[metadata]
name = 'DjangoRebornAgain'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
