[colors]
ansi = [
    '#333333',
    '#f8818e',
    '#92d3a2',
    '#1a8e63',
    '#8ed0ce',
    '#5e468c',
    '#31658c',
    '#e2d8cd',
]
background = '#051519'
brights = [
    '#3d3d3d',
    '#fb3d66',
    '#6bb48d',
    '#30c85a',
    '#39a7a2',
    '#7e62b3',
    '#6096bf',
    '#e2d8cd',
]
cursor_bg = '#9e9ecb'
cursor_border = '#9e9ecb'
cursor_fg = '#000000'
foreground = '#e2d8cd'
selection_bg = '#4d4d4d'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'ForestBlue'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
