[colors]
ansi = [
    '#141414',
    '#ff5555',
    '#98ec65',
    '#ffcc33',
    '#00aaff',
    '#aa88ff',
    '#88ddff',
    '#cccccc',
]
background = '#111111'
brights = [
    '#414141',
    '#ff8888',
    '#b6f292',
    '#ffd966',
    '#33bbff',
    '#cebbff',
    '#bbecff',
    '#ffffff',
]
cursor_bg = '#fcdc08'
cursor_border = '#fcdc08'
cursor_fg = '#161616'
foreground = '#777777'
selection_bg = '#666666'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Framer'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
