[colors]
ansi = [
    '#000000',
    '#bb0000',
    '#00bb00',
    '#e7b000',
    '#0000a3',
    '#950062',
    '#00bbbb',
    '#bbbbbb',
]
background = '#13773d'
brights = [
    '#555555',
    '#bb0000',
    '#00bb00',
    '#e7b000',
    '#0000bb',
    '#ff55ff',
    '#55ffff',
    '#ffffff',
]
cursor_bg = '#8c2800'
cursor_border = '#8c2800'
cursor_fg = '#ffffff'
foreground = '#fff0a5'
selection_bg = '#b64926'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Grass'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
