[colors]
ansi = [
    '#000000',
    '#fe1414',
    '#74ff00',
    '#f1ff01',
    '#00deff',
    '#ff00f0',
    '#00ffbc',
    '#ffffff',
]
background = '#002a1a'
brights = [
    '#666666',
    '#ff3939',
    '#00ff44',
    '#ffd100',
    '#00afff',
    '#ff008a',
    '#00ffd3',
    '#f5ecec',
]
cursor_bg = '#fff400'
cursor_border = '#fff400'
cursor_fg = '#e1e4e3'
foreground = '#ffffff'
selection_bg = '#517e50'
selection_fg = '#e2e2e2'

[colors.indexed]

[metadata]
name = 'Grey-green'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
