[colors]
ansi = [
    '#322931',
    '#dd464c',
    '#8fc13e',
    '#fdcc59',
    '#1290bf',
    '#c85e7c',
    '#149b93',
    '#b9b5b8',
]
background = '#322931'
brights = [
    '#797379',
    '#dd464c',
    '#8fc13e',
    '#fdcc59',
    '#1290bf',
    '#c85e7c',
    '#149b93',
    '#ffffff',
]
cursor_bg = '#b9b5b8'
cursor_border = '#b9b5b8'
cursor_fg = '#322931'
foreground = '#b9b5b8'
selection_bg = '#5c545b'
selection_fg = '#b9b5b8'

[colors.indexed]

[metadata]
name = 'Hopscotch.256'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
