[colors]
ansi = [
    '#2a2e33',
    '#b84d51',
    '#b3bf5a',
    '#e4b55e',
    '#6e90b0',
    '#a17eac',
    '#7fbfb4',
    '#b5b9b6',
]
background = '#161719'
brights = [
    '#1d1f22',
    '#8d2e32',
    '#798431',
    '#e58a50',
    '#4b6b88',
    '#6e5079',
    '#4d7b74',
    '#5a626a',
]
cursor_bg = '#b7bcba'
cursor_border = '#b7bcba'
cursor_fg = '#1e1f22'
foreground = '#b7bcba'
selection_bg = '#1e1f22'
selection_fg = '#b7bcba'

[colors.indexed]

[metadata]
name = 'Hybrid'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
