[colors]
ansi = [
    '#dcdfe7',
    '#cc517a',
    '#668e3d',
    '#c57339',
    '#2d539e',
    '#7759b4',
    '#3f83a6',
    '#33374c',
]
background = '#e8e9ec'
brights = [
    '#8389a3',
    '#cc3768',
    '#598030',
    '#b6662d',
    '#22478e',
    '#6845ad',
    '#327698',
    '#262a3f',
]
cursor_bg = '#33374c'
cursor_border = '#33374c'
cursor_fg = '#e8e9ec'
foreground = '#33374c'
selection_bg = '#33374c'
selection_fg = '#e8e9ec'

[colors.indexed]

[metadata]
name = 'iceberg-light'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
