[colors]
ansi = [
    '#323232',
    '#d25252',
    '#7fe173',
    '#ffc66d',
    '#4099ff',
    '#f680ff',
    '#bed6ff',
    '#eeeeec',
]
background = '#323232'
brights = [
    '#535353',
    '#f07070',
    '#9dff91',
    '#ffe48b',
    '#5eb7f7',
    '#ff9dff',
    '#dcf4ff',
    '#ffffff',
]
cursor_bg = '#d6d6d6'
cursor_border = '#d6d6d6'
cursor_fg = '#000000'
foreground = '#ffffff'
selection_bg = '#5b5b5b'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'idleToes'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
