[colors]
ansi = [
    '#000000',
    '#fa5355',
    '#126e00',
    '#c2c300',
    '#4581eb',
    '#fa54ff',
    '#33c2c1',
    '#adadad',
]
background = '#202020'
brights = [
    '#555555',
    '#fb7172',
    '#67ff4f',
    '#ffff00',
    '#6d9df1',
    '#fb82ff',
    '#60d3d1',
    '#eeeeee',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#000000'
foreground = '#adadad'
selection_bg = '#1a3272'
selection_fg = '#adadad'

[colors.indexed]

[metadata]
name = 'JetBrains Darcula'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
