[colors]
ansi = [
    '#626262',
    '#ff8373',
    '#b4fb73',
    '#09b4bd',
    '#fed300',
    '#ff90fe',
    '#d1d1fe',
    '#f1f1f1',
]
background = '#030d18'
brights = [
    '#8f8f8f',
    '#ffc4be',
    '#d6fcba',
    '#fffed5',
    '#f92883',
    '#ffb2fe',
    '#e6e7fe',
    '#ffffff',
]
cursor_bg = '#00ff9c'
cursor_border = '#00ff9c'
cursor_fg = '#ffffff'
foreground = '#f106e3'
selection_bg = '#2e206a'
selection_fg = '#f4f4f4'

[colors.indexed]

[metadata]
name = 'Laser'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
