[colors]
ansi = [
    '#000000',
    '#ff3030',
    '#559a70',
    '#ccac00',
    '#0099cc',
    '#cc69c8',
    '#7ac4cc',
    '#bccccc',
]
background = '#000000'
brights = [
    '#000000',
    '#ff3030',
    '#559a70',
    '#ccac00',
    '#0099cc',
    '#cc69c8',
    '#7ac4cc',
    '#bccccc',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#000000'
foreground = '#afc2c2'
selection_bg = '#7dbeff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'LiquidCarbonTransparent'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
