[colors]
ansi = [
    '#282a36',
    '#f37f97',
    '#5adecd',
    '#f2a272',
    '#8897f4',
    '#c574dd',
    '#79e6f3',
    '#fdfdfd',
]
background = '#1d1f28'
brights = [
    '#414458',
    '#ff4971',
    '#18e3c8',
    '#ff8037',
    '#556fff',
    '#b043d1',
    '#3fdcee',
    '#bebec1',
]
cursor_bg = '#c574dd'
cursor_border = '#c574dd'
cursor_fg = '#ffffff'
foreground = '#fdfdfd'
selection_bg = '#c1deff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'lovelace'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
