[colors]
ansi = [
    '#000000',
    '#ec5f66',
    '#99c794',
    '#f9ae58',
    '#6699cc',
    '#c695c6',
    '#5fb4b4',
    '#f7f7f7',
]
background = '#343d46'
brights = [
    '#333333',
    '#f97b58',
    '#acd1a8',
    '#fac761',
    '#85add6',
    '#d8b6d8',
    '#82c4c4',
    '#ffffff',
]
cursor_bg = '#fcbb6a'
cursor_border = '#fcbb6a'
cursor_fg = '#ffffff'
foreground = '#d8dee9'
selection_bg = '#4e5a65'
selection_fg = '#d8dee9'

[colors.indexed]

[metadata]
name = 'Mariana'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
