[colors]
ansi = [
    '#212121',
    '#b7141f',
    '#457b24',
    '#f6981e',
    '#134eb2',
    '#560088',
    '#0e717c',
    '#efefef',
]
background = '#eaeaea'
brights = [
    '#424242',
    '#e83b3f',
    '#7aba3a',
    '#ffea2e',
    '#54a4f3',
    '#aa4dbc',
    '#26bbd1',
    '#d9d9d9',
]
cursor_bg = '#16afca'
cursor_border = '#16afca'
cursor_fg = '#2e2e2d'
foreground = '#232322'
selection_bg = '#c2c2c2'
selection_fg = '#4e4e4e'

[colors.indexed]

[metadata]
name = 'Material'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
