[colors]
ansi = [
    '#121212',
    '#fa2573',
    '#98e123',
    '#dfd460',
    '#1080d0',
    '#8700ff',
    '#43a8d0',
    '#bbbbbb',
]
background = '#121212'
brights = [
    '#555555',
    '#f6669d',
    '#b1e05f',
    '#fff26d',
    '#00afff',
    '#af87ff',
    '#51ceff',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#bbbbbb'
selection_bg = '#b5d5ff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Molokai'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
