[colors]
ansi = [
    '#0f191f',
    '#de6e7c',
    '#90ff6b',
    '#b77e64',
    '#8190d4',
    '#b279a7',
    '#66a5ad',
    '#c6d5cf',
]
background = '#0f191f'
brights = [
    '#263945',
    '#e8838f',
    '#a0ff85',
    '#d68c67',
    '#92a0e2',
    '#cf86c1',
    '#65b8c1',
    '#98a39e',
]
cursor_bg = '#ceddd7'
cursor_border = '#ceddd7'
cursor_fg = '#0f191f'
foreground = '#c6d5cf'
selection_bg = '#3a3e3d'
selection_fg = '#c6d5cf'

[colors.indexed]

[metadata]
name = 'neobones_dark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
