[colors]
ansi = [
    '#000000',
    '#ac2e31',
    '#31ac61',
    '#ac4300',
    '#2d57ac',
    '#b08528',
    '#1fa6ac',
    '#8a8eac',
]
background = '#222125'
brights = [
    '#5b3725',
    '#ff3d48',
    '#3bff99',
    '#ff5e1e',
    '#4488ff',
    '#ffc21d',
    '#1ffaff',
    '#5b6ea7',
]
cursor_bg = '#5b6ea7'
cursor_border = '#5b6ea7'
cursor_fg = '#2a292d'
foreground = '#8a8dae'
selection_bg = '#1e3a66'
selection_fg = '#8a8eac'

[colors.indexed]

[metadata]
name = 'Ollie'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
