[colors]
ansi = [
    '#5a5a5a',
    '#ca372d',
    '#4d7b3a',
    '#d4d697',
    '#4387cf',
    '#b86cb4',
    '#72d5c6',
    '#ced4cd',
]
background = '#191919'
brights = [
    '#9a9b99',
    '#c37d62',
    '#83d0a2',
    '#fdfdc5',
    '#89d3f6',
    '#ff2c7a',
    '#82eada',
    '#fdfdf6',
]
cursor_bg = '#fcdc08'
cursor_border = '#fcdc08'
cursor_fg = '#161616'
foreground = '#c3cac2'
selection_bg = '#19273b'
selection_fg = '#dde5dc'

[colors.indexed]

[metadata]
name = 'Operator Mono Dark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
