[colors]
ansi = [
    '#000000',
    '#ff4242',
    '#74af68',
    '#ffad29',
    '#338f86',
    '#9414e6',
    '#23d7d7',
    '#e2e2e2',
]
background = '#141e43'
brights = [
    '#3f5648',
    '#ff3242',
    '#74cd68',
    '#ffb929',
    '#23d7d7',
    '#ff37ff',
    '#00ede1',
    '#ffffff',
]
cursor_bg = '#43d58e'
cursor_border = '#43d58e'
cursor_fg = '#ffffff'
foreground = '#e1e1e1'
selection_bg = '#2d37ff'
selection_fg = '#82e0ff'

[colors.indexed]

[metadata]
name = 'Pandora'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
