[colors]
ansi = [
    '#353535',
    '#e74669',
    '#89d287',
    '#dab853',
    '#449fd0',
    '#da62dc',
    '#65aaaf',
    '#b4b4b4',
]
background = '#000000'
brights = [
    '#535353',
    '#e4859b',
    '#a3cca2',
    '#e1e487',
    '#6fbce2',
    '#e586e7',
    '#96dcdb',
    '#dfdfdf',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#c8c8c8'
selection_bg = '#e6e6e6'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Peppermint'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
