[colors]
ansi = [
    '#000000',
    '#db4437',
    '#0f9d58',
    '#f4b400',
    '#4285f4',
    '#db4437',
    '#4285f4',
    '#ffffff',
]
background = '#ffffff'
brights = [
    '#000000',
    '#db4437',
    '#0f9d58',
    '#f4b400',
    '#4285f4',
    '#4285f4',
    '#0f9d58',
    '#ffffff',
]
cursor_bg = '#000000'
cursor_border = '#000000'
cursor_fg = '#ffffff'
foreground = '#000000'
selection_bg = '#656565'
selection_fg = '#eeeeee'

[colors.indexed]

[metadata]
name = 'primary'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
