[colors]
ansi = [
    '#000000',
    '#990000',
    '#00a600',
    '#999900',
    '#2009db',
    '#b200b2',
    '#00a6b2',
    '#bfbfbf',
]
background = '#000000'
brights = [
    '#666666',
    '#e50000',
    '#00d900',
    '#e5e500',
    '#0000ff',
    '#e500e5',
    '#00e5e5',
    '#e5e5e5',
]
cursor_bg = '#4d4d4d'
cursor_border = '#4d4d4d'
cursor_fg = '#ffffff'
foreground = '#f2f2f2'
selection_bg = '#414141'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Pro'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
