[colors]
ansi = [
    '#000000',
    '#ff5360',
    '#59d499',
    '#ffc531',
    '#56c2ff',
    '#cf2f98',
    '#52eee5',
    '#ffffff',
]
background = '#1a1a1a'
brights = [
    '#000000',
    '#ff6363',
    '#59d499',
    '#ffc531',
    '#56c2ff',
    '#cf2f98',
    '#52eee5',
    '#ffffff',
]
cursor_bg = '#cccccc'
cursor_border = '#cccccc'
cursor_fg = '#ffffff'
foreground = '#ffffff'
selection_bg = '#333333'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Raycast_Dark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
