[colors]
ansi = [
    '#12131e',
    '#dd7755',
    '#04dbb5',
    '#f2e7b7',
    '#7aa5ff',
    '#bf9cf9',
    '#56d3c2',
    '#e4e3e9',
]
background = '#292a44'
brights = [
    '#666699',
    '#ff92cd',
    '#01eac0',
    '#fffca8',
    '#69c0fa',
    '#c17ff8',
    '#8bfde1',
    '#f4f2f9',
]
cursor_bg = '#b89bf9'
cursor_border = '#b89bf9'
cursor_fg = '#292a44'
foreground = '#e8e6ed'
selection_bg = '#663399'
selection_fg = '#f4f2f9'

[colors.indexed]

[metadata]
name = 'rebecca'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
