[colors]
ansi = [
    '#17384c',
    '#d15123',
    '#027c9b',
    '#fca02f',
    '#1e4950',
    '#68d4f1',
    '#50a3b5',
    '#deb88d',
]
background = '#09141b'
brights = [
    '#434b53',
    '#d48678',
    '#628d98',
    '#fdd39f',
    '#1bbcdd',
    '#bbe3ee',
    '#87acb4',
    '#fee4ce',
]
cursor_bg = '#fca02f'
cursor_border = '#fca02f'
cursor_fg = '#08131a'
foreground = '#deb88d'
selection_bg = '#1e4962'
selection_fg = '#fee4ce'

[colors.indexed]

[metadata]
name = 'SeaShells'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
