[colors]
ansi = [
    '#222222',
    '#e2a8bf',
    '#81d778',
    '#c4c9c0',
    '#264b49',
    '#a481d3',
    '#15ab9c',
    '#02c5e0',
]
background = '#222222'
brights = [
    '#ffffff',
    '#ffcdd9',
    '#beffa8',
    '#d0ccca',
    '#7ab0d2',
    '#c5a7d9',
    '#8cdfe0',
    '#e0e0e0',
]
cursor_bg = '#87d3c4'
cursor_border = '#87d3c4'
cursor_fg = '#323232'
foreground = '#35b1d2'
selection_bg = '#0f3754'
selection_fg = '#2dffc0'

[colors.indexed]

[metadata]
name = 'Slate'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
