[colors]
ansi = [
    '#15171c',
    '#ec5f67',
    '#81a764',
    '#fec254',
    '#5486c0',
    '#bf83c1',
    '#57c2c1',
    '#efece7',
]
background = '#222222'
brights = [
    '#555555',
    '#ff6973',
    '#93d493',
    '#ffd256',
    '#4d84d1',
    '#ff55ff',
    '#83e9e4',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#bdbaae'
selection_bg = '#272e35'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'SpaceGray Eighties'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
