[colors]
ansi = [
    '#253045',
    '#ee5577',
    '#55ee77',
    '#ffdd88',
    '#5588ff',
    '#ff77cc',
    '#44eeee',
    '#f5f5da',
]
background = '#202535'
brights = [
    '#405570',
    '#ee6655',
    '#99ee77',
    '#ffff77',
    '#77bbff',
    '#aa88ff',
    '#55ffbb',
    '#ffffee',
]
cursor_bg = '#ccced0'
cursor_border = '#ccced0'
cursor_fg = '#202535'
foreground = '#ccced0'
selection_bg = '#ccced0'
selection_fg = '#202535'

[colors.indexed]

[metadata]
name = 'Sublette'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
