[colors]
ansi = [
    '#1d202f',
    '#f7768e',
    '#9ece6a',
    '#e0af68',
    '#7aa2f7',
    '#bb9af7',
    '#7dcfff',
    '#a9b1d6',
]
background = '#24283b'
brights = [
    '#414868',
    '#f7768e',
    '#9ece6a',
    '#e0af68',
    '#7aa2f7',
    '#bb9af7',
    '#7dcfff',
    '#c0caf5',
]
cursor_bg = '#c0caf5'
cursor_border = '#c0caf5'
cursor_fg = '#1d202f'
foreground = '#c0caf5'
selection_bg = '#364a82'
selection_fg = '#c0caf5'

[colors.indexed]

[metadata]
name = 'tokyonight-storm'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
