[colors]
ansi = [
    '#15161e',
    '#f7768e',
    '#9ece6a',
    '#e0af68',
    '#7aa2f7',
    '#bb9af7',
    '#7dcfff',
    '#a9b1d6',
]
background = '#1a1b26'
brights = [
    '#414868',
    '#f7768e',
    '#9ece6a',
    '#e0af68',
    '#7aa2f7',
    '#bb9af7',
    '#7dcfff',
    '#c0caf5',
]
cursor_bg = '#c0caf5'
cursor_border = '#c0caf5'
cursor_fg = '#15161e'
foreground = '#c0caf5'
selection_bg = '#33467c'
selection_fg = '#c0caf5'

[colors.indexed]

[metadata]
name = 'tokyonight'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
