[colors]
ansi = [
    '#000000',
    '#ff9da4',
    '#d1f1a9',
    '#ffeead',
    '#bbdaff',
    '#ebbbff',
    '#99ffff',
    '#ffffff',
]
background = '#002451'
brights = [
    '#000000',
    '#ff9da4',
    '#d1f1a9',
    '#ffeead',
    '#bbdaff',
    '#ebbbff',
    '#99ffff',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#003f8e'
foreground = '#ffffff'
selection_bg = '#003f8e'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Tomorrow Night Blue'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
