[colors]
ansi = [
    '#000000',
    '#f07178',
    '#c3e88d',
    '#ffcb6b',
    '#82aaff',
    '#c792ea',
    '#89ddff',
    '#cccccc',
]
background = '#000000'
brights = [
    '#333333',
    '#f6a9ae',
    '#dbf1ba',
    '#ffdfa6',
    '#b4ccff',
    '#ddbdf2',
    '#b8eaff',
    '#ffffff',
]
cursor_bg = '#fefefe'
cursor_border = '#fefefe'
cursor_fg = '#000000'
foreground = '#ffffff'
selection_bg = '#222222'
selection_fg = '#cccccc'

[colors.indexed]

[metadata]
name = 'UltraDark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
