[colors]
ansi = [
    '#000000',
    '#cc5555',
    '#55cc55',
    '#cdcd55',
    '#5555cc',
    '#cc55cc',
    '#7acaca',
    '#cccccc',
]
background = '#000000'
brights = [
    '#555555',
    '#ff5555',
    '#55ff55',
    '#ffff55',
    '#5555ff',
    '#ff55ff',
    '#55ffff',
    '#ffffff',
]
cursor_bg = '#53ae71'
cursor_border = '#53ae71'
cursor_fg = '#000000'
foreground = '#b3b3b3'
selection_bg = '#4d52f8'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Wez'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
