[colors]
ansi = [
    '#f0edec',
    '#a8334c',
    '#4f6c31',
    '#944927',
    '#286486',
    '#88507d',
    '#3b8992',
    '#2c363c',
]
background = '#f0edec'
brights = [
    '#cfc1ba',
    '#94253e',
    '#3f5a22',
    '#803d1c',
    '#1d5573',
    '#7b3b70',
    '#2b747c',
    '#4f5e68',
]
cursor_bg = '#2c363c'
cursor_border = '#2c363c'
cursor_fg = '#f0edec'
foreground = '#2c363c'
selection_bg = '#cbd9e3'
selection_fg = '#2c363c'

[colors.indexed]

[metadata]
name = 'zenbones_light'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
