[colors]
ansi = [
    '#1c1917',
    '#de6e7c',
    '#819b69',
    '#b77e64',
    '#6099c0',
    '#b279a7',
    '#66a5ad',
    '#b4bdc3',
]
background = '#1c1917'
brights = [
    '#403833',
    '#e8838f',
    '#8bae68',
    '#d68c67',
    '#61abda',
    '#cf86c1',
    '#65b8c1',
    '#888f94',
]
cursor_bg = '#c4cacf'
cursor_border = '#c4cacf'
cursor_fg = '#1c1917'
foreground = '#b4bdc3'
selection_bg = '#3d4042'
selection_fg = '#b4bdc3'

[colors.indexed]

[metadata]
name = 'zenbones_dark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
