[package]
name = "filesystem"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
filenamegen = "0.2"
anyhow = "1.0"
config = { path = "../../config" }
luahelper = { path = "../../luahelper" }
smol = "1.2"
