[colors]
ansi = [
    '#040404',
    '#d84a33',
    '#5da602',
    '#eebb6e',
    '#417ab3',
    '#e5c499',
    '#bdcfe5',
    '#dbded8',
]
background = '#040404'
brights = [
    '#685656',
    '#d76b42',
    '#99b52c',
    '#ffb670',
    '#97d7ef',
    '#aa7900',
    '#bdcfe5',
    '#e4d5c7',
]
cursor_bg = '#feffff'
cursor_border = '#feffff'
cursor_fg = '#000000'
foreground = '#feffff'
selection_bg = '#606060'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Adventure'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
