[colors]
ansi = [
    '#151515',
    '#ac4142',
    '#7e8e50',
    '#e5b567',
    '#6c99bb',
    '#9f4e85',
    '#7dd6cf',
    '#d0d0d0',
]
background = '#212121'
brights = [
    '#505050',
    '#ac4142',
    '#7e8e50',
    '#e5b567',
    '#6c99bb',
    '#9f4e85',
    '#7dd6cf',
    '#f5f5f5',
]
cursor_bg = '#d0d0d0'
cursor_border = '#d0d0d0'
cursor_fg = '#151515'
foreground = '#d0d0d0'
selection_bg = '#303030'
selection_fg = '#d0d0d0'

[colors.indexed]

[metadata]
name = 'Afterglow'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
