[colors]
ansi = [
    '#000000',
    '#de3e35',
    '#3f953a',
    '#d2b67c',
    '#2f5af3',
    '#950095',
    '#3f953a',
    '#bbbbbb',
]
background = '#f9f9f9'
brights = [
    '#000000',
    '#de3e35',
    '#3f953a',
    '#d2b67c',
    '#2f5af3',
    '#a00095',
    '#3f953a',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#2a2c33'
selection_bg = '#ededed'
selection_fg = '#2a2c33'

[colors.indexed]

[metadata]
name = 'AtomOneLight'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
