[colors]
ansi = [
    '#000000',
    '#fd5ff1',
    '#87c38a',
    '#ffd7b1',
    '#85befd',
    '#b9b6fc',
    '#85befd',
    '#e0e0e0',
]
background = '#161719'
brights = [
    '#000000',
    '#fd5ff1',
    '#94fa36',
    '#f5ffa8',
    '#96cbfe',
    '#b9b6fc',
    '#85befd',
    '#e0e0e0',
]
cursor_bg = '#d0d0d0'
cursor_border = '#d0d0d0'
cursor_fg = '#151515'
foreground = '#c5c8c6'
selection_bg = '#444444'
selection_fg = '#c5c8c6'

[colors.indexed]

[metadata]
name = 'Atom'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
