[colors]
ansi = [
    '#000000',
    '#ff3333',
    '#86b300',
    '#f29718',
    '#41a6d9',
    '#f07178',
    '#4dbf99',
    '#ffffff',
]
background = '#fafafa'
brights = [
    '#323232',
    '#ff6565',
    '#b8e532',
    '#ffc94a',
    '#73d8ff',
    '#ffa3aa',
    '#7ff1cb',
    '#ffffff',
]
cursor_bg = '#ff6a00'
cursor_border = '#ff6a00'
cursor_fg = '#5c6773'
foreground = '#5c6773'
selection_bg = '#f0eee4'
selection_fg = '#5c6773'

[colors.indexed]

[metadata]
name = 'ayu_light'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
