[colors]
ansi = [
    '#17141f',
    '#ff6b7f',
    '#00bd9c',
    '#e6c62f',
    '#22e8df',
    '#dc396a',
    '#56b6c2',
    '#f1f1f1',
]
background = '#191323'
brights = [
    '#495162',
    '#fe9ea1',
    '#98c379',
    '#f9e46b',
    '#91fff4',
    '#da70d6',
    '#bcf3ff',
    '#ffffff',
]
cursor_bg = '#e07d13'
cursor_border = '#e07d13'
cursor_fg = '#ffffff'
foreground = '#cccccc'
selection_bg = '#220525'
selection_fg = '#f4f4f4'

[colors.indexed]

[metadata]
name = 'Banana Blueberry'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
