[colors]
ansi = [
    '#000000',
    '#b87a7a',
    '#7ab87a',
    '#b8b87a',
    '#7a7ab8',
    '#b87ab8',
    '#7ab8b8',
    '#d9d9d9',
]
background = '#0d1926'
brights = [
    '#262626',
    '#dbbdbd',
    '#bddbbd',
    '#dbdbbd',
    '#bdbddb',
    '#dbbddb',
    '#bddbdb',
    '#ffffff',
]
cursor_bg = '#d9e6f2'
cursor_border = '#d9e6f2'
cursor_fg = '#0d1926'
foreground = '#d9e6f2'
selection_bg = '#c1ddff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Blazer'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
