[colors]
ansi = [
    '#101116',
    '#ff5680',
    '#00ff9c',
    '#fffc58',
    '#00b0ff',
    '#d57bff',
    '#76c1ff',
    '#c7c7c7',
]
background = '#101116'
brights = [
    '#686868',
    '#ff6e67',
    '#5ffa68',
    '#fffc67',
    '#6871ff',
    '#d682ec',
    '#60fdff',
    '#ffffff',
]
cursor_bg = '#76ff9f'
cursor_border = '#76ff9f'
cursor_fg = '#ffffff'
foreground = '#00a2ff'
selection_bg = '#c1deff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Blue Matrix'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
