[colors]
ansi = [
    '#0a4c62',
    '#99246e',
    '#5cb1b3',
    '#eab9a8',
    '#90a5bd',
    '#9d54a7',
    '#7e83cc',
    '#f0e8d6',
]
background = '#1c0c28'
brights = [
    '#201637',
    '#c87272',
    '#0a6c7e',
    '#7a3188',
    '#39173d',
    '#bc94b7',
    '#5e6071',
    '#0a6c7e',
]
cursor_bg = '#fcfad6'
cursor_border = '#fcfad6'
cursor_fg = '#000000'
foreground = '#babab9'
selection_bg = '#606060'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'BlueBerryPie'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
