[colors]
ansi = [
    '#373a41',
    '#d52753',
    '#23974a',
    '#df631c',
    '#275fe4',
    '#823ff1',
    '#27618d',
    '#babbc2',
]
background = '#f9f9f9'
brights = [
    '#676a77',
    '#ff6480',
    '#3cbc66',
    '#c5a332',
    '#0099e1',
    '#ce33c0',
    '#6d93bb',
    '#d3d3d3',
]
cursor_bg = '#f32759'
cursor_border = '#f32759'
cursor_fg = '#ffffff'
foreground = '#373a41'
selection_bg = '#daf0ff'
selection_fg = '#373a41'

[colors.indexed]

[metadata]
name = 'BlulocoLight'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
