[colors]
ansi = [
    '#31363b',
    '#ed1515',
    '#11d116',
    '#f67400',
    '#1d99f3',
    '#9b59b6',
    '#1abc9c',
    '#eff0f1',
]
background = '#31363b'
brights = [
    '#7f8c8d',
    '#c0392b',
    '#1cdc9a',
    '#fdbc4b',
    '#3daee9',
    '#8e44ad',
    '#16a085',
    '#fcfcfc',
]
cursor_bg = '#eff0f1'
cursor_border = '#eff0f1'
cursor_fg = '#31363b'
foreground = '#eff0f1'
selection_bg = '#eff0f1'
selection_fg = '#31363b'

[colors.indexed]

[metadata]
name = 'Breeze'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
