[colors]
ansi = [
    '#191919',
    '#ff355b',
    '#b7e876',
    '#ffc251',
    '#76d4ff',
    '#ba76e7',
    '#6cbfb5',
    '#c2c8d7',
]
background = '#191919'
brights = [
    '#191919',
    '#ff355b',
    '#b7e876',
    '#ffc251',
    '#76d5ff',
    '#ba76e7',
    '#6cbfb5',
    '#c2c8d7',
]
cursor_bg = '#f34b00'
cursor_border = '#f34b00'
cursor_fg = '#002831'
foreground = '#b3c9d7'
selection_bg = '#b3c9d7'
selection_fg = '#191919'

[colors.indexed]

[metadata]
name = 'Bright Lights'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
