[colors]
ansi = [
    '#1f1f1f',
    '#f81118',
    '#2dc55e',
    '#ecba0f',
    '#2a84d2',
    '#4e5ab7',
    '#1081d6',
    '#d6dbe5',
]
background = '#131313'
brights = [
    '#d6dbe5',
    '#de352e',
    '#1dd361',
    '#f3bd09',
    '#1081d6',
    '#5350b9',
    '#0f7ddb',
    '#ffffff',
]
cursor_bg = '#b9b9b9'
cursor_border = '#b9b9b9'
cursor_fg = '#101010'
foreground = '#d6dbe5'
selection_bg = '#1f1f1f'
selection_fg = '#d6dbe5'

[colors.indexed]

[metadata]
name = 'Brogrammer'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
