[colors]
ansi = [
    '#073642',
    '#dc322f',
    '#859900',
    '#b58900',
    '#268bd2',
    '#d33682',
    '#2aa198',
    '#eee8d5',
]
background = '#002b36'
brights = [
    '#002b36',
    '#cb4b16',
    '#586e75',
    '#657b83',
    '#839496',
    '#6c71c4',
    '#93a1a1',
    '#fdf6e3',
]
cursor_bg = '#839496'
cursor_border = '#839496'
cursor_fg = '#073642'
foreground = '#839496'
selection_bg = '#073642'
selection_fg = '#93a1a1'

[colors.indexed]

[metadata]
name = 'Builtin Solarized Dark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
