[colors]
ansi = [
    '#000000',
    '#bb0000',
    '#00bb00',
    '#bbbb00',
    '#0000bb',
    '#bb00bb',
    '#00bbbb',
    '#bbbbbb',
]
background = '#000000'
brights = [
    '#555555',
    '#ff5555',
    '#55ff55',
    '#ffff55',
    '#5555ff',
    '#ff55ff',
    '#55ffff',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#bbbbbb'
selection_bg = '#b5d5ff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Builtin Dark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
