[colors]
ansi = [
    '#000000',
    '#aa0000',
    '#00aa00',
    '#aa5500',
    '#0000aa',
    '#aa00aa',
    '#00aaaa',
    '#aaaaaa',
]
background = '#000000'
brights = [
    '#555555',
    '#ff5555',
    '#55ff55',
    '#ffff55',
    '#5555ff',
    '#ff55ff',
    '#55ffff',
    '#ffffff',
]
cursor_bg = '#b8b8b8'
cursor_border = '#b8b8b8'
cursor_fg = '#ffffff'
foreground = '#aaaaaa'
selection_bg = '#c1deff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'CGA'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
