[colors]
ansi = [
    '#080200',
    '#fa5e5b',
    '#16c98d',
    '#ffc83f',
    '#288ad6',
    '#d34590',
    '#28ddde',
    '#e7e7e7',
]
background = '#2c3643'
brights = [
    '#6f6b68',
    '#fa5e5b',
    '#16c98d',
    '#feef6d',
    '#278ad6',
    '#d34590',
    '#27dede',
    '#ffffff',
]
cursor_bg = '#b4b1b1'
cursor_border = '#b4b1b1'
cursor_fg = '#000000'
foreground = '#ffffff'
selection_bg = '#67747c'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Chester'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
