[colors]
ansi = [
    '#000000',
    '#f8282a',
    '#328a5d',
    '#fa701d',
    '#135cd0',
    '#9f00bd',
    '#33c3c1',
    '#b3b3b3',
]
background = '#ffffff'
brights = [
    '#555753',
    '#fb0416',
    '#2cc631',
    '#fdd727',
    '#1670ff',
    '#e900b0',
    '#3ad5ce',
    '#eeeeec',
]
cursor_bg = '#6fd3fc'
cursor_border = '#6fd3fc'
cursor_fg = '#ffffff'
foreground = '#262626'
selection_bg = '#6fd3fc'
selection_fg = '#041730'

[colors.indexed]

[metadata]
name = 'CLRS'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
