[colors]
ansi = [
    '#000000',
    '#c91b00',
    '#00c200',
    '#c7c400',
    '#0225c7',
    '#ca30c7',
    '#00c5c7',
    '#c7c7c7',
]
background = '#f5deb3'
brights = [
    '#686868',
    '#ff6e67',
    '#5ffa68',
    '#fffc67',
    '#6871ff',
    '#ff77ff',
    '#60fdff',
    '#ffffff',
]
cursor_bg = '#c7c7c7'
cursor_border = '#c7c7c7'
cursor_fg = '#fffc67'
foreground = '#000000'
selection_bg = '#c1deff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'coffee_theme'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
