[colors]
ansi = [
    '#000000',
    '#ff7092',
    '#00fbac',
    '#fffa6a',
    '#00bfff',
    '#df95ff',
    '#86cbfe',
    '#ffffff',
]
background = '#332a57'
brights = [
    '#000000',
    '#ff8aa4',
    '#21f6bc',
    '#fff787',
    '#1bccfd',
    '#e6aefe',
    '#99d6fc',
    '#ffffff',
]
cursor_bg = '#21f6bc'
cursor_border = '#21f6bc'
cursor_fg = '#ffffff'
foreground = '#e5e5e5'
selection_bg = '#c1deff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'cyberpunk'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
