[colors]
ansi = [
    '#091013',
    '#002e18',
    '#6fa64c',
    '#595900',
    '#00cb6b',
    '#412a4d',
    '#125459',
    '#002e19',
]
background = '#070c0e'
brights = [
    '#333333',
    '#00381d',
    '#90d762',
    '#e2e500',
    '#00ff87',
    '#412a4d',
    '#176c73',
    '#00381e',
]
cursor_bg = '#373a26'
cursor_border = '#373a26'
cursor_fg = '#00ff87'
foreground = '#28380d'
selection_bg = '#0f191c'
selection_fg = '#00ff87'

[colors.indexed]

[metadata]
name = 'darkermatrix'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
