[colors]
ansi = [
    '#000000',
    '#d70005',
    '#1cd915',
    '#d9bd26',
    '#5665ff',
    '#b052da',
    '#50d2da',
    '#e0e0e0',
]
background = '#090909'
brights = [
    '#535353',
    '#fb0007',
    '#22ff18',
    '#fedc2b',
    '#9fa9ff',
    '#e09aff',
    '#8df9ff',
    '#ffffff',
]
cursor_bg = '#d0d0d0'
cursor_border = '#d0d0d0'
cursor_fg = '#151515'
foreground = '#cdcdcd'
selection_bg = '#780002'
selection_fg = '#ececec'

[colors.indexed]

[metadata]
name = 'deep'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
