[colors]
ansi = [
    '#4d4d4d',
    '#ff2b2b',
    '#98fb98',
    '#f0e68c',
    '#cd853f',
    '#ffdead',
    '#ffa0a0',
    '#f5deb3',
]
background = '#333333'
brights = [
    '#555555',
    '#ff5555',
    '#55ff55',
    '#ffff55',
    '#87ceff',
    '#ff55ff',
    '#ffd700',
    '#ffffff',
]
cursor_bg = '#00ff00'
cursor_border = '#00ff00'
cursor_fg = '#000000'
foreground = '#ffffff'
selection_bg = '#b5d5ff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Desert'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
