[colors]
ansi = [
    '#000000',
    '#fd6209',
    '#41a83e',
    '#ffe862',
    '#989898',
    '#f8f8f8',
    '#9df39f',
    '#e8e8e7',
]
background = '#245032'
brights = [
    '#323232',
    '#ff943b',
    '#73da70',
    '#ffff94',
    '#cacaca',
    '#ffffff',
    '#cfffd1',
    '#ffffff',
]
cursor_bg = '#336442'
cursor_border = '#336442'
cursor_fg = '#f8f8f8'
foreground = '#f8f8f8'
selection_bg = '#336442'
selection_fg = '#f8f8f8'

[colors.indexed]

[metadata]
name = 'DjangoSmooth'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
