[colors]
ansi = [
    '#191919',
    '#bf091d',
    '#3d9751',
    '#f6bb34',
    '#17b2e0',
    '#7830b0',
    '#8bd2ed',
    '#ffffff',
]
background = '#262c35'
brights = [
    '#191919',
    '#bf091d',
    '#3d9751',
    '#f6bb34',
    '#17b2e0',
    '#7830b0',
    '#8bd2ed',
    '#ffffff',
]
cursor_bg = '#d9002f'
cursor_border = '#d9002f'
cursor_fg = '#ffffff'
foreground = '#ebebeb'
selection_bg = '#1a4080'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'DotGov'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
