[colors]
ansi = [
    '#000000',
    '#ff5555',
    '#50fa7b',
    '#f1fa8c',
    '#bd93f9',
    '#ff79c6',
    '#8be9fd',
    '#bbbbbb',
]
background = '#1e1f29'
brights = [
    '#555555',
    '#ff5555',
    '#50fa7b',
    '#f1fa8c',
    '#bd93f9',
    '#ff79c6',
    '#8be9fd',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#f8f8f2'
selection_bg = '#44475a'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Dracula'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
