[colors]
ansi = [
    '#1f1d27',
    '#d9393e',
    '#2dcd73',
    '#d9b76e',
    '#ffc284',
    '#de8d40',
    '#2488ff',
    '#b7a1ff',
]
background = '#1f1d27'
brights = [
    '#353147',
    '#d9393e',
    '#2dcd73',
    '#d9b76e',
    '#ffc284',
    '#de8d40',
    '#2488ff',
    '#eae5ff',
]
cursor_bg = '#ff9839'
cursor_border = '#ff9839'
cursor_fg = '#1f1d27'
foreground = '#b7a1ff'
selection_bg = '#353147'
selection_fg = '#b7a2ff'

[colors.indexed]

[metadata]
name = 'Duotone Dark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
