[colors]
ansi = [
    '#242424',
    '#d71c15',
    '#5aa513',
    '#fdb40c',
    '#063b8c',
    '#e40038',
    '#2595e1',
    '#efefef',
]
background = '#181818'
brights = [
    '#4b4b4b',
    '#fc1c18',
    '#6bc219',
    '#fec80e',
    '#0955ff',
    '#fb0050',
    '#3ea8fc',
    '#8c00ec',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#efefef'
selection_bg = '#b5d5ff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Elementary'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
