[colors]
ansi = [
    '#000000',
    '#9f0000',
    '#008b00',
    '#ffd000',
    '#0081ff',
    '#bc00ca',
    '#008b8b',
    '#bbbbbb',
]
background = '#000000'
brights = [
    '#555555',
    '#ff0000',
    '#00ee00',
    '#ffff00',
    '#0000ff',
    '#ff00ff',
    '#00cdcd',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#00a595'
selection_bg = '#00a48c'
selection_fg = '#3de1c9'

[colors.indexed]

[metadata]
name = 'ENCOM'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
