[colors]
ansi = [
    '#353535',
    '#d25252',
    '#a5c261',
    '#ffc66d',
    '#6c99bb',
    '#d197d9',
    '#bed6ff',
    '#eeeeec',
]
background = '#323232'
brights = [
    '#535353',
    '#f00c0c',
    '#c2e075',
    '#e1e48b',
    '#8ab7d9',
    '#efb5f7',
    '#dcf4ff',
    '#ffffff',
]
cursor_bg = '#d6d6d6'
cursor_border = '#d6d6d6'
cursor_fg = '#ffffff'
foreground = '#ffffff'
selection_bg = '#5b5b5b'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Espresso'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
