[colors]
ansi = [
    '#000000',
    '#cc0000',
    '#1a921c',
    '#f0e53a',
    '#0066ff',
    '#c5656b',
    '#06989a',
    '#d3d7cf',
]
background = '#2a211c'
brights = [
    '#555753',
    '#ef2929',
    '#9aff87',
    '#fffb5c',
    '#43a8ed',
    '#ff818a',
    '#34e2e2',
    '#eeeeec',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#000000'
foreground = '#b8a898'
selection_bg = '#c3dcff'
selection_fg = '#b8a898'

[colors.indexed]

[metadata]
name = 'Espresso Libre'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
