[colors]
ansi = [
    '#1d1d1d',
    '#cda074',
    '#9e744d',
    '#fecf75',
    '#720102',
    '#734c4d',
    '#979797',
    '#ffffce',
]
background = '#000000'
brights = [
    '#000000',
    '#fecea0',
    '#cc734d',
    '#fd9f4d',
    '#cb4a05',
    '#4e739f',
    '#fed04d',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#ffffce'
selection_bg = '#4e739f'
selection_fg = '#ffffce'

[colors.indexed]

[metadata]
name = 'Fahrenheit'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
