[colors]
ansi = [
    '#040303',
    '#f92672',
    '#c2ffdf',
    '#e6c000',
    '#c2ffdf',
    '#ffb8d1',
    '#c5a3ff',
    '#f8f8f0',
]
background = '#5a5475'
brights = [
    '#6090cb',
    '#ff857f',
    '#c2ffdf',
    '#ffea00',
    '#c2ffdf',
    '#ffb8d1',
    '#c5a3ff',
    '#f8f8f0',
]
cursor_bg = '#f8f8f0'
cursor_border = '#f8f8f0'
cursor_fg = '#060709'
foreground = '#f8f8f2'
selection_bg = '#8077a8'
selection_fg = '#f6e1ce'

[colors.indexed]

[metadata]
name = 'Fairyfloss'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
