[colors]
ansi = [
    '#03073c',
    '#c6004a',
    '#acf157',
    '#fecd5e',
    '#525fb8',
    '#986f82',
    '#968763',
    '#ecf0fc',
]
background = '#232537'
brights = [
    '#6c5b30',
    '#da4b8a',
    '#dbffa9',
    '#fee6a9',
    '#b2befa',
    '#fda5cd',
    '#a5bd86',
    '#f6ffec',
]
cursor_bg = '#fecd5e'
cursor_border = '#fecd5e'
cursor_fg = '#232537'
foreground = '#ecf0fe'
selection_bg = '#fcf7e9'
selection_fg = '#232537'

[colors.indexed]

[metadata]
name = 'FishTank'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
