[colors]
ansi = [
    '#1d1d19',
    '#f18339',
    '#9fd364',
    '#f4ef6d',
    '#5096be',
    '#695abc',
    '#d63865',
    '#ffffff',
]
background = '#1d1f21'
brights = [
    '#1d1d19',
    '#d22a24',
    '#a7d42c',
    '#ff8949',
    '#61b9d0',
    '#695abc',
    '#d63865',
    '#ffffff',
]
cursor_bg = '#708284'
cursor_border = '#708284'
cursor_fg = '#002831'
foreground = '#b8dbef'
selection_bg = '#2b2a24'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Flatland'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
