[colors]
ansi = [
    '#222d3f',
    '#a82320',
    '#32a548',
    '#e58d11',
    '#3167ac',
    '#781aa0',
    '#2c9370',
    '#b0b6ba',
]
background = '#002240'
brights = [
    '#212c3c',
    '#d4312e',
    '#2d9440',
    '#e5be0c',
    '#3c7dd2',
    '#8230a7',
    '#35b387',
    '#e7eced',
]
cursor_bg = '#e5be0c'
cursor_border = '#e5be0c'
cursor_fg = '#ffffff'
foreground = '#2cc55d'
selection_bg = '#792b9c'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Flat'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
