[colors]
ansi = [
    '#000000',
    '#d6262b',
    '#919c00',
    '#be8a13',
    '#4699a3',
    '#8d4331',
    '#da8213',
    '#ddc265',
]
background = '#251200'
brights = [
    '#7f6a55',
    '#e55a1c',
    '#bfc65a',
    '#ffcb1b',
    '#7cc9cf',
    '#d26349',
    '#e6a96b',
    '#ffeaa3',
]
cursor_bg = '#e5591c'
cursor_border = '#e5591c'
cursor_fg = '#000000'
foreground = '#dec165'
selection_bg = '#e5591c'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'FunForrest'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
