[colors]
ansi = [
    '#000000',
    '#f9555f',
    '#21b089',
    '#fef02a',
    '#589df6',
    '#944d95',
    '#1f9ee7',
    '#bbbbbb',
]
background = '#1d2837'
brights = [
    '#555555',
    '#fa8c8f',
    '#35bb9a',
    '#ffff55',
    '#589df6',
    '#e75699',
    '#3979bc',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#ffffff'
selection_bg = '#b5d5ff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Galaxy'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
