[colors]
ansi = [
    '#000000',
    '#f78166',
    '#56d364',
    '#e3b341',
    '#6ca4f8',
    '#db61a2',
    '#2b7489',
    '#ffffff',
]
background = '#101216'
brights = [
    '#4d4d4d',
    '#f78166',
    '#56d364',
    '#e3b341',
    '#6ca4f8',
    '#db61a2',
    '#2b7489',
    '#ffffff',
]
cursor_bg = '#c9d1d9'
cursor_border = '#c9d1d9'
cursor_fg = '#101216'
foreground = '#8b949e'
selection_bg = '#3b5070'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'GitHub Dark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
