[colors]
ansi = [
    '#2e343c',
    '#bd0f2f',
    '#35a770',
    '#fb9435',
    '#1f5872',
    '#bd2523',
    '#778397',
    '#ffffff',
]
background = '#0c1115'
brights = [
    '#404a55',
    '#bd0f2f',
    '#49e998',
    '#fddf6e',
    '#2a8bc1',
    '#ea4727',
    '#a0b6d3',
    '#ffffff',
]
cursor_bg = '#6c6c6c'
cursor_border = '#6c6c6c'
cursor_fg = '#6c6c6c'
foreground = '#ffffff'
selection_bg = '#bd2523'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Glacier'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
