[colors]
ansi = [
    '#2d283f',
    '#ed2261',
    '#1fa91b',
    '#8ddc20',
    '#487df4',
    '#8d35c9',
    '#3bdeed',
    '#9e9ea0',
]
background = '#171423'
brights = [
    '#59516a',
    '#f0729a',
    '#53aa5e',
    '#b2dc87',
    '#a9bcec',
    '#ad81c2',
    '#9de3eb',
    '#a288f7',
]
cursor_bg = '#a288f7'
cursor_border = '#a288f7'
cursor_fg = '#171422'
foreground = '#9f9fa1'
selection_bg = '#493d70'
selection_fg = '#171422'

[colors.indexed]

[metadata]
name = 'Grape'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
