[colors]
ansi = [
    '#191918',
    '#b34538',
    '#587744',
    '#d08949',
    '#206ec5',
    '#864651',
    '#ac9166',
    '#f1eee7',
]
background = '#141414'
brights = [
    '#2c2b2a',
    '#b33323',
    '#42824a',
    '#c75a22',
    '#5389c5',
    '#e795a5',
    '#ebc587',
    '#ffffff',
]
cursor_bg = '#c9c9c9'
cursor_border = '#c9c9c9'
cursor_fg = '#141414'
foreground = '#c9c9c9'
selection_bg = '#141414'
selection_fg = '#c9c9c9'

[colors.indexed]

[metadata]
name = 'Hacktober'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
