[colors]
ansi = [
    '#1b1d1e',
    '#f92672',
    '#a6e22e',
    '#fd971f',
    '#66d9ef',
    '#9e6ffe',
    '#5e7175',
    '#ccccc6',
]
background = '#121212'
brights = [
    '#505354',
    '#ff669d',
    '#beed5f',
    '#e6db74',
    '#66d9ef',
    '#9e6ffe',
    '#a3babf',
    '#f8f8f2',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#a0a0a0'
selection_bg = '#453b39'
selection_fg = '#b6bbc0'

[colors.indexed]

[metadata]
name = 'Hardcore'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
