[colors]
ansi = [
    '#1f0000',
    '#b00d0d',
    '#b00d0d',
    '#b00d0d',
    '#b00d0d',
    '#b00d0d',
    '#b00d0d',
    '#fafafa',
]
background = '#200101'
brights = [
    '#150000',
    '#ff1111',
    '#ff1010',
    '#ff1010',
    '#ff1010',
    '#ff1010',
    '#ff1010',
    '#fefefe',
]
cursor_bg = '#b00d0d'
cursor_border = '#b00d0d'
cursor_fg = '#ffffff'
foreground = '#b10e0e'
selection_bg = '#ebc1ff'
selection_fg = '#fdfdfd'

[colors.indexed]

[metadata]
name = 'HaX0R_R3D'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
