[colors]
ansi = [
    '#010921',
    '#10b6ff',
    '#10b6ff',
    '#10b6ff',
    '#10b6ff',
    '#10b6ff',
    '#10b6ff',
    '#fafafa',
]
background = '#010515'
brights = [
    '#080117',
    '#00b3f7',
    '#00b3f7',
    '#00b3f7',
    '#00b3f7',
    '#00b3f7',
    '#00b3f7',
    '#fefefe',
]
cursor_bg = '#10b6ff'
cursor_border = '#10b6ff'
cursor_fg = '#ffffff'
foreground = '#11b7ff'
selection_bg = '#c1e4ff'
selection_fg = '#f6f6f6'

[colors.indexed]

[metadata]
name = 'HaX0R_BLUE'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
