[colors]
ansi = [
    '#001f0b',
    '#15d00d',
    '#15d00d',
    '#15d00d',
    '#15d00d',
    '#15d00d',
    '#15d00d',
    '#fafafa',
]
background = '#020f01'
brights = [
    '#001510',
    '#19e20e',
    '#19e20e',
    '#19e20e',
    '#19e20e',
    '#19e20e',
    '#19e20e',
    '#fefefe',
]
cursor_bg = '#15d00d'
cursor_border = '#15d00d'
cursor_fg = '#ffffff'
foreground = '#16b10e'
selection_bg = '#d4ffc1'
selection_fg = '#fdfdfd'

[colors.indexed]

[metadata]
name = 'HaX0R_GR33N'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
