[colors]
ansi = [
    '#000000',
    '#b6214a',
    '#00a600',
    '#bfbf00',
    '#246eb2',
    '#b200b2',
    '#00a6b2',
    '#bfbfbf',
]
background = '#100b05'
brights = [
    '#666666',
    '#e50000',
    '#86a93e',
    '#e5e500',
    '#0000ff',
    '#e500e5',
    '#00e5e5',
    '#e5e5e5',
]
cursor_bg = '#23ff18'
cursor_border = '#23ff18'
cursor_fg = '#ff0018'
foreground = '#84c138'
selection_bg = '#083905'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Hipster Green'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
