[colors]
ansi = [
    '#000000',
    '#c13900',
    '#a4a900',
    '#caaf00',
    '#bd6d00',
    '#fc5e00',
    '#f79500',
    '#ffc88a',
]
background = '#262626'
brights = [
    '#6a4f2a',
    '#ff8c68',
    '#f6ff40',
    '#ffe36e',
    '#ffbe55',
    '#fc874f',
    '#c69752',
    '#fafaff',
]
cursor_bg = '#fc531d'
cursor_border = '#fc531d'
cursor_fg = '#ffc88a'
foreground = '#ffcb83'
selection_bg = '#c14020'
selection_fg = '#ffc88a'

[colors.indexed]

[metadata]
name = 'IC_Orange_PPL'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
