[colors]
ansi = [
    '#1e2132',
    '#e27878',
    '#b4be82',
    '#e2a478',
    '#84a0c6',
    '#a093c7',
    '#89b8c2',
    '#c6c8d1',
]
background = '#161821'
brights = [
    '#6b7089',
    '#e98989',
    '#c0ca8e',
    '#e9b189',
    '#91acd1',
    '#ada0d3',
    '#95c4ce',
    '#d2d4de',
]
cursor_bg = '#c6c8d1'
cursor_border = '#c6c8d1'
cursor_fg = '#161821'
foreground = '#c6c8d1'
selection_bg = '#c6c8d1'
selection_fg = '#161821'

[colors.indexed]

[metadata]
name = 'iceberg-dark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
