[colors]
ansi = [
    '#3b3750',
    '#cf7b98',
    '#90a94b',
    '#6ebfc0',
    '#576ea6',
    '#bc4f68',
    '#75a7d2',
    '#c3d3de',
]
background = '#262b33'
brights = [
    '#a874ce',
    '#de90ab',
    '#bcdd61',
    '#87e9ea',
    '#8c9fcd',
    '#e16c87',
    '#b7c9ef',
    '#d5e5f1',
]
cursor_bg = '#c3d3de'
cursor_border = '#c3d3de'
cursor_fg = '#1e1b2e'
foreground = '#c3d3de'
selection_bg = '#5b5184'
selection_fg = '#1e1b2e'

[colors.indexed]

[metadata]
name = 'jubi'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
