[colors]
ansi = [
    '#1d1a1e',
    '#ff5b82',
    '#47d7a1',
    '#e8e562',
    '#5db4ee',
    '#da6cda',
    '#57e9eb',
    '#ededed',
]
background = '#1d1a1e'
brights = [
    '#1d1a1e',
    '#ff5b82',
    '#47d7a1',
    '#e8e562',
    '#5db4ee',
    '#da6cda',
    '#57e9eb',
    '#ededed',
]
cursor_bg = '#c7c7c7'
cursor_border = '#c7c7c7'
cursor_fg = '#ffffff'
foreground = '#efecec'
selection_bg = '#e1925c'
selection_fg = '#1d1a1e'

[colors.indexed]

[metadata]
name = 'Kolorit'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
