[colors]
ansi = [
    '#435b67',
    '#fc3841',
    '#5cf19e',
    '#fed032',
    '#37b6ff',
    '#fc226e',
    '#59ffd1',
    '#ffffff',
]
background = '#1d262a'
brights = [
    '#a1b0b8',
    '#fc746d',
    '#adf7be',
    '#fee16c',
    '#70cfff',
    '#fc669b',
    '#9affe6',
    '#ffffff',
]
cursor_bg = '#eaeaea'
cursor_border = '#eaeaea'
cursor_fg = '#000000'
foreground = '#e7ebed'
selection_bg = '#4e6a78'
selection_fg = '#e7ebed'

[colors.indexed]

[metadata]
name = 'MaterialDesignColors'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
