[colors]
ansi = [
    '#546e7a',
    '#ff5370',
    '#c3e88d',
    '#ffcb6b',
    '#82aaff',
    '#c792ea',
    '#89ddff',
    '#ffffff',
]
background = '#0f111a'
brights = [
    '#546e7a',
    '#ff5370',
    '#c3e88d',
    '#ffcb6b',
    '#82aaff',
    '#c792ea',
    '#89ddff',
    '#ffffff',
]
cursor_bg = '#ffcc00'
cursor_border = '#ffcc00'
cursor_fg = '#0f111a'
foreground = '#8f93a2'
selection_bg = '#1f2233'
selection_fg = '#8f93a2'

[colors.indexed]

[metadata]
name = 'MaterialOcean'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
