[colors]
ansi = [
    '#0f191c',
    '#23755a',
    '#82d967',
    '#ffd700',
    '#3f5242',
    '#409931',
    '#50b45a',
    '#507350',
]
background = '#0f191c'
brights = [
    '#688060',
    '#2fc079',
    '#90d762',
    '#faff00',
    '#4f7e7e',
    '#11ff25',
    '#c1ff8a',
    '#678c61',
]
cursor_bg = '#384545'
cursor_border = '#384545'
cursor_fg = '#00ff00'
foreground = '#426644'
selection_bg = '#18282e'
selection_fg = '#00ff87'

[colors.indexed]

[metadata]
name = 'matrix'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
