[colors]
ansi = [
    '#000000',
    '#b64c00',
    '#7c8b16',
    '#d3bd26',
    '#616bb0',
    '#8c5a90',
    '#916c25',
    '#cac29a',
]
background = '#1d1908'
brights = [
    '#5e5219',
    '#ff9149',
    '#b2ca3b',
    '#ffe54a',
    '#acb8ff',
    '#ffa0ff',
    '#ffbc51',
    '#fed698',
]
cursor_bg = '#d3ba30'
cursor_border = '#d3ba30'
cursor_fg = '#d2bc3d'
foreground = '#cac296'
selection_bg = '#626dac'
selection_fg = '#cac29a'

[colors.indexed]

[metadata]
name = 'Medallion'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
