[colors]
ansi = [
    '#1e1e1e',
    '#ff453a',
    '#32d74b',
    '#ffd60a',
    '#0a84ff',
    '#bf5af2',
    '#5ac8fa',
    '#ffffff',
]
background = '#1e1e1e'
brights = [
    '#1e1e1e',
    '#ff453a',
    '#32d74b',
    '#ffd60a',
    '#0a84ff',
    '#bf5af2',
    '#5ac8fa',
    '#ffffff',
]
cursor_bg = '#32d74b'
cursor_border = '#32d74b'
cursor_fg = '#1c1c1c'
foreground = '#ffffff'
selection_bg = '#4a504d'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'midnight-in-mojave'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
