[colors]
ansi = [
    '#011627',
    '#ff9999',
    '#85cc95',
    '#ffd700',
    '#7fb5ff',
    '#ddb3ff',
    '#21c7a8',
    '#ffffff',
]
background = '#1b2738'
brights = [
    '#575656',
    '#ff9999',
    '#85cc95',
    '#ffd700',
    '#7fb5ff',
    '#ddb3ff',
    '#85cc95',
    '#ffffff',
]
cursor_bg = '#ddb3ff'
cursor_border = '#ddb3ff'
cursor_fg = '#ffffff'
foreground = '#a6b2c0'
selection_bg = '#273951'
selection_fg = '#d3dbe5'

[colors.indexed]

[metadata]
name = 'Mirage'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
