[colors]
ansi = [
    '#000000',
    '#ff4242',
    '#74af68',
    '#ffad29',
    '#338f86',
    '#9414e6',
    '#23d7d7',
    '#e1e1e0',
]
background = '#2d3743'
brights = [
    '#555555',
    '#ff3242',
    '#74cd68',
    '#ffb929',
    '#23d7d7',
    '#ff37ff',
    '#00ede1',
    '#ffffff',
]
cursor_bg = '#000000'
cursor_border = '#000000'
cursor_fg = '#ffffff'
foreground = '#e1e1e0'
selection_bg = '#2d37ff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Misterioso'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
