[colors]
ansi = [
    '#121212',
    '#fa2934',
    '#98e123',
    '#fff30a',
    '#0443ff',
    '#f800f8',
    '#01b6ed',
    '#ffffff',
]
background = '#121212'
brights = [
    '#838383',
    '#f6669d',
    '#b1e05f',
    '#fff26d',
    '#0443ff',
    '#f200f6',
    '#51ceff',
    '#ffffff',
]
cursor_bg = '#fb0007'
cursor_border = '#fb0007'
cursor_fg = '#ea0009'
foreground = '#f9f9f9'
selection_bg = '#ffffff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Monokai Vivid'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
