[colors]
ansi = [
    '#1a1a1a',
    '#f4005f',
    '#98e024',
    '#fd971f',
    '#9d65ff',
    '#f4005f',
    '#58d1eb',
    '#c4c5b5',
]
background = '#0c0c0c'
brights = [
    '#625e4c',
    '#f4005f',
    '#98e024',
    '#e0d561',
    '#9d65ff',
    '#f4005f',
    '#58d1eb',
    '#f6f6ef',
]
cursor_bg = '#fc971f'
cursor_border = '#fc971f'
cursor_fg = '#000000'
foreground = '#d9d9d9'
selection_bg = '#343434'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Monokai Remastered'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
