[colors]
ansi = [
    '#000000',
    '#ff3045',
    '#5ffa74',
    '#fffc7e',
    '#0208cb',
    '#f924e7',
    '#00fffc',
    '#c7c7c7',
]
background = '#14161a'
brights = [
    '#686868',
    '#ff5a5a',
    '#75ff88',
    '#fffd96',
    '#3c40cb',
    '#f15be5',
    '#88fffe',
    '#ffffff',
]
cursor_bg = '#c7c7c7'
cursor_border = '#c7c7c7'
cursor_fg = '#ffffff'
foreground = '#00fffc'
selection_bg = '#0013ff'
selection_fg = '#08d2cf'

[colors.indexed]

[metadata]
name = 'Neon'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
