[colors]
ansi = [
    '#23252b',
    '#b54036',
    '#5ab977',
    '#deb566',
    '#6a7c93',
    '#a4799d',
    '#3f94a8',
    '#e6e8ef',
]
background = '#1c1e22'
brights = [
    '#23252b',
    '#b54036',
    '#5ab977',
    '#deb566',
    '#6a7c93',
    '#a4799d',
    '#3f94a8',
    '#ebedf2',
]
cursor_bg = '#f6f7ec'
cursor_border = '#f6f7ec'
cursor_fg = '#c4c5b5'
foreground = '#e6e8ef'
selection_bg = '#2f363e'
selection_fg = '#7d8fa4'

[colors.indexed]

[metadata]
name = 'Neutron'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
