[colors]
ansi = [
    '#4c4c4c',
    '#bb0000',
    '#04f623',
    '#f3f167',
    '#64d0f0',
    '#ce6fdb',
    '#00dadf',
    '#bbbbbb',
]
background = '#171717'
brights = [
    '#555555',
    '#ff5555',
    '#7df71d',
    '#ffff55',
    '#62cbe8',
    '#ff9bf5',
    '#00ccd8',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#bbbbbb'
selection_bg = '#b5d5ff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'NightLion v2'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
