[colors]
ansi = [
    '#011627',
    '#d3423e',
    '#2aa298',
    '#daaa01',
    '#4876d6',
    '#403f53',
    '#08916a',
    '#7a8181',
]
background = '#ffffff'
brights = [
    '#7a8181',
    '#f76e6e',
    '#49d0c5',
    '#dac26b',
    '#5ca7e4',
    '#697098',
    '#00c990',
    '#989fb1',
]
cursor_bg = '#403f53'
cursor_border = '#403f53'
cursor_fg = '#fbfbfb'
foreground = '#403f53'
selection_bg = '#f2f2f2'
selection_fg = '#403f53'

[colors.indexed]

[metadata]
name = 'Night Owlish Light'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
