[colors]
ansi = [
    '#3b4252',
    '#bf616a',
    '#a3be8c',
    '#ebcb8b',
    '#81a1c1',
    '#b48ead',
    '#88c0d0',
    '#e5e9f0',
]
background = '#2e3440'
brights = [
    '#4c566a',
    '#bf616a',
    '#a3be8c',
    '#ebcb8b',
    '#81a1c1',
    '#b48ead',
    '#8fbcbb',
    '#eceff4',
]
cursor_bg = '#eceff4'
cursor_border = '#eceff4'
cursor_fg = '#282828'
foreground = '#d8dee9'
selection_bg = '#eceff4'
selection_fg = '#4c566a'

[colors.indexed]

[metadata]
name = 'nord'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
