[colors]
ansi = [
    '#000000',
    '#cc0000',
    '#009600',
    '#d06b00',
    '#0000cc',
    '#cc00cc',
    '#0087cc',
    '#cccccc',
]
background = '#dfdbc3'
brights = [
    '#808080',
    '#cc0000',
    '#009600',
    '#d06b00',
    '#0000cc',
    '#cc00cc',
    '#0087cc',
    '#ffffff',
]
cursor_bg = '#73635a'
cursor_border = '#73635a'
cursor_fg = '#000000'
foreground = '#3b2322'
selection_bg = '#a4a390'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Novel'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
