[colors]
ansi = [
    '#000000',
    '#990000',
    '#00a600',
    '#999900',
    '#0000b2',
    '#b200b2',
    '#00a6b2',
    '#bfbfbf',
]
background = '#224fbc'
brights = [
    '#666666',
    '#e50000',
    '#00d900',
    '#e5e500',
    '#0000ff',
    '#e500e5',
    '#00e5e5',
    '#e5e5e5',
]
cursor_bg = '#7f7f7f'
cursor_border = '#7f7f7f'
cursor_fg = '#ffffff'
foreground = '#ffffff'
selection_bg = '#216dff'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Ocean'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
