[colors]
ansi = [
    '#121c21',
    '#e44754',
    '#89bd82',
    '#f7bd51',
    '#5486c0',
    '#b77eb8',
    '#50a5a4',
    '#ffffff',
]
background = '#121b21'
brights = [
    '#52606b',
    '#e44754',
    '#89bd82',
    '#f7bd51',
    '#5486c0',
    '#b77eb8',
    '#50a5a4',
    '#ffffff',
]
cursor_bg = '#b3b8c3'
cursor_border = '#b3b8c3'
cursor_fg = '#121c21'
foreground = '#b3b8c3'
selection_bg = '#3e4953'
selection_fg = '#b3b8c3'

[colors.indexed]

[metadata]
name = 'Oceanic-Next'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
