[colors]
ansi = [
    '#0a1222',
    '#ffa7c4',
    '#85cc95',
    '#ffcb8b',
    '#8dabe1',
    '#c792eb',
    '#78ccf0',
    '#ffffff',
]
background = '#0e1729'
brights = [
    '#575656',
    '#ffa7c4',
    '#85cc95',
    '#ffcb8b',
    '#8dabe1',
    '#c792eb',
    '#ffa7c4',
    '#ffffff',
]
cursor_bg = '#ffa7c4'
cursor_border = '#ffa7c4'
cursor_fg = '#ffffff'
foreground = '#ced2d6'
selection_bg = '#1f2b41'
selection_fg = '#ced2d6'

[colors.indexed]

[metadata]
name = 'Overnight Slumber'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
