[colors]
ansi = [
    '#000000',
    '#f07178',
    '#c3e88d',
    '#ffcb6b',
    '#82aaff',
    '#c792ea',
    '#89ddff',
    '#ffffff',
]
background = '#3e4251'
brights = [
    '#666666',
    '#f6a9ae',
    '#dbf1ba',
    '#ffdfa6',
    '#b4ccff',
    '#ddbdf2',
    '#b8eaff',
    '#999999',
]
cursor_bg = '#ffcb6b'
cursor_border = '#ffcb6b'
cursor_fg = '#323232'
foreground = '#cccccc'
selection_bg = '#717cb4'
selection_fg = '#80cbc4'

[colors.indexed]

[metadata]
name = 'PaleNightHC'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
