[colors]
ansi = [
    '#2f1e2e',
    '#ef6155',
    '#48b685',
    '#fec418',
    '#06b6ef',
    '#815ba4',
    '#5bc4bf',
    '#a39e9b',
]
background = '#2f1e2e'
brights = [
    '#776e71',
    '#ef6155',
    '#48b685',
    '#fec418',
    '#06b6ef',
    '#815ba4',
    '#5bc4bf',
    '#e7e9db',
]
cursor_bg = '#a39e9b'
cursor_border = '#a39e9b'
cursor_fg = '#2f1e2e'
foreground = '#a39e9b'
selection_bg = '#4f424c'
selection_fg = '#a39e9b'

[colors.indexed]

[metadata]
name = 'Paraiso Dark'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
