[colors]
ansi = [
    '#2a2a2a',
    '#ff0000',
    '#79ff0f',
    '#e7bf00',
    '#396bd7',
    '#b449be',
    '#66ccff',
    '#bbbbbb',
]
background = '#000000'
brights = [
    '#666666',
    '#ff0080',
    '#66ff66',
    '#f3d64e',
    '#709aed',
    '#db67e6',
    '#7adff2',
    '#ffffff',
]
cursor_bg = '#4d4d4d'
cursor_border = '#4d4d4d'
cursor_fg = '#ffffff'
foreground = '#f2f2f2'
selection_bg = '#414141'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'PaulMillr'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
