[colors]
ansi = [
    '#1d2021',
    '#cc241d',
    '#98971a',
    '#d79921',
    '#458588',
    '#b16286',
    '#689d6a',
    '#a89984',
]
background = '#181921'
brights = [
    '#928374',
    '#f42c3e',
    '#b8bb26',
    '#fabd2f',
    '#99c6ca',
    '#d3869b',
    '#7ec16e',
    '#ebdbb2',
]
cursor_bg = '#c7c7c7'
cursor_border = '#c7c7c7'
cursor_fg = '#ffffff'
foreground = '#ebdbb2'
selection_bg = '#ebdbb2'
selection_fg = '#928374'

[colors.indexed]

[metadata]
name = 'Popping and Locking'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
