[colors]
ansi = [
    '#0a0520',
    '#ff796d',
    '#99b481',
    '#efdfac',
    '#66d9ef',
    '#e78fcd',
    '#ba8cff',
    '#ffba81',
]
background = '#2a1a4a'
brights = [
    '#100b23',
    '#f99f92',
    '#b4be8f',
    '#f2e9bf',
    '#79daed',
    '#ba91d4',
    '#a0a0d6',
    '#b9aed3',
]
cursor_bg = '#c7c7c7'
cursor_border = '#c7c7c7'
cursor_fg = '#ffffff'
foreground = '#ece7fa'
selection_bg = '#8689c2'
selection_fg = '#271c50'

[colors.indexed]

[metadata]
name = 'purplepeter'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
