[colors]
ansi = [
    '#000000',
    '#ff260e',
    '#9be205',
    '#ffc400',
    '#00a2fa',
    '#815bb5',
    '#00deef',
    '#ffffff',
]
background = '#21084a'
brights = [
    '#565656',
    '#ff4250',
    '#b8e36e',
    '#ffd852',
    '#00a6ff',
    '#ac7bf0',
    '#74fdf3',
    '#ffffff',
]
cursor_bg = '#ff271d'
cursor_border = '#ff271d'
cursor_fg = '#ff271d'
foreground = '#fffbf6'
selection_bg = '#287691'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Purple Rain'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
