[colors]
ansi = [
    '#000000',
    '#fc644d',
    '#7afde1',
    '#fff09b',
    '#6c9bf5',
    '#ff4fa1',
    '#64e0ff',
    '#c0c9e5',
]
background = '#111e2a'
brights = [
    '#304b66',
    '#fc644d',
    '#7afde1',
    '#fff09b',
    '#6c9bf5',
    '#ff4fa1',
    '#64e0ff',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#111e2a'
foreground = '#c0c9e5'
selection_bg = '#304b66'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Rapture'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
