[colors]
ansi = [
    '#000000',
    '#b12424',
    '#006b4f',
    '#f8a300',
    '#138af2',
    '#9a1b6e',
    '#3eb8bf',
    '#ffffff',
]
background = '#ffffff'
brights = [
    '#000000',
    '#b12424',
    '#006b4f',
    '#f8a300',
    '#138af2',
    '#9a1b6e',
    '#3eb8bf',
    '#ffffff',
]
cursor_bg = '#000000'
cursor_border = '#000000'
cursor_fg = '#000000'
foreground = '#000000'
selection_bg = '#e5e5e5'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Raycast_Light'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
