[colors]
ansi = [
    '#202020',
    '#8c3432',
    '#728271',
    '#e8bf6a',
    '#69819e',
    '#896492',
    '#5b8390',
    '#b9aa99',
]
background = '#222222'
brights = [
    '#676767',
    '#b55242',
    '#869985',
    '#ebeb91',
    '#60827e',
    '#de4974',
    '#38add8',
    '#d6bfb8',
]
cursor_bg = '#c2b790'
cursor_border = '#c2b790'
cursor_fg = '#202020'
foreground = '#c2b790'
selection_bg = '#1b324a'
selection_fg = '#bcb291'

[colors.indexed]

[metadata]
name = 'Red Planet'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
