[colors]
ansi = [
    '#151515',
    '#bc5653',
    '#909d63',
    '#ebc17a',
    '#6a8799',
    '#b06698',
    '#c9dfff',
    '#d9d9d9',
]
background = '#353a44'
brights = [
    '#636363',
    '#bc5653',
    '#a0ac77',
    '#ebc17a',
    '#7eaac7',
    '#b06698',
    '#acbbd0',
    '#f7f7f7',
]
cursor_bg = '#d9d9d9'
cursor_border = '#d9d9d9'
cursor_fg = '#1b1b1b'
foreground = '#d9d9d9'
selection_bg = '#6a7985'
selection_fg = '#d9d9d9'

[colors.indexed]

[metadata]
name = 'Relaxed'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
