[colors]
ansi = [
    '#2c3941',
    '#865f5b',
    '#66907d',
    '#b1a990',
    '#6a8e95',
    '#b18a73',
    '#88b2ac',
    '#ececec',
]
background = '#2c3941'
brights = [
    '#5d7079',
    '#865f5b',
    '#66907d',
    '#b1a990',
    '#6a8e95',
    '#b18a73',
    '#88b2ac',
    '#ececec',
]
cursor_bg = '#ececec'
cursor_border = '#ececec'
cursor_fg = '#002831'
foreground = '#ececec'
selection_bg = '#002831'
selection_fg = '#819090'

[colors.indexed]

[metadata]
name = 'Ryuuko'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
