[colors]
ansi = [
    '#000000',
    '#d52370',
    '#41af1a',
    '#bc7053',
    '#6964ab',
    '#c71fbf',
    '#939393',
    '#998eac',
]
background = '#18131e'
brights = [
    '#786d69',
    '#f41d99',
    '#22e529',
    '#f59574',
    '#9892f1',
    '#e90cdd',
    '#eeeeee',
    '#cbb6ff',
]
cursor_bg = '#ff65fd'
cursor_border = '#ff65fd'
cursor_fg = '#24242e'
foreground = '#dd7bdc'
selection_bg = '#c05cbf'
selection_fg = '#24242e'

[colors.indexed]

[metadata]
name = 'Sakura'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
