[colors]
ansi = [
    '#101116',
    '#ff0051',
    '#00dc84',
    '#faf945',
    '#0271b6',
    '#ca30c7',
    '#00c5c7',
    '#c7c7c7',
]
background = '#1c153d'
brights = [
    '#686868',
    '#ff6e67',
    '#5ffa68',
    '#fffc67',
    '#6871ff',
    '#bd35ec',
    '#60fdff',
    '#ffffff',
]
cursor_bg = '#76ff9f'
cursor_border = '#76ff9f'
cursor_fg = '#ffffff'
foreground = '#e41951'
selection_bg = '#c1deff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Scarlet Protocol'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
