[colors]
ansi = [
    '#323232',
    '#c22832',
    '#8ec43d',
    '#e0c64f',
    '#43a5d5',
    '#8b57b5',
    '#8ec43d',
    '#eeeeee',
]
background = '#111213'
brights = [
    '#323232',
    '#c22832',
    '#8ec43d',
    '#e0c64f',
    '#43a5d5',
    '#8b57b5',
    '#8ec43d',
    '#ffffff',
]
cursor_bg = '#e3bf21'
cursor_border = '#e3bf21'
cursor_fg = '#e0be2e'
foreground = '#cacecd'
selection_bg = '#303233'
selection_fg = '#cacecd'

[colors.indexed]

[metadata]
name = 'Seti'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
