[colors]
ansi = [
    '#000000',
    '#d90429',
    '#3ad900',
    '#ffe700',
    '#6943ff',
    '#ff2c70',
    '#00c5c7',
    '#c7c7c7',
]
background = '#1e1d40'
brights = [
    '#686868',
    '#f92a1c',
    '#43d426',
    '#f1d000',
    '#6871ff',
    '#ff77ff',
    '#79e8fb',
    '#ffffff',
]
cursor_bg = '#fad000'
cursor_border = '#fad000'
cursor_fg = '#fefff4'
foreground = '#ffffff'
selection_bg = '#b362ff'
selection_fg = '#c2c2c2'

[colors.indexed]

[metadata]
name = 'shades-of-purple'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
