[colors]
ansi = [
    '#000000',
    '#fc4346',
    '#50fb7c',
    '#f0fb8c',
    '#49baff',
    '#fc4cb4',
    '#8be9fe',
    '#ededec',
]
background = '#1e1f29'
brights = [
    '#555555',
    '#fc4346',
    '#50fb7c',
    '#f0fb8c',
    '#49baff',
    '#fc4cb4',
    '#8be9fe',
    '#ededec',
]
cursor_bg = '#e4e4e4'
cursor_border = '#e4e4e4'
cursor_fg = '#f6f6f6'
foreground = '#ebece6'
selection_bg = '#81aec6'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Snazzy'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
