[colors]
ansi = [
    '#002831',
    '#d11c24',
    '#6cbe6c',
    '#a57706',
    '#2176c7',
    '#c61c6f',
    '#259286',
    '#eae3cb',
]
background = '#001e27'
brights = [
    '#006488',
    '#f5163b',
    '#51ef84',
    '#b27e28',
    '#178ec8',
    '#e24d8e',
    '#00b39e',
    '#fcf4dc',
]
cursor_bg = '#f34b00'
cursor_border = '#f34b00'
cursor_fg = '#002831'
foreground = '#9cc2c3'
selection_bg = '#003748'
selection_fg = '#7a8f8e'

[colors.indexed]

[metadata]
name = 'Solarized Dark Higher Contrast'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
