[colors]
ansi = [
    '#002831',
    '#d11c24',
    '#738a05',
    '#a57706',
    '#2176c7',
    '#c61c6f',
    '#259286',
    '#eae3cb',
]
background = '#001e27'
brights = [
    '#475b62',
    '#bd3613',
    '#475b62',
    '#536870',
    '#708284',
    '#5956ba',
    '#819090',
    '#fcf4dc',
]
cursor_bg = '#708284'
cursor_border = '#708284'
cursor_fg = '#002831'
foreground = '#708284'
selection_bg = '#002831'
selection_fg = '#819090'

[colors.indexed]

[metadata]
name = 'Solarized Dark - Patched'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
