[colors]
ansi = [
    '#25292a',
    '#f24840',
    '#629655',
    '#b68800',
    '#2075c7',
    '#797fd4',
    '#15968d',
    '#d2d8d9',
]
background = '#3d3f41'
brights = [
    '#25292a',
    '#f24840',
    '#629655',
    '#b68800',
    '#2075c7',
    '#797fd4',
    '#15968d',
    '#d2d8d9',
]
cursor_bg = '#708284'
cursor_border = '#708284'
cursor_fg = '#002831'
foreground = '#d2d8d9'
selection_bg = '#214283'
selection_fg = '#d2d8d9'

[colors.indexed]

[metadata]
name = 'Solarized Darcula'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
