[colors]
ansi = [
    '#000000',
    '#b04b57',
    '#87b379',
    '#e5c179',
    '#7d8fa4',
    '#a47996',
    '#85a7a5',
    '#b3b8c3',
]
background = '#20242d'
brights = [
    '#000000',
    '#b04b57',
    '#87b379',
    '#e5c179',
    '#7d8fa4',
    '#a47996',
    '#85a7a5',
    '#ffffff',
]
cursor_bg = '#b3b8c3'
cursor_border = '#b3b8c3'
cursor_fg = '#1d1f21'
foreground = '#b3b8c3'
selection_bg = '#16181e'
selection_fg = '#b3b8c3'

[colors.indexed]

[metadata]
name = 'SpaceGray'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
