[colors]
ansi = [
    '#15171c',
    '#b24a56',
    '#92b477',
    '#c6735a',
    '#7c8fa5',
    '#a5789e',
    '#80cdcb',
    '#b3b8c3',
]
background = '#222222'
brights = [
    '#555555',
    '#ec5f67',
    '#89e986',
    '#fec254',
    '#5486c0',
    '#bf83c1',
    '#58c2c1',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#c9c6bc'
selection_bg = '#272e36'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'SpaceGray Eighties Dull'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
