[colors]
ansi = [
    '#6e5346',
    '#e35b00',
    '#5cab96',
    '#e3cd7b',
    '#0f548b',
    '#e35b00',
    '#06afc7',
    '#f0f1ce',
]
background = '#0a1e24'
brights = [
    '#684c31',
    '#ff8a3a',
    '#aecab8',
    '#ffc878',
    '#67a0ce',
    '#ff8a3a',
    '#83a7b4',
    '#fefff1',
]
cursor_bg = '#708284'
cursor_border = '#708284'
cursor_fg = '#002831'
foreground = '#ecf0c1'
selection_bg = '#0a385c'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Spacedust'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
