[colors]
ansi = [
    '#7f7f7f',
    '#e15a60',
    '#a9cfa4',
    '#ffe2a9',
    '#6699cc',
    '#f1a5ab',
    '#5fb3b3',
    '#d4d4d4',
]
background = '#282c35'
brights = [
    '#7f7f7f',
    '#e15a60',
    '#a9cfa4',
    '#ffe2a9',
    '#6699cc',
    '#f1a5ab',
    '#5fb3b3',
    '#d4d4d4',
]
cursor_bg = '#c7c7c7'
cursor_border = '#c7c7c7'
cursor_fg = '#ffffff'
foreground = '#d4d4d4'
selection_bg = '#484e5b'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Subliminal'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
