[colors]
ansi = [
    '#302b2a',
    '#a7463d',
    '#587744',
    '#9d602a',
    '#485b98',
    '#864651',
    '#9c814f',
    '#c9c9c9',
]
background = '#1a1818'
brights = [
    '#4d4e48',
    '#aa000c',
    '#128c21',
    '#fc6a21',
    '#7999f7',
    '#fd8aa1',
    '#fad484',
    '#ffffff',
]
cursor_bg = '#ffffff'
cursor_border = '#ffffff'
cursor_fg = '#191717'
foreground = '#c9c9c9'
selection_bg = '#302b2a'
selection_fg = '#c9c9c9'

[colors.indexed]

[metadata]
name = 'Sundried'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
