[colors]
ansi = [
    '#000000',
    '#dc322f',
    '#56db3a',
    '#ff8400',
    '#0084d4',
    '#b729d9',
    '#ccccff',
    '#ffffff',
]
background = '#000000'
brights = [
    '#1b1d21',
    '#dc322f',
    '#56db3a',
    '#ff8400',
    '#0084d4',
    '#b729d9',
    '#ccccff',
    '#ffffff',
]
cursor_bg = '#dc322f'
cursor_border = '#dc322f'
cursor_fg = '#ffffff'
foreground = '#ffffff'
selection_bg = '#073642'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Symfonic'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
