[colors]
ansi = [
    '#fefefe',
    '#f97e72',
    '#72f1b8',
    '#fede5d',
    '#6d77b3',
    '#c792ea',
    '#f772e0',
    '#fefefe',
]
background = '#2a2139'
brights = [
    '#fefefe',
    '#f88414',
    '#72f1b8',
    '#fff951',
    '#36f9f6',
    '#e1acff',
    '#f92aad',
    '#fefefe',
]
cursor_bg = '#72f1b8'
cursor_border = '#72f1b8'
cursor_fg = '#1a1a1a'
foreground = '#f0eff1'
selection_bg = '#181521'
selection_fg = '#f0eff1'

[colors.indexed]

[metadata]
name = 'synthwave-everything'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
