[colors]
ansi = [
    '#000000',
    '#ff0000',
    '#59d600',
    '#f0cb00',
    '#00a2ff',
    '#c17ecc',
    '#00d0d6',
    '#e6ebe1',
]
background = '#ffffff'
brights = [
    '#8f928b',
    '#ff0013',
    '#93ff00',
    '#fff121',
    '#88c9ff',
    '#e9a7e1',
    '#00feff',
    '#f6f6f4',
]
cursor_bg = '#000000'
cursor_border = '#000000'
cursor_fg = '#ffffff'
foreground = '#000000'
selection_bg = '#c1deff'
selection_fg = '#000000'

[colors.indexed]

[metadata]
name = 'Tango Adapted'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
