[colors]
ansi = [
    '#1b1d1e',
    '#269d1b',
    '#13ce30',
    '#63e457',
    '#2525f5',
    '#641f74',
    '#378ca9',
    '#d9d8d1',
]
background = '#1b1d1e'
brights = [
    '#505354',
    '#8dff2a',
    '#48ff77',
    '#3afe16',
    '#506b95',
    '#72589d',
    '#4085a6',
    '#e5e6e1',
]
cursor_bg = '#16b61b'
cursor_border = '#16b61b'
cursor_fg = '#000000'
foreground = '#b5b5b5'
selection_bg = '#4d504c'
selection_fg = '#0b6309'

[colors.indexed]

[metadata]
name = 'The Hulk'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
