[colors]
ansi = [
    '#1d1d26',
    '#ff3399',
    '#00d364',
    '#ffcc66',
    '#00cbff',
    '#cc66ff',
    '#00ceca',
    '#cbcbf0',
]
background = '#f8f8ff'
brights = [
    '#636667',
    '#ff2f92',
    '#00d364',
    '#ffd479',
    '#00cbff',
    '#d783ff',
    '#00d5d4',
    '#d5d6f3',
]
cursor_bg = '#cbcbf0'
cursor_border = '#cbcbf0'
cursor_fg = '#ffffff'
foreground = '#1d1d26'
selection_bg = '#ff3399'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Tinacious Design (Light)'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
