[colors]
ansi = [
    '#000000',
    '#c82829',
    '#718c00',
    '#eab700',
    '#4271ae',
    '#8959a8',
    '#3e999f',
    '#ffffff',
]
background = '#ffffff'
brights = [
    '#000000',
    '#c82829',
    '#718c00',
    '#eab700',
    '#4271ae',
    '#8959a8',
    '#3e999f',
    '#ffffff',
]
cursor_bg = '#4d4d4c'
cursor_border = '#4d4d4c'
cursor_fg = '#ffffff'
foreground = '#4d4d4c'
selection_bg = '#d6d6d6'
selection_fg = '#4d4d4c'

[colors.indexed]

[metadata]
name = 'Tomorrow'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
