[colors]
ansi = [
    '#000000',
    '#cc6666',
    '#b5bd68',
    '#f0c674',
    '#81a2be',
    '#b294bb',
    '#8abeb7',
    '#ffffff',
]
background = '#1d1f21'
brights = [
    '#000000',
    '#cc6666',
    '#b5bd68',
    '#f0c674',
    '#81a2be',
    '#b294bb',
    '#8abeb7',
    '#ffffff',
]
cursor_bg = '#c5c8c6'
cursor_border = '#c5c8c6'
cursor_fg = '#1d1f21'
foreground = '#c5c8c6'
selection_bg = '#373b41'
selection_fg = '#c5c8c6'

[colors.indexed]

[metadata]
name = 'Tomorrow Night'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
