[colors]
ansi = [
    '#000000',
    '#d54e53',
    '#b9ca4a',
    '#e7c547',
    '#7aa6da',
    '#c397d8',
    '#70c0b1',
    '#ffffff',
]
background = '#000000'
brights = [
    '#000000',
    '#d54e53',
    '#b9ca4a',
    '#e7c547',
    '#7aa6da',
    '#c397d8',
    '#70c0b1',
    '#ffffff',
]
cursor_bg = '#eaeaea'
cursor_border = '#eaeaea'
cursor_fg = '#000000'
foreground = '#eaeaea'
selection_bg = '#424242'
selection_fg = '#eaeaea'

[colors.indexed]

[metadata]
name = 'Tomorrow Night Bright'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
