[colors]
ansi = [
    '#000000',
    '#f2777a',
    '#99cc99',
    '#ffcc66',
    '#6699cc',
    '#cc99cc',
    '#66cccc',
    '#ffffff',
]
background = '#2d2d2d'
brights = [
    '#000000',
    '#f2777a',
    '#99cc99',
    '#ffcc66',
    '#6699cc',
    '#cc99cc',
    '#66cccc',
    '#ffffff',
]
cursor_bg = '#cccccc'
cursor_border = '#cccccc'
cursor_fg = '#2d2d2d'
foreground = '#cccccc'
selection_bg = '#515151'
selection_fg = '#cccccc'

[colors.indexed]

[metadata]
name = 'Tomorrow Night Eighties'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
