[colors]
ansi = [
    '#2c3f58',
    '#be2d26',
    '#1a9172',
    '#db8e27',
    '#325d96',
    '#8a5edc',
    '#35a08f',
    '#23d183',
]
background = '#24364b'
brights = [
    '#336889',
    '#dd5944',
    '#31d07b',
    '#e7d84b',
    '#34a6da',
    '#ae6bdc',
    '#42c3ae',
    '#d5d5d5',
]
cursor_bg = '#d5d5d5'
cursor_border = '#d5d5d5'
cursor_fg = '#141c25'
foreground = '#31d07b'
selection_bg = '#5f217a'
selection_fg = '#d5d5d5'

[colors.indexed]

[metadata]
name = 'ToyChest'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
