[colors]
ansi = [
    '#022026',
    '#b2302d',
    '#00a941',
    '#59819c',
    '#459a86',
    '#00599d',
    '#5d7e19',
    '#405555',
]
background = '#011116'
brights = [
    '#384451',
    '#ff4242',
    '#2aea5e',
    '#8ed4fd',
    '#61d5ba',
    '#1298ff',
    '#98d028',
    '#58fbd6',
]
cursor_bg = '#4afcd6'
cursor_border = '#4afcd6'
cursor_fg = '#031413'
foreground = '#ffffff'
selection_bg = '#415555'
selection_fg = '#4dffda'

[colors.indexed]

[metadata]
name = 'UnderTheSea'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
