[colors]
ansi = [
    '#0c0c0c',
    '#a80f20',
    '#bafc8b',
    '#eedf4b',
    '#145fcd',
    '#ff36a2',
    '#6bd1bc',
    '#e2d7e1',
]
background = '#ff8cd9'
brights = [
    '#434343',
    '#d91329',
    '#d3ffaf',
    '#ffef50',
    '#0075ea',
    '#fdd5e5',
    '#79ecd5',
    '#fff3fe',
]
cursor_bg = '#bafc8b'
cursor_border = '#bafc8b'
cursor_fg = '#202020'
foreground = '#0b0b0b'
selection_bg = '#3ea9fe'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Unikitty'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
