[colors]
ansi = [
    '#56595c',
    '#c94c22',
    '#85981c',
    '#b4881d',
    '#2e8bce',
    '#d13a82',
    '#32a198',
    '#d3d0c9',
]
background = '#fcf4dc'
brights = [
    '#45484b',
    '#bd3613',
    '#738a04',
    '#a57705',
    '#2176c7',
    '#c61c6f',
    '#259286',
    '#c9c6bd',
]
cursor_bg = '#536870'
cursor_border = '#536870'
cursor_fg = '#fcf4dc'
foreground = '#536870'
selection_bg = '#595ab7'
selection_fg = '#fcf4dc'

[colors.indexed]

[metadata]
name = 'Violet Light'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
