[colors]
ansi = [
    '#000000',
    '#e24346',
    '#39b13a',
    '#dae145',
    '#4261c5',
    '#f920fb',
    '#2abbd4',
    '#d0b8a3',
]
background = '#404040'
brights = [
    '#fefcfc',
    '#e97071',
    '#9cc090',
    '#ddda7a',
    '#7b91d6',
    '#f674ba',
    '#5ed1e5',
    '#d8c8bb',
]
cursor_bg = '#30ff24'
cursor_border = '#30ff24'
cursor_fg = '#3eef37'
foreground = '#afdab6'
selection_bg = '#b0ad21'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'WarmNeon'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
