[colors]
ansi = [
    '#535178',
    '#ef6487',
    '#5eca89',
    '#fdd877',
    '#65aef7',
    '#aa7ff0',
    '#43c1be',
    '#ffffff',
]
background = '#29283b'
brights = [
    '#535178',
    '#ef6487',
    '#5eca89',
    '#fdd877',
    '#65aef7',
    '#aa7ff0',
    '#43c1be',
    '#ffffff',
]
cursor_bg = '#b3b0d6'
cursor_border = '#b3b0d6'
cursor_fg = '#535178'
foreground = '#b3b0d6'
selection_bg = '#3d3c58'
selection_fg = '#ffffff'

[colors.indexed]

[metadata]
name = 'Whimsy'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
