[colors]
ansi = [
    '#000507',
    '#d94085',
    '#2ab250',
    '#ffd16f',
    '#883cdc',
    '#ececec',
    '#c1b8b7',
    '#fff8de',
]
background = '#1f1726'
brights = [
    '#009cc9',
    '#da6bac',
    '#f4dca5',
    '#eac066',
    '#308cba',
    '#ae636b',
    '#ff919d',
    '#e4838d',
]
cursor_bg = '#dd00ff'
cursor_border = '#dd00ff'
cursor_fg = '#ff00fe'
foreground = '#dafaff'
selection_bg = '#002831'
selection_fg = '#e4ffff'

[colors.indexed]

[metadata]
name = 'WildCherry'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
