[colors]
ansi = [
    '#000000',
    '#ff615a',
    '#b1e969',
    '#ebd99c',
    '#5da9f6',
    '#e86aff',
    '#82fff7',
    '#dedacf',
]
background = '#171717'
brights = [
    '#313131',
    '#f58c80',
    '#ddf88f',
    '#eee5b2',
    '#a5c7ff',
    '#ddaaff',
    '#b7fff9',
    '#ffffff',
]
cursor_bg = '#bbbbbb'
cursor_border = '#bbbbbb'
cursor_fg = '#ffffff'
foreground = '#dedacf'
selection_bg = '#453b39'
selection_fg = '#b6bbc0'

[colors.indexed]

[metadata]
name = 'Wombat'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
