[colors]
ansi = [
    '#4d4d4d',
    '#705050',
    '#60b48a',
    '#f0dfaf',
    '#506070',
    '#dc8cc3',
    '#8cd0d3',
    '#dcdccc',
]
background = '#3f3f3f'
brights = [
    '#709080',
    '#dca3a3',
    '#c3bf9f',
    '#e0cf9f',
    '#94bff3',
    '#ec93d3',
    '#93e0e3',
    '#ffffff',
]
cursor_bg = '#73635a'
cursor_border = '#73635a'
cursor_fg = '#000000'
foreground = '#dcdccc'
selection_bg = '#21322f'
selection_fg = '#c2d87a'

[colors.indexed]

[metadata]
name = 'Zenburn'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
