[colors]
ansi = [
    '#404040',
    '#e3716e',
    '#819b69',
    '#b77e64',
    '#6099c0',
    '#b279a7',
    '#66a5ad',
    '#f0e4cf',
]
background = '#404040'
brights = [
    '#625a5b',
    '#ec8685',
    '#8bae68',
    '#d68c67',
    '#61abda',
    '#cf86c1',
    '#65b8c1',
    '#c0ab86',
]
cursor_bg = '#f3eadb'
cursor_border = '#f3eadb'
cursor_fg = '#404040'
foreground = '#f0e4cf'
selection_bg = '#746956'
selection_fg = '#f0e4cf'

[colors.indexed]

[metadata]
name = 'zenburned'
origin_url = 'https://github.com/mbadolato/iTerm2-Color-Schemes'
