[package]
name = "zf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]
path = "src/lib.rs"

[dependencies]
anyhow = { workspace = true, version = "1.0.65"}
gdnative = { git = "https://github.com/Bromeon/godot-rust.git" }
nu-ansi-term = "0.46"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

zf-runtime = { path = "../zf-runtime" }
zf-bridge = { path = "../zf-bridge" }