#!/usr/bin/env sh
# cat crates/zf-term/src/weclome.txt | lolcat -t -f | tee /dev/tty > crates/zf-term/src/weclome.ansi
cargo r --release -p zf-runtime -- "help commands | get name | str join $'(char nl)'" > crates/zf-runtime/src/cmds.txt