[package]
name = "zf-ffi"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bincode = "2.0.0-rc.2"
gdnative = { workspace = true, optional = true }

[features]
godot = ["dep:gdnative"]