name: termwiz

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".cirrus.yml"
      - "docs/*"
      - "ci/build-docs.sh"
      - "ci/generate-docs.py"
      - "ci/subst-release-info.py"
      - ".github/workflows/pages.yml"
      - ".github/workflows/verify-pages.yml"
      - ".github/ISSUE_TEMPLATE/*"
      - "**/*.md"
  push:
    branches:
      - main
    paths-ignore:
      - ".cirrus.yml"
      - "docs/**"
      - "ci/build-docs.sh"
      - "ci/generate-docs.py"
      - "ci/subst-release-info.py"
      - ".github/workflows/pages.yml"
      - ".github/workflows/verify-pages.yml"
      - ".github/ISSUE_TEMPLATE/*"
      - "**/*.md"

jobs:
  build-termwiz-all-features:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Install Rust"
        uses: actions-rs/toolchain@v1
        with:
          profile: "minimal"
          toolchain: "stable"
          override: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: Build
        run: |
          source $HOME/.cargo/env
          cargo build -p termwiz --all-features
          cargo test -p termwiz --all-features

  fuzz-termwiz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: "Install Rust"
        uses: actions-rs/toolchain@v1
        with:
          profile: "minimal"
          toolchain: "nightly"
          override: true
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
      - name: "Cache cargo"
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: "ubuntu-latest-termwiz-fuzz-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}-cargo"
      - name: Install fuzzer
        run: |
          source $HOME/.cargo/env
          cargo install cargo-fuzz
          cd termwiz/fuzz
      - name: Fuzz
        run: |
          source $HOME/.cargo/env
          cd termwiz/fuzz
          RUST_BACKTRACE=full cargo +nightly fuzz run escape_parse -- -max_total_time=60

